package main

import (
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestAnalyzeFileReportsStringLiteralCode(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `
package fixture

var _ = attunev1.ErrorResponse{Code: "VALIDATION"}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Len(t, got, 1)
	require.Equal(t, ruleCodeLiteral, got[0].Rule)
}

func TestAnalyzeFileAllowsEnumString(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `
package fixture

var _ = attunev1.ErrorResponse{Code: attunev1.ErrorCode_VALIDATION.String()}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAnalyzeFileAllowsLineDirective(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `
package fixture

var _ = attunev1.ErrorResponse{Code: "VALIDATION"} // errorcode:allow fixture
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAnalyzeFileSkipsGeneratedCode(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `// Code generated by protoc-gen-go. DO NOT EDIT.
package fixture

var _ = attunev1.ErrorResponse{Code: "VALIDATION"}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAnalyzeFileSkipsFileAllowDirective(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `// errorcode:file-allow test fixture
package fixture

var _ = attunev1.ErrorResponse{Code: "VALIDATION"}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAnalyzeFileReportsUnqualifiedErrorResponse(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `
package fixture

var _ = ErrorResponse{Code: "VALIDATION"}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Len(t, got, 1)
}

func TestAnalyzeFileIgnoresNonCodeFields(t *testing.T) {
	t.Parallel()

	path := writeLintFixture(t, `
package fixture

var _ = attunev1.ErrorResponse{Message: "bad request"}
`)

	got, err := analyzeFile(token.NewFileSet(), path)
	require.NoError(t, err)
	require.Empty(t, got)
}

func TestAnalyzeFileRejectsNonExistentPath(t *testing.T) {
	t.Parallel()

	_, err := analyzeFile(token.NewFileSet(), "/nonexistent/file.go")
	require.Error(t, err)
}

func TestExpandPaths(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	sub := filepath.Join(dir, "pkg")
	require.NoError(t, os.MkdirAll(sub, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(sub, "a.go"), []byte("package pkg"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(sub, "b.txt"), []byte("not go"), 0o644))

	files, err := expandPaths([]string{dir + "/..."})
	require.NoError(t, err)
	require.Len(t, files, 1)
	require.Contains(t, files[0], "a.go")
}

func TestExpandPathsSkipsVendor(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	vendor := filepath.Join(dir, "vendor", "pkg")
	require.NoError(t, os.MkdirAll(vendor, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(vendor, "v.go"), []byte("package pkg"), 0o644))

	files, err := expandPaths([]string{dir + "/..."})
	require.NoError(t, err)
	require.Empty(t, files)
}

func TestExpandPathsSkipsNodeModules(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	nm := filepath.Join(dir, "node_modules", "pkg")
	require.NoError(t, os.MkdirAll(nm, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(nm, "n.go"), []byte("package pkg"), 0o644))

	files, err := expandPaths([]string{dir + "/..."})
	require.NoError(t, err)
	require.Empty(t, files)
}

func TestExpandPathsSkipsPbFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "foo.pb.go"), []byte("package pb"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "bar.go"), []byte("package bar"), 0o644))

	files, err := expandPaths([]string{dir})
	require.NoError(t, err)
	require.Len(t, files, 1)
	require.Contains(t, files[0], "bar.go")
}

func TestIsErrorResponseType_Ident(t *testing.T) {
	t.Parallel()

	require.True(t, isErrorResponseType(&ast.Ident{Name: "ErrorResponse"}))
	require.False(t, isErrorResponseType(&ast.Ident{Name: "OtherType"}))
}

func TestIsErrorResponseType_Selector(t *testing.T) {
	t.Parallel()

	require.True(t, isErrorResponseType(&ast.SelectorExpr{
		X:   &ast.Ident{Name: "attunev1"},
		Sel: &ast.Ident{Name: "ErrorResponse"},
	}))
	require.False(t, isErrorResponseType(&ast.SelectorExpr{
		X:   &ast.Ident{Name: "attunev1"},
		Sel: &ast.Ident{Name: "OtherType"},
	}))
}

func TestIsErrorResponseType_OtherExpr(t *testing.T) {
	t.Parallel()

	require.False(t, isErrorResponseType(&ast.BasicLit{Kind: token.STRING, Value: `"x"`}))
}

func TestIsCodeKey(t *testing.T) {
	t.Parallel()

	require.True(t, isCodeKey(&ast.Ident{Name: "Code"}))
	require.False(t, isCodeKey(&ast.Ident{Name: "Message"}))
	require.False(t, isCodeKey(&ast.BasicLit{Kind: token.STRING}))
}

func TestIsStringLiteral(t *testing.T) {
	t.Parallel()

	require.True(t, isStringLiteral(&ast.BasicLit{Kind: token.STRING, Value: `"hello"`}))
	require.False(t, isStringLiteral(&ast.BasicLit{Kind: token.INT, Value: "42"}))
	require.False(t, isStringLiteral(&ast.Ident{Name: "x"}))
}

func writeLintFixture(t *testing.T, src string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "fixture.go")
	require.NoError(t, os.WriteFile(path, []byte(src), 0o600))
	return path
}
