// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/api_key.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface ApiKey {
  id: string;
  keyPrefix: string;
  label: string;
  isActive: boolean;
  /** RFC3339 */
  createdAt: string;
  /** RFC3339, null if never used */
  lastUsedAt?:
    | string
    | undefined;
  /** RFC3339, null if active */
  revokedAt?: string | undefined;
}

export interface ListApiKeysRequest {
}

export interface ListApiKeysResponse {
  items: ApiKey[];
}

export interface CreateApiKeyRequest {
  label: string;
}

export interface CreateApiKeyResponse {
  key?:
    | ApiKey
    | undefined;
  /** The raw secret — returned only here, once, at creation. */
  secret: string;
}

export interface DeleteApiKeyRequest {
  /** path param (UUID) */
  id: string;
}

export interface DeleteApiKeyResponse {
}

/** ApiKeyService manages a tenant's external ingest API keys (console). */
export interface ApiKeyService {
  /** GET /fb/v1/console/api-keys */
  ListApiKeys(request: ListApiKeysRequest): Promise<ListApiKeysResponse>;
  /** POST /fb/v1/console/api-keys — returns the raw secret once. */
  CreateApiKey(request: CreateApiKeyRequest): Promise<CreateApiKeyResponse>;
  /** DELETE /fb/v1/console/api-keys/{id} — revoke (204). */
  DeleteApiKey(request: DeleteApiKeyRequest): Promise<DeleteApiKeyResponse>;
}
