// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/api_key.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface ApiKey {
  id: string;
  keyPrefix: string;
  label: string;
  isActive: boolean;
  /** RFC3339 */
  createdAt: string;
  /** RFC3339, null if never used */
  lastUsedAt?:
    | string
    | undefined;
  /** RFC3339, null if active */
  revokedAt?:
    | string
    | undefined;
  /** granted scopes */
  scopes: string[];
}

export interface ListApiKeysRequest {
}

export interface ListApiKeysResponse {
  items: ApiKey[];
}

export interface CreateApiKeyRequest {
  label: string;
  /** optional, defaults to full_access preset */
  scopes: string[];
}

export interface CreateApiKeyResponse {
  key?:
    | ApiKey
    | undefined;
  /** The raw secret — returned only here, once, at creation. */
  secret: string;
}

export interface DeleteApiKeyRequest {
  /** path param (UUID) */
  id: string;
}

export interface DeleteApiKeyResponse {
}

/** Scope metadata */
export interface ListScopesRequest {
}

export interface ListScopesResponse {
  scopes: ScopeInfo[];
}

export interface ScopeInfo {
  /** e.g., "feedback:read" */
  scope: string;
  /** e.g., "feedback" */
  resource: string;
  /** e.g., "read" */
  action: string;
  /** human-readable */
  description: string;
  /** scopes this one implies (hierarchy) */
  implies: string[];
}

/** Preset templates */
export interface ListScopePresetsRequest {
}

export interface ListScopePresetsResponse {
  presets: ScopePreset[];
}

export interface ScopePreset {
  /** e.g., "ingest_only" */
  id: string;
  /** e.g., "Ingest Only" */
  name: string;
  /** human-readable */
  description: string;
  scopes: string[];
}

/** ApiKeyService manages a tenant's external ingest API keys (console). */
export interface ApiKeyService {
  /** GET /fb/v1/console/api-keys */
  ListApiKeys(request: ListApiKeysRequest): Promise<ListApiKeysResponse>;
  /** POST /fb/v1/console/api-keys — returns the raw secret once. */
  CreateApiKey(request: CreateApiKeyRequest): Promise<CreateApiKeyResponse>;
  /** DELETE /fb/v1/console/api-keys/{id} — revoke (204). */
  DeleteApiKey(request: DeleteApiKeyRequest): Promise<DeleteApiKeyResponse>;
  /** GET /fb/v1/console/api-keys/scopes — list available scopes. */
  ListScopes(request: ListScopesRequest): Promise<ListScopesResponse>;
  /** GET /fb/v1/console/api-keys/presets — list scope preset templates. */
  ListScopePresets(request: ListScopePresetsRequest): Promise<ListScopePresetsResponse>;
}
