// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/audit.proto

/* eslint-disable */
import { type HttpBody } from "../../google/api/httpbody";

export const protobufPackage = "attune.v1";

export interface AuditLogEntry {
  id: string;
  actorType: string;
  actorId: string;
  actorEmail: string;
  actorIp: string;
  actorUserAgent: string;
  action: string;
  targetType: string;
  targetId: string;
  summary: string;
  beforeJson: string;
  afterJson: string;
  createdAt: string;
}

export interface ListAuditLogRequest {
  action: string;
  actorType: string;
  actorId: string;
  targetType: string;
  targetId: string;
  from: string;
  to: string;
  limit: number;
  cursor?: string | undefined;
  actions: string[];
}

export interface ListAuditLogResponse {
  items: AuditLogEntry[];
  nextCursor?: string | undefined;
}

export interface ExportAuditLogCSVRequest {
  action: string;
  actorType: string;
  actorId: string;
  targetType: string;
  targetId: string;
  from: string;
  to: string;
  actions: string[];
}

export interface AuditLogService {
  ListAuditLog(request: ListAuditLogRequest): Promise<ListAuditLogResponse>;
  ExportAuditLogCSV(request: ExportAuditLogCSVRequest): Promise<HttpBody>;
}
