// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/batch.proto

/* eslint-disable */
import { type FeedbackFilter } from "./common";

export const protobufPackage = "attune.v1";

/**
 * BatchFeedbackRequest is the envelope for all batch operations.
 * Either feedback_ids or query must be provided to select rows.
 */
export interface BatchFeedbackRequest {
  /** Explicit row IDs to operate on (mutually exclusive with query). */
  feedbackIds: string[];
  /** Filter query to select rows (mutually exclusive with feedback_ids). */
  query?:
    | FeedbackFilter
    | undefined;
  /**
   * Safety cap: refuse if query matches more than this many rows.
   * Required when using query-based selection.
   */
  maxAffected?:
    | number
    | undefined;
  /**
   * Confirmation count: proceed only if matched count equals this.
   * Prevents TOCTOU races between preview and execute.
   */
  confirmCount?:
    | number
    | undefined;
  /** If true, return what would happen without making changes. */
  dryRun: boolean;
  /** The operation to perform. */
  operation?:
    | BatchOperation
    | undefined;
  /**
   * Client-generated idempotency key for safe retries.
   * Same key + same params = return cached result.
   * Same key + different params = IDEMPOTENCY_CONFLICT error.
   */
  idempotencyKey?:
    | string
    | undefined;
  /**
   * Optimistic concurrency: reject if any row was modified since this timestamp.
   * Format: RFC3339.
   */
  ifUnmodifiedSince?: string | undefined;
}

/** BatchOperation is the discriminated union of supported batch operations. */
export interface BatchOperation {
  tag?: BatchTagOp | undefined;
  workflow?: BatchWorkflowOp | undefined;
  delete?: BatchDeleteOp | undefined;
}

/** BatchTagOp adds and/or removes tags from selected rows. */
export interface BatchTagOp {
  /** Tag IDs to add to all selected rows. */
  addTagIds: string[];
  /** Tag IDs to remove from all selected rows. */
  removeTagIds: string[];
}

/** BatchWorkflowOp transitions selected rows to a new workflow state. */
export interface BatchWorkflowOp {
  /** Target workflow state ID. */
  toStateId: string;
  /** Optional audit comment for the transition. */
  comment: string;
}

/** BatchDeleteOp soft-deletes or hard-deletes selected rows. */
export interface BatchDeleteOp {
  /** If true, permanently delete rows. If false (default), soft-delete. */
  hard: boolean;
}

/** BatchFeedbackResponse reports the outcome of a batch operation. */
export interface BatchFeedbackResponse {
  /** Total rows matched by the selection criteria. */
  totalMatched: number;
  /** Number of rows successfully updated. */
  succeeded: number;
  /** Number of rows skipped (already in target state, etc.). */
  skipped: number;
  /** Per-row failures with error details. */
  failed: BatchItemFailure[];
  /** For async operations, the job ID to poll for status. */
  jobId?:
    | string
    | undefined;
  /** URL to poll for job status (convenience for clients). */
  jobStatusUrl?: string | undefined;
}

/** BatchItemFailure describes why a single row failed in a batch operation. */
export interface BatchItemFailure {
  /** The feedback row that failed. */
  feedbackId: string;
  /** Machine-readable error code (ErrorCode enum name). */
  code: string;
  /** Human-readable error message. */
  message: string;
  /** For optimistic concurrency failures: the row's current updated_at. */
  currentUpdatedAt?: string | undefined;
}

/**
 * BatchService provides batch operations on feedback rows (#30).
 * Operations can target rows by explicit IDs or by filter query.
 */
export interface BatchService {
  BatchFeedback(request: BatchFeedbackRequest): Promise<BatchFeedbackResponse>;
}
