// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/common.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * ErrorResponse is the JSON body returned on 4xx/5xx by attune's public + console
 * APIs: a single human-facing message, e.g. {"error": "content is required"}.
 * (The console's richer envelope — code / message / request_id — folds in as the
 * console endpoints migrate; see proposal 2026-06-06-protobuf-idl-contract.)
 */
export interface ErrorResponse {
  error: string;
}
