// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/common.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * ErrorResponse is the JSON body returned on any 4xx/5xx across attune's HTTP
 * APIs — a stable machine-readable `code`, a human-facing `message`, and the
 * request id for support/tracing:
 *
 *   {"code":"validation","message":"content is required","requestId":"abc123"}
 *
 * One envelope for the public ingest API and the console alike.
 */
export interface ErrorResponse {
  /**
   * Stable error code, e.g. unauthorized / bad_request / validation /
   * not_found / conflict / internal. Safe for clients to switch on.
   */
  code: string;
  /** Human-facing message. Not stable; do not switch on it. */
  message: string;
  /** The request id (chi X-Request-ID) for support / log correlation. */
  requestId: string;
}
