// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/customer_request.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum CustomerRequestStatus {
  CUSTOMER_REQUEST_STATUS_UNSPECIFIED = "CUSTOMER_REQUEST_STATUS_UNSPECIFIED",
  CUSTOMER_REQUEST_STATUS_OPEN = "CUSTOMER_REQUEST_STATUS_OPEN",
  CUSTOMER_REQUEST_STATUS_PLANNED = "CUSTOMER_REQUEST_STATUS_PLANNED",
  CUSTOMER_REQUEST_STATUS_IN_PROGRESS = "CUSTOMER_REQUEST_STATUS_IN_PROGRESS",
  CUSTOMER_REQUEST_STATUS_SHIPPED = "CUSTOMER_REQUEST_STATUS_SHIPPED",
  CUSTOMER_REQUEST_STATUS_CANCELLED = "CUSTOMER_REQUEST_STATUS_CANCELLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestPriority {
  CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED = "CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED",
  CUSTOMER_REQUEST_PRIORITY_NONE = "CUSTOMER_REQUEST_PRIORITY_NONE",
  CUSTOMER_REQUEST_PRIORITY_LOW = "CUSTOMER_REQUEST_PRIORITY_LOW",
  CUSTOMER_REQUEST_PRIORITY_MEDIUM = "CUSTOMER_REQUEST_PRIORITY_MEDIUM",
  CUSTOMER_REQUEST_PRIORITY_HIGH = "CUSTOMER_REQUEST_PRIORITY_HIGH",
  CUSTOMER_REQUEST_PRIORITY_URGENT = "CUSTOMER_REQUEST_PRIORITY_URGENT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestImportance {
  CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED = "CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED",
  CUSTOMER_REQUEST_IMPORTANCE_NORMAL = "CUSTOMER_REQUEST_IMPORTANCE_NORMAL",
  CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT = "CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT",
  CUSTOMER_REQUEST_IMPORTANCE_CRITICAL = "CUSTOMER_REQUEST_IMPORTANCE_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestVisibility {
  CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED = "CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED",
  CUSTOMER_REQUEST_VISIBILITY_ACTIVE = "CUSTOMER_REQUEST_VISIBILITY_ACTIVE",
  CUSTOMER_REQUEST_VISIBILITY_MERGED = "CUSTOMER_REQUEST_VISIBILITY_MERGED",
  CUSTOMER_REQUEST_VISIBILITY_ARCHIVED = "CUSTOMER_REQUEST_VISIBILITY_ARCHIVED",
  CUSTOMER_REQUEST_VISIBILITY_ALL = "CUSTOMER_REQUEST_VISIBILITY_ALL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestSort {
  CUSTOMER_REQUEST_SORT_UNSPECIFIED = "CUSTOMER_REQUEST_SORT_UNSPECIFIED",
  CUSTOMER_REQUEST_SORT_UPDATED_AT = "CUSTOMER_REQUEST_SORT_UPDATED_AT",
  CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT = "CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT",
  CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT = "CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT",
  CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT = "CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT",
  CUSTOMER_REQUEST_SORT_PRIORITY = "CUSTOMER_REQUEST_SORT_PRIORITY",
  CUSTOMER_REQUEST_SORT_REVENUE_IMPACT = "CUSTOMER_REQUEST_SORT_REVENUE_IMPACT",
  CUSTOMER_REQUEST_SORT_DECISION_SCORE = "CUSTOMER_REQUEST_SORT_DECISION_SCORE",
  CUSTOMER_REQUEST_SORT_DELIVERY_HEALTH = "CUSTOMER_REQUEST_SORT_DELIVERY_HEALTH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestIssueSyncState {
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_UNSPECIFIED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_UNSPECIFIED",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_MANUAL = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_MANUAL",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_PENDING = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_PENDING",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_SYNCED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_SYNCED",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_STALE = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_STALE",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_FAILED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestDeliveryHealth {
  CUSTOMER_REQUEST_DELIVERY_HEALTH_UNSPECIFIED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_UNSPECIFIED",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_NO_LINKS = "CUSTOMER_REQUEST_DELIVERY_HEALTH_NO_LINKS",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_MANUAL = "CUSTOMER_REQUEST_DELIVERY_HEALTH_MANUAL",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_PENDING = "CUSTOMER_REQUEST_DELIVERY_HEALTH_PENDING",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_SYNCED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_SYNCED",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_STALE = "CUSTOMER_REQUEST_DELIVERY_HEALTH_STALE",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_FAILED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = "SORT_DIRECTION_UNSPECIFIED",
  SORT_DIRECTION_ASC = "SORT_DIRECTION_ASC",
  SORT_DIRECTION_DESC = "SORT_DIRECTION_DESC",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestDecisionScoreFactorKind {
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_UNSPECIFIED = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_UNSPECIFIED",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_PRIORITY = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_PRIORITY",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_FEEDBACK = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_FEEDBACK",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_CUSTOMERS = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_CUSTOMERS",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_ACCOUNTS = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_ACCOUNTS",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_VOTES = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_VOTES",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_REVENUE = "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_REVENUE",
  CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_DELIVERY_HEALTH =
    "CUSTOMER_REQUEST_DECISION_SCORE_FACTOR_KIND_DELIVERY_HEALTH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestEvidenceConfidence {
  CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_UNSPECIFIED = "CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_UNSPECIFIED",
  CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_LOW = "CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_LOW",
  CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_MEDIUM = "CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_MEDIUM",
  CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_HIGH = "CUSTOMER_REQUEST_EVIDENCE_CONFIDENCE_HIGH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestEvidenceQualityReason {
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_UNSPECIFIED = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_UNSPECIFIED",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_SUPPORTING_FEEDBACK =
    "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_SUPPORTING_FEEDBACK",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_LOW_FEEDBACK_VOLUME =
    "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_LOW_FEEDBACK_VOLUME",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SINGLE_CUSTOMER = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SINGLE_CUSTOMER",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_ACCOUNT_CONTEXT =
    "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_ACCOUNT_CONTEXT",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_STALE_EVIDENCE = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_STALE_EVIDENCE",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_DELIVERY_LINK =
    "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_NO_DELIVERY_LINK",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_HIDDEN_FEEDBACK = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_HIDDEN_FEEDBACK",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SUPPORTING_FEEDBACK =
    "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SUPPORTING_FEEDBACK",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_MULTI_CUSTOMER = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_MULTI_CUSTOMER",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_ACCOUNT_CONTEXT = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_ACCOUNT_CONTEXT",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_FRESH_EVIDENCE = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_FRESH_EVIDENCE",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_DELIVERY_LINKED = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_DELIVERY_LINKED",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SINGLE_SOURCE = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_SINGLE_SOURCE",
  CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_MULTI_SOURCE = "CUSTOMER_REQUEST_EVIDENCE_QUALITY_REASON_MULTI_SOURCE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestDecisionPublicSafeState {
  CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_UNSPECIFIED = "CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_UNSPECIFIED",
  CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_PUBLIC_SAFE = "CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_PUBLIC_SAFE",
  CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_NEEDS_REVIEW = "CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_NEEDS_REVIEW",
  CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_INTERNAL_ONLY =
    "CUSTOMER_REQUEST_DECISION_PUBLIC_SAFE_STATE_INTERNAL_ONLY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestAccountSignalKind {
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_UNSPECIFIED = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_UNSPECIFIED",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_DELIVERY_RISK = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_DELIVERY_RISK",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_HIGH_PRIORITY_DEMAND =
    "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_HIGH_PRIORITY_DEMAND",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_REVENUE_IMPACT = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_REVENUE_IMPACT",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_EVIDENCE_BREADTH = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_EVIDENCE_BREADTH",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_EVIDENCE_GAP = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_EVIDENCE_GAP",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_SHIPPED_OUTCOME = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_KIND_SHIPPED_OUTCOME",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestAccountSignalSeverity {
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_UNSPECIFIED = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_UNSPECIFIED",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_POSITIVE = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_POSITIVE",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_INFO = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_INFO",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_WARNING = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_WARNING",
  CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_CRITICAL = "CUSTOMER_REQUEST_ACCOUNT_SIGNAL_SEVERITY_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestAccountEventKind {
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_UNSPECIFIED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_UNSPECIFIED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_REQUEST_CREATED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_REQUEST_CREATED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_FEEDBACK_LINKED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_FEEDBACK_LINKED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_CUSTOMER_LINKED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_CUSTOMER_LINKED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_VOTE_ADDED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_VOTE_ADDED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_ISSUE_LINKED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_ISSUE_LINKED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_ISSUE_SYNCED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_ISSUE_SYNCED",
  CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_NOTE_ADDED = "CUSTOMER_REQUEST_ACCOUNT_EVENT_KIND_NOTE_ADDED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface CustomerRequestOwner {
  id: string;
  memberType: string;
  userId: string;
  email: string;
  role: string;
}

export interface CustomerRequestDecisionScoreFactor {
  kind: CustomerRequestDecisionScoreFactorKind;
  rawCount: number;
  rawValueCents: string;
  weight: number;
  cap: number;
  unitCents: string;
  contribution: number;
  capped: boolean;
  contributesToScore: boolean;
}

export interface CustomerRequestEvidenceQuality {
  score: number;
  confidence: CustomerRequestEvidenceConfidence;
  evidenceCount: number;
  sourceCount: number;
  customerCount: number;
  accountCount: number;
  latestEvidenceAt: string;
  stale: boolean;
  lowConfidence: boolean;
  gapReasons: CustomerRequestEvidenceQualityReason[];
  strengths: CustomerRequestEvidenceQualityReason[];
}

export interface CustomerRequestSummary {
  id: string;
  displayId: string;
  displayNumber: string;
  title: string;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  owner?: CustomerRequestOwner | undefined;
  supportingFeedbackCount: number;
  customerCount: number;
  linkedIssueCount: number;
  hiddenFeedbackCount: number;
  firstFeedbackAt: string;
  latestFeedbackAt: string;
  mergedIntoRequestId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string | undefined;
  accountCount: number;
  voteCount: number;
  duplicateRequestCount: number;
  revenueImpactCents: string;
  revenueCurrency: string;
  decisionScore: number;
  decisionScoreExplanation: string;
  deliveryHealth: CustomerRequestDeliveryHealth;
  syncedIssueCount: number;
  staleIssueCount: number;
  failedIssueCount: number;
  pendingIssueCount: number;
  manualIssueCount: number;
  decisionScoreFactors: CustomerRequestDecisionScoreFactor[];
  evidenceQuality?: CustomerRequestEvidenceQuality | undefined;
}

export interface CustomerRequestFeedbackEvidence {
  feedbackId: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  subjectDisplay: string;
  enrichedTitle: string;
  importance: CustomerRequestImportance;
  note: string;
  linkedBy: string;
  linkedAt: string;
  createdAt: string;
}

export interface CustomerRequestIssueLink {
  id: string;
  provider: string;
  externalKey: string;
  externalUrl: string;
  title: string;
  status: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  lastSyncedAt: string;
  syncState: CustomerRequestIssueSyncState;
  externalStatusCategory: string;
  externalAssignee: string;
  externalUpdatedAt: string;
  syncError: string;
}

export interface CustomerRequestDeliveryArtifact {
  id: string;
  provider: string;
  artifactType: string;
  externalKey: string;
  externalUrl: string;
  title: string;
  status: string;
  statusCategory: string;
  assignee: string;
  syncState: CustomerRequestIssueSyncState;
  health: CustomerRequestDeliveryHealth;
  lastSeenAt: string;
  source: string;
  syncError: string;
}

export interface CustomerRequestDeliveryRelationship {
  id: string;
  sourceArtifactId: string;
  targetArtifactId: string;
  relationshipType: string;
  provider: string;
  createdAt: string;
}

export interface CustomerRequestDeliveryGraph {
  artifacts: CustomerRequestDeliveryArtifact[];
  relationships: CustomerRequestDeliveryRelationship[];
  health: CustomerRequestDeliveryHealth;
  healthExplanation: string;
  updatedAt: string;
}

export interface CustomerRequestCustomerLink {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  note: string;
  createdBy: string;
  createdAt: string;
  accountProfile?: CustomerRequestAccountProfile | undefined;
}

export interface CustomerRequestVote {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  weight: number;
  note: string;
  createdBy: string;
  createdAt: string;
  accountProfile?: CustomerRequestAccountProfile | undefined;
}

export interface CustomerRequestAccountProfile {
  accountKey: string;
  accountDisplay: string;
  revenueCents: string;
  revenueCurrency: string;
  tier: string;
  sizeSegment: string;
  lifecycleStatus: string;
  crmProvider: string;
  crmExternalId: string;
  source: string;
  updatedAt: string;
}

export interface CustomerRequestDuplicate {
  id: string;
  displayId: string;
  title: string;
  mergedAt: string;
}

export interface CustomerRequestNote {
  id: string;
  body: string;
  createdBy: string;
  createdAt: string;
}

export interface CustomerRequestAuditEntry {
  id: string;
  action: string;
  actorType: string;
  actorId: string;
  summary: string;
  createdAt: string;
}

export interface CustomerRequestDecisionRecord {
  auditId: string;
  action: string;
  actorType: string;
  actorId: string;
  summary: string;
  createdAt: string;
  statusChanged: boolean;
  oldStatus: CustomerRequestStatus;
  newStatus: CustomerRequestStatus;
  priorityChanged: boolean;
  oldPriority: CustomerRequestPriority;
  newPriority: CustomerRequestPriority;
  ownerChanged: boolean;
  oldOwnerMemberId: string;
  newOwnerMemberId: string;
  titleChanged: boolean;
  descriptionChanged: boolean;
  hasDecisionSnapshot: boolean;
  decisionScore: number;
  decisionScoreFactors: CustomerRequestDecisionScoreFactor[];
  deliveryHealth: CustomerRequestDeliveryHealth;
  supportingFeedbackCount: number;
  customerCount: number;
  accountCount: number;
  voteCount: number;
  revenueImpactCents: string;
  revenueCurrency: string;
  decisionRationale: string;
  ownerMemberId: string;
  ownerDisplay: string;
  evidenceBundleRef: string;
  publicSafeState: CustomerRequestDecisionPublicSafeState;
  publicSafeReasons: string[];
}

export interface CustomerRequestDetail {
  request?: CustomerRequestSummary | undefined;
  description: string;
  feedback: CustomerRequestFeedbackEvidence[];
  issueLinks: CustomerRequestIssueLink[];
  auditEntries: CustomerRequestAuditEntry[];
  customers: CustomerRequestCustomerLink[];
  votes: CustomerRequestVote[];
  duplicates: CustomerRequestDuplicate[];
  accountProfiles: CustomerRequestAccountProfile[];
  notes: CustomerRequestNote[];
  deliveryGraph?: CustomerRequestDeliveryGraph | undefined;
  decisionRecords: CustomerRequestDecisionRecord[];
}

export interface CustomerRequestAccountDecisionSignal {
  kind: CustomerRequestAccountSignalKind;
  severity: CustomerRequestAccountSignalSeverity;
  count: number;
  valueCents: string;
  score: number;
}

export interface CustomerRequestAccountEvent {
  kind: CustomerRequestAccountEventKind;
  requestId: string;
  requestDisplayId: string;
  requestTitle: string;
  occurredAt: string;
  actorId: string;
  subjectDisplay: string;
  source: string;
  description: string;
  feedbackId: string;
  issueProvider: string;
  issueKey: string;
  issueUrl: string;
  issueSyncState: CustomerRequestIssueSyncState;
}

export interface CustomerRequestAccountSummary {
  accountKey: string;
  accountProfile?: CustomerRequestAccountProfile | undefined;
  requestCount: number;
  feedbackCount: number;
  customerCount: number;
  voteCount: number;
  issueCount: number;
  syncedIssueCount: number;
  staleIssueCount: number;
  failedIssueCount: number;
  pendingIssueCount: number;
  manualIssueCount: number;
  revenueImpactCents: string;
  revenueCurrency: string;
  highPriorityRequestCount: number;
  shippedRequestCount: number;
  staleOrFailedIssueCount: number;
  timeline: CustomerRequestSummary[];
  averageDecisionScore: number;
  topDecisionScore: number;
  decisionSignals: CustomerRequestAccountDecisionSignal[];
  events: CustomerRequestAccountEvent[];
}

export interface CustomerRequestScoringSettings {
  tenantId: string;
  priorityNoneWeight: number;
  priorityLowWeight: number;
  priorityMediumWeight: number;
  priorityHighWeight: number;
  priorityUrgentWeight: number;
  feedbackWeight: number;
  feedbackCap: number;
  customerWeight: number;
  customerCap: number;
  accountWeight: number;
  accountCap: number;
  voteWeight: number;
  voteCap: number;
  revenueCentsPerPoint: string;
  revenueCap: number;
  updatedBy: string;
  updatedAt: string;
}

export interface GetCustomerRequestScoringSettingsRequest {
}

export interface UpdateCustomerRequestScoringSettingsRequest {
  priorityNoneWeight?: number | undefined;
  priorityLowWeight?: number | undefined;
  priorityMediumWeight?: number | undefined;
  priorityHighWeight?: number | undefined;
  priorityUrgentWeight?: number | undefined;
  feedbackWeight?: number | undefined;
  feedbackCap?: number | undefined;
  customerWeight?: number | undefined;
  customerCap?: number | undefined;
  accountWeight?: number | undefined;
  accountCap?: number | undefined;
  voteWeight?: number | undefined;
  voteCap?: number | undefined;
  revenueCentsPerPoint?: string | undefined;
  revenueCap?: number | undefined;
}

export interface CustomerRequestSavedViewState {
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  feedbackId?: string | undefined;
  accountKey?: string | undefined;
}

export interface CustomerRequestSavedView {
  id: string;
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface ListCustomerRequestSavedViewsRequest {
}

export interface ListCustomerRequestSavedViewsResponse {
  views: CustomerRequestSavedView[];
}

export interface CreateCustomerRequestSavedViewRequest {
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
}

export interface UpdateCustomerRequestSavedViewRequest {
  id: string;
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
}

export interface CustomerRequestSavedViewResponse {
  view?: CustomerRequestSavedView | undefined;
}

export interface DeleteCustomerRequestSavedViewRequest {
  id: string;
}

export interface DeleteCustomerRequestSavedViewResponse {
}

export interface ListCustomerRequestsRequest {
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  limit?: number | undefined;
  cursor?: string | undefined;
  feedbackId?: string | undefined;
  cohortId?: string | undefined;
  accountKey?: string | undefined;
}

export interface ListCustomerRequestsResponse {
  requests: CustomerRequestSummary[];
  nextCursor?: string | undefined;
}

export interface GetCustomerRequestAccountSummaryRequest {
  accountKey: string;
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  feedbackId?: string | undefined;
  timelineLimit?: number | undefined;
  eventLimit?: number | undefined;
}

export interface GetCustomerRequestRequest {
  id: string;
  evidenceLimit?: number | undefined;
}

export interface CreateCustomerRequestRequest {
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface UpdateCustomerRequestRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  status?: CustomerRequestStatus | undefined;
  priority?: CustomerRequestPriority | undefined;
  ownerMemberId?: string | undefined;
}

export interface PromoteFeedbackToCustomerRequestRequest {
  feedbackIds: string[];
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface LinkFeedbackToCustomerRequestRequest {
  id: string;
  feedbackId: string;
  importance: CustomerRequestImportance;
  note?: string | undefined;
}

export interface UnlinkFeedbackFromCustomerRequestRequest {
  id: string;
  feedbackId: string;
}

export interface LinkCustomerToCustomerRequestRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  note?: string | undefined;
  accountRevenueCents?: string | undefined;
  accountRevenueCurrency?: string | undefined;
  accountTier?: string | undefined;
  accountSizeSegment?: string | undefined;
  accountLifecycleStatus?: string | undefined;
  accountCrmProvider?: string | undefined;
  accountCrmExternalId?: string | undefined;
}

export interface UnlinkCustomerFromCustomerRequestRequest {
  id: string;
  customerLinkId: string;
}

export interface AddCustomerRequestVoteRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  weight: number;
  note?: string | undefined;
  accountRevenueCents?: string | undefined;
  accountRevenueCurrency?: string | undefined;
  accountTier?: string | undefined;
  accountSizeSegment?: string | undefined;
  accountLifecycleStatus?: string | undefined;
  accountCrmProvider?: string | undefined;
  accountCrmExternalId?: string | undefined;
}

export interface RemoveCustomerRequestVoteRequest {
  id: string;
  voteId: string;
}

export interface AddCustomerRequestNoteRequest {
  id: string;
  body: string;
}

export interface DeleteCustomerRequestNoteRequest {
  id: string;
  noteId: string;
}

export interface MergeCustomerRequestsRequest {
  sourceId: string;
  targetId: string;
  idempotencyKey: string;
}

export interface LinkCustomerRequestIssueRequest {
  id: string;
  provider: string;
  externalUrl: string;
  externalKey?: string | undefined;
  title?: string | undefined;
  status?: string | undefined;
  connectionId?: string | undefined;
  mappingId?: string | undefined;
  issueNumber?: string | undefined;
}

export interface CreateCustomerRequestGitHubIssueRequest {
  id: string;
  connectionId?: string | undefined;
  mappingId?: string | undefined;
}

export interface CreateCustomerRequestGitHubIssueResponse {
  detail?: CustomerRequestDetail | undefined;
  runId: string;
  connectionId: string;
  mappingId: string;
}

export interface UnlinkCustomerRequestIssueRequest {
  id: string;
  issueLinkId: string;
}

export interface RecordCustomerRequestIssueSyncRequest {
  id: string;
  issueLinkId: string;
  syncState: CustomerRequestIssueSyncState;
  status?: string | undefined;
  externalStatusCategory?: string | undefined;
  externalAssignee?: string | undefined;
  externalUpdatedAt?: string | undefined;
  syncError?: string | undefined;
}

export interface CustomerRequestService {
  ListCustomerRequests(request: ListCustomerRequestsRequest): Promise<ListCustomerRequestsResponse>;
  GetCustomerRequestAccountSummary(
    request: GetCustomerRequestAccountSummaryRequest,
  ): Promise<CustomerRequestAccountSummary>;
  GetCustomerRequestScoringSettings(
    request: GetCustomerRequestScoringSettingsRequest,
  ): Promise<CustomerRequestScoringSettings>;
  UpdateCustomerRequestScoringSettings(
    request: UpdateCustomerRequestScoringSettingsRequest,
  ): Promise<CustomerRequestScoringSettings>;
  ListCustomerRequestSavedViews(
    request: ListCustomerRequestSavedViewsRequest,
  ): Promise<ListCustomerRequestSavedViewsResponse>;
  CreateCustomerRequestSavedView(
    request: CreateCustomerRequestSavedViewRequest,
  ): Promise<CustomerRequestSavedViewResponse>;
  UpdateCustomerRequestSavedView(
    request: UpdateCustomerRequestSavedViewRequest,
  ): Promise<CustomerRequestSavedViewResponse>;
  DeleteCustomerRequestSavedView(
    request: DeleteCustomerRequestSavedViewRequest,
  ): Promise<DeleteCustomerRequestSavedViewResponse>;
  GetCustomerRequest(request: GetCustomerRequestRequest): Promise<CustomerRequestDetail>;
  CreateCustomerRequest(request: CreateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UpdateCustomerRequest(request: UpdateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  PromoteFeedbackToCustomerRequest(request: PromoteFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkFeedbackToCustomerRequest(request: LinkFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkFeedbackFromCustomerRequest(request: UnlinkFeedbackFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkCustomerToCustomerRequest(request: LinkCustomerToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkCustomerFromCustomerRequest(request: UnlinkCustomerFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  AddCustomerRequestVote(request: AddCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  RemoveCustomerRequestVote(request: RemoveCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  AddCustomerRequestNote(request: AddCustomerRequestNoteRequest): Promise<CustomerRequestDetail>;
  DeleteCustomerRequestNote(request: DeleteCustomerRequestNoteRequest): Promise<CustomerRequestDetail>;
  MergeCustomerRequests(request: MergeCustomerRequestsRequest): Promise<CustomerRequestDetail>;
  LinkCustomerRequestIssue(request: LinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
  CreateCustomerRequestGitHubIssue(
    request: CreateCustomerRequestGitHubIssueRequest,
  ): Promise<CreateCustomerRequestGitHubIssueResponse>;
  UnlinkCustomerRequestIssue(request: UnlinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
  RecordCustomerRequestIssueSync(request: RecordCustomerRequestIssueSyncRequest): Promise<CustomerRequestDetail>;
}
