// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/customer_request.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum CustomerRequestStatus {
  CUSTOMER_REQUEST_STATUS_UNSPECIFIED = "CUSTOMER_REQUEST_STATUS_UNSPECIFIED",
  CUSTOMER_REQUEST_STATUS_OPEN = "CUSTOMER_REQUEST_STATUS_OPEN",
  CUSTOMER_REQUEST_STATUS_PLANNED = "CUSTOMER_REQUEST_STATUS_PLANNED",
  CUSTOMER_REQUEST_STATUS_IN_PROGRESS = "CUSTOMER_REQUEST_STATUS_IN_PROGRESS",
  CUSTOMER_REQUEST_STATUS_SHIPPED = "CUSTOMER_REQUEST_STATUS_SHIPPED",
  CUSTOMER_REQUEST_STATUS_CANCELLED = "CUSTOMER_REQUEST_STATUS_CANCELLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestPriority {
  CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED = "CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED",
  CUSTOMER_REQUEST_PRIORITY_NONE = "CUSTOMER_REQUEST_PRIORITY_NONE",
  CUSTOMER_REQUEST_PRIORITY_LOW = "CUSTOMER_REQUEST_PRIORITY_LOW",
  CUSTOMER_REQUEST_PRIORITY_MEDIUM = "CUSTOMER_REQUEST_PRIORITY_MEDIUM",
  CUSTOMER_REQUEST_PRIORITY_HIGH = "CUSTOMER_REQUEST_PRIORITY_HIGH",
  CUSTOMER_REQUEST_PRIORITY_URGENT = "CUSTOMER_REQUEST_PRIORITY_URGENT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestImportance {
  CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED = "CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED",
  CUSTOMER_REQUEST_IMPORTANCE_NORMAL = "CUSTOMER_REQUEST_IMPORTANCE_NORMAL",
  CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT = "CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT",
  CUSTOMER_REQUEST_IMPORTANCE_CRITICAL = "CUSTOMER_REQUEST_IMPORTANCE_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestVisibility {
  CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED = "CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED",
  CUSTOMER_REQUEST_VISIBILITY_ACTIVE = "CUSTOMER_REQUEST_VISIBILITY_ACTIVE",
  CUSTOMER_REQUEST_VISIBILITY_MERGED = "CUSTOMER_REQUEST_VISIBILITY_MERGED",
  CUSTOMER_REQUEST_VISIBILITY_ARCHIVED = "CUSTOMER_REQUEST_VISIBILITY_ARCHIVED",
  CUSTOMER_REQUEST_VISIBILITY_ALL = "CUSTOMER_REQUEST_VISIBILITY_ALL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestSort {
  CUSTOMER_REQUEST_SORT_UNSPECIFIED = "CUSTOMER_REQUEST_SORT_UNSPECIFIED",
  CUSTOMER_REQUEST_SORT_UPDATED_AT = "CUSTOMER_REQUEST_SORT_UPDATED_AT",
  CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT = "CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT",
  CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT = "CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT",
  CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT = "CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT",
  CUSTOMER_REQUEST_SORT_PRIORITY = "CUSTOMER_REQUEST_SORT_PRIORITY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = "SORT_DIRECTION_UNSPECIFIED",
  SORT_DIRECTION_ASC = "SORT_DIRECTION_ASC",
  SORT_DIRECTION_DESC = "SORT_DIRECTION_DESC",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface CustomerRequestOwner {
  id: string;
  memberType: string;
  userId: string;
  email: string;
  role: string;
}

export interface CustomerRequestSummary {
  id: string;
  displayId: string;
  displayNumber: string;
  title: string;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  owner?: CustomerRequestOwner | undefined;
  supportingFeedbackCount: number;
  customerCount: number;
  linkedIssueCount: number;
  hiddenFeedbackCount: number;
  firstFeedbackAt: string;
  latestFeedbackAt: string;
  mergedIntoRequestId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string | undefined;
  accountCount: number;
  voteCount: number;
  duplicateRequestCount: number;
}

export interface CustomerRequestFeedbackEvidence {
  feedbackId: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  subjectDisplay: string;
  enrichedTitle: string;
  importance: CustomerRequestImportance;
  note: string;
  linkedBy: string;
  linkedAt: string;
  createdAt: string;
}

export interface CustomerRequestIssueLink {
  id: string;
  provider: string;
  externalKey: string;
  externalUrl: string;
  title: string;
  status: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  lastSyncedAt: string;
}

export interface CustomerRequestCustomerLink {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  note: string;
  createdBy: string;
  createdAt: string;
}

export interface CustomerRequestVote {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  weight: number;
  note: string;
  createdBy: string;
  createdAt: string;
}

export interface CustomerRequestDuplicate {
  id: string;
  displayId: string;
  title: string;
  mergedAt: string;
}

export interface CustomerRequestAuditEntry {
  id: string;
  action: string;
  actorType: string;
  actorId: string;
  summary: string;
  createdAt: string;
}

export interface CustomerRequestDetail {
  request?: CustomerRequestSummary | undefined;
  description: string;
  feedback: CustomerRequestFeedbackEvidence[];
  issueLinks: CustomerRequestIssueLink[];
  auditEntries: CustomerRequestAuditEntry[];
  customers: CustomerRequestCustomerLink[];
  votes: CustomerRequestVote[];
  duplicates: CustomerRequestDuplicate[];
}

export interface ListCustomerRequestsRequest {
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  limit?: number | undefined;
  cursor?: string | undefined;
  feedbackId?: string | undefined;
}

export interface ListCustomerRequestsResponse {
  requests: CustomerRequestSummary[];
  nextCursor?: string | undefined;
}

export interface GetCustomerRequestRequest {
  id: string;
  evidenceLimit?: number | undefined;
}

export interface CreateCustomerRequestRequest {
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface UpdateCustomerRequestRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  status?: CustomerRequestStatus | undefined;
  priority?: CustomerRequestPriority | undefined;
  ownerMemberId?: string | undefined;
}

export interface PromoteFeedbackToCustomerRequestRequest {
  feedbackIds: string[];
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface LinkFeedbackToCustomerRequestRequest {
  id: string;
  feedbackId: string;
  importance: CustomerRequestImportance;
  note?: string | undefined;
}

export interface UnlinkFeedbackFromCustomerRequestRequest {
  id: string;
  feedbackId: string;
}

export interface LinkCustomerToCustomerRequestRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  note?: string | undefined;
}

export interface UnlinkCustomerFromCustomerRequestRequest {
  id: string;
  customerLinkId: string;
}

export interface AddCustomerRequestVoteRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  weight: number;
  note?: string | undefined;
}

export interface RemoveCustomerRequestVoteRequest {
  id: string;
  voteId: string;
}

export interface MergeCustomerRequestsRequest {
  sourceId: string;
  targetId: string;
  idempotencyKey: string;
}

export interface LinkCustomerRequestIssueRequest {
  id: string;
  provider: string;
  externalUrl: string;
  externalKey?: string | undefined;
  title?: string | undefined;
  status?: string | undefined;
}

export interface UnlinkCustomerRequestIssueRequest {
  id: string;
  issueLinkId: string;
}

export interface CustomerRequestService {
  ListCustomerRequests(request: ListCustomerRequestsRequest): Promise<ListCustomerRequestsResponse>;
  GetCustomerRequest(request: GetCustomerRequestRequest): Promise<CustomerRequestDetail>;
  CreateCustomerRequest(request: CreateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UpdateCustomerRequest(request: UpdateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  PromoteFeedbackToCustomerRequest(request: PromoteFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkFeedbackToCustomerRequest(request: LinkFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkFeedbackFromCustomerRequest(request: UnlinkFeedbackFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkCustomerToCustomerRequest(request: LinkCustomerToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkCustomerFromCustomerRequest(request: UnlinkCustomerFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  AddCustomerRequestVote(request: AddCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  RemoveCustomerRequestVote(request: RemoveCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  MergeCustomerRequests(request: MergeCustomerRequestsRequest): Promise<CustomerRequestDetail>;
  LinkCustomerRequestIssue(request: LinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
  UnlinkCustomerRequestIssue(request: UnlinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
}
