// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/customer_request.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum CustomerRequestStatus {
  CUSTOMER_REQUEST_STATUS_UNSPECIFIED = "CUSTOMER_REQUEST_STATUS_UNSPECIFIED",
  CUSTOMER_REQUEST_STATUS_OPEN = "CUSTOMER_REQUEST_STATUS_OPEN",
  CUSTOMER_REQUEST_STATUS_PLANNED = "CUSTOMER_REQUEST_STATUS_PLANNED",
  CUSTOMER_REQUEST_STATUS_IN_PROGRESS = "CUSTOMER_REQUEST_STATUS_IN_PROGRESS",
  CUSTOMER_REQUEST_STATUS_SHIPPED = "CUSTOMER_REQUEST_STATUS_SHIPPED",
  CUSTOMER_REQUEST_STATUS_CANCELLED = "CUSTOMER_REQUEST_STATUS_CANCELLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestPriority {
  CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED = "CUSTOMER_REQUEST_PRIORITY_UNSPECIFIED",
  CUSTOMER_REQUEST_PRIORITY_NONE = "CUSTOMER_REQUEST_PRIORITY_NONE",
  CUSTOMER_REQUEST_PRIORITY_LOW = "CUSTOMER_REQUEST_PRIORITY_LOW",
  CUSTOMER_REQUEST_PRIORITY_MEDIUM = "CUSTOMER_REQUEST_PRIORITY_MEDIUM",
  CUSTOMER_REQUEST_PRIORITY_HIGH = "CUSTOMER_REQUEST_PRIORITY_HIGH",
  CUSTOMER_REQUEST_PRIORITY_URGENT = "CUSTOMER_REQUEST_PRIORITY_URGENT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestImportance {
  CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED = "CUSTOMER_REQUEST_IMPORTANCE_UNSPECIFIED",
  CUSTOMER_REQUEST_IMPORTANCE_NORMAL = "CUSTOMER_REQUEST_IMPORTANCE_NORMAL",
  CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT = "CUSTOMER_REQUEST_IMPORTANCE_IMPORTANT",
  CUSTOMER_REQUEST_IMPORTANCE_CRITICAL = "CUSTOMER_REQUEST_IMPORTANCE_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestVisibility {
  CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED = "CUSTOMER_REQUEST_VISIBILITY_UNSPECIFIED",
  CUSTOMER_REQUEST_VISIBILITY_ACTIVE = "CUSTOMER_REQUEST_VISIBILITY_ACTIVE",
  CUSTOMER_REQUEST_VISIBILITY_MERGED = "CUSTOMER_REQUEST_VISIBILITY_MERGED",
  CUSTOMER_REQUEST_VISIBILITY_ARCHIVED = "CUSTOMER_REQUEST_VISIBILITY_ARCHIVED",
  CUSTOMER_REQUEST_VISIBILITY_ALL = "CUSTOMER_REQUEST_VISIBILITY_ALL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestSort {
  CUSTOMER_REQUEST_SORT_UNSPECIFIED = "CUSTOMER_REQUEST_SORT_UNSPECIFIED",
  CUSTOMER_REQUEST_SORT_UPDATED_AT = "CUSTOMER_REQUEST_SORT_UPDATED_AT",
  CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT = "CUSTOMER_REQUEST_SORT_CUSTOMER_COUNT",
  CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT = "CUSTOMER_REQUEST_SORT_SUPPORTING_FEEDBACK_COUNT",
  CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT = "CUSTOMER_REQUEST_SORT_LATEST_FEEDBACK_AT",
  CUSTOMER_REQUEST_SORT_PRIORITY = "CUSTOMER_REQUEST_SORT_PRIORITY",
  CUSTOMER_REQUEST_SORT_REVENUE_IMPACT = "CUSTOMER_REQUEST_SORT_REVENUE_IMPACT",
  CUSTOMER_REQUEST_SORT_DECISION_SCORE = "CUSTOMER_REQUEST_SORT_DECISION_SCORE",
  CUSTOMER_REQUEST_SORT_DELIVERY_HEALTH = "CUSTOMER_REQUEST_SORT_DELIVERY_HEALTH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestIssueSyncState {
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_UNSPECIFIED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_UNSPECIFIED",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_MANUAL = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_MANUAL",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_PENDING = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_PENDING",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_SYNCED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_SYNCED",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_STALE = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_STALE",
  CUSTOMER_REQUEST_ISSUE_SYNC_STATE_FAILED = "CUSTOMER_REQUEST_ISSUE_SYNC_STATE_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum CustomerRequestDeliveryHealth {
  CUSTOMER_REQUEST_DELIVERY_HEALTH_UNSPECIFIED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_UNSPECIFIED",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_NO_LINKS = "CUSTOMER_REQUEST_DELIVERY_HEALTH_NO_LINKS",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_MANUAL = "CUSTOMER_REQUEST_DELIVERY_HEALTH_MANUAL",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_PENDING = "CUSTOMER_REQUEST_DELIVERY_HEALTH_PENDING",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_SYNCED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_SYNCED",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_STALE = "CUSTOMER_REQUEST_DELIVERY_HEALTH_STALE",
  CUSTOMER_REQUEST_DELIVERY_HEALTH_FAILED = "CUSTOMER_REQUEST_DELIVERY_HEALTH_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = "SORT_DIRECTION_UNSPECIFIED",
  SORT_DIRECTION_ASC = "SORT_DIRECTION_ASC",
  SORT_DIRECTION_DESC = "SORT_DIRECTION_DESC",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface CustomerRequestOwner {
  id: string;
  memberType: string;
  userId: string;
  email: string;
  role: string;
}

export interface CustomerRequestSummary {
  id: string;
  displayId: string;
  displayNumber: string;
  title: string;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  owner?: CustomerRequestOwner | undefined;
  supportingFeedbackCount: number;
  customerCount: number;
  linkedIssueCount: number;
  hiddenFeedbackCount: number;
  firstFeedbackAt: string;
  latestFeedbackAt: string;
  mergedIntoRequestId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string | undefined;
  accountCount: number;
  voteCount: number;
  duplicateRequestCount: number;
  revenueImpactCents: string;
  revenueCurrency: string;
  decisionScore: number;
  decisionScoreExplanation: string;
  deliveryHealth: CustomerRequestDeliveryHealth;
  syncedIssueCount: number;
  staleIssueCount: number;
  failedIssueCount: number;
  pendingIssueCount: number;
  manualIssueCount: number;
}

export interface CustomerRequestFeedbackEvidence {
  feedbackId: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  subjectDisplay: string;
  enrichedTitle: string;
  importance: CustomerRequestImportance;
  note: string;
  linkedBy: string;
  linkedAt: string;
  createdAt: string;
}

export interface CustomerRequestIssueLink {
  id: string;
  provider: string;
  externalKey: string;
  externalUrl: string;
  title: string;
  status: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  lastSyncedAt: string;
  syncState: CustomerRequestIssueSyncState;
  externalStatusCategory: string;
  externalAssignee: string;
  externalUpdatedAt: string;
  syncError: string;
}

export interface CustomerRequestCustomerLink {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  note: string;
  createdBy: string;
  createdAt: string;
  accountProfile?: CustomerRequestAccountProfile | undefined;
}

export interface CustomerRequestVote {
  id: string;
  subjectKey: string;
  subjectHash: string;
  subjectDisplay: string;
  accountKey: string;
  accountDisplay: string;
  weight: number;
  note: string;
  createdBy: string;
  createdAt: string;
  accountProfile?: CustomerRequestAccountProfile | undefined;
}

export interface CustomerRequestAccountProfile {
  accountKey: string;
  accountDisplay: string;
  revenueCents: string;
  revenueCurrency: string;
  tier: string;
  sizeSegment: string;
  lifecycleStatus: string;
  crmProvider: string;
  crmExternalId: string;
  source: string;
  updatedAt: string;
}

export interface CustomerRequestDuplicate {
  id: string;
  displayId: string;
  title: string;
  mergedAt: string;
}

export interface CustomerRequestNote {
  id: string;
  body: string;
  createdBy: string;
  createdAt: string;
}

export interface CustomerRequestAuditEntry {
  id: string;
  action: string;
  actorType: string;
  actorId: string;
  summary: string;
  createdAt: string;
}

export interface CustomerRequestDetail {
  request?: CustomerRequestSummary | undefined;
  description: string;
  feedback: CustomerRequestFeedbackEvidence[];
  issueLinks: CustomerRequestIssueLink[];
  auditEntries: CustomerRequestAuditEntry[];
  customers: CustomerRequestCustomerLink[];
  votes: CustomerRequestVote[];
  duplicates: CustomerRequestDuplicate[];
  accountProfiles: CustomerRequestAccountProfile[];
  notes: CustomerRequestNote[];
}

export interface CustomerRequestScoringSettings {
  tenantId: string;
  priorityNoneWeight: number;
  priorityLowWeight: number;
  priorityMediumWeight: number;
  priorityHighWeight: number;
  priorityUrgentWeight: number;
  feedbackWeight: number;
  feedbackCap: number;
  customerWeight: number;
  customerCap: number;
  accountWeight: number;
  accountCap: number;
  voteWeight: number;
  voteCap: number;
  revenueCentsPerPoint: string;
  revenueCap: number;
  updatedBy: string;
  updatedAt: string;
}

export interface GetCustomerRequestScoringSettingsRequest {
}

export interface UpdateCustomerRequestScoringSettingsRequest {
  priorityNoneWeight?: number | undefined;
  priorityLowWeight?: number | undefined;
  priorityMediumWeight?: number | undefined;
  priorityHighWeight?: number | undefined;
  priorityUrgentWeight?: number | undefined;
  feedbackWeight?: number | undefined;
  feedbackCap?: number | undefined;
  customerWeight?: number | undefined;
  customerCap?: number | undefined;
  accountWeight?: number | undefined;
  accountCap?: number | undefined;
  voteWeight?: number | undefined;
  voteCap?: number | undefined;
  revenueCentsPerPoint?: string | undefined;
  revenueCap?: number | undefined;
}

export interface CustomerRequestSavedViewState {
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  feedbackId?: string | undefined;
}

export interface CustomerRequestSavedView {
  id: string;
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface ListCustomerRequestSavedViewsRequest {
}

export interface ListCustomerRequestSavedViewsResponse {
  views: CustomerRequestSavedView[];
}

export interface CreateCustomerRequestSavedViewRequest {
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
}

export interface UpdateCustomerRequestSavedViewRequest {
  id: string;
  name: string;
  state?: CustomerRequestSavedViewState | undefined;
}

export interface CustomerRequestSavedViewResponse {
  view?: CustomerRequestSavedView | undefined;
}

export interface DeleteCustomerRequestSavedViewRequest {
  id: string;
}

export interface DeleteCustomerRequestSavedViewResponse {
}

export interface ListCustomerRequestsRequest {
  q: string;
  status: CustomerRequestStatus[];
  priority: CustomerRequestPriority[];
  ownerMemberId?: string | undefined;
  visibility: CustomerRequestVisibility;
  sort: CustomerRequestSort;
  direction: SortDirection;
  limit?: number | undefined;
  cursor?: string | undefined;
  feedbackId?: string | undefined;
  cohortId?: string | undefined;
}

export interface ListCustomerRequestsResponse {
  requests: CustomerRequestSummary[];
  nextCursor?: string | undefined;
}

export interface GetCustomerRequestRequest {
  id: string;
  evidenceLimit?: number | undefined;
}

export interface CreateCustomerRequestRequest {
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface UpdateCustomerRequestRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  status?: CustomerRequestStatus | undefined;
  priority?: CustomerRequestPriority | undefined;
  ownerMemberId?: string | undefined;
}

export interface PromoteFeedbackToCustomerRequestRequest {
  feedbackIds: string[];
  title: string;
  description?: string | undefined;
  status: CustomerRequestStatus;
  priority: CustomerRequestPriority;
  ownerMemberId?: string | undefined;
  idempotencyKey: string;
}

export interface LinkFeedbackToCustomerRequestRequest {
  id: string;
  feedbackId: string;
  importance: CustomerRequestImportance;
  note?: string | undefined;
}

export interface UnlinkFeedbackFromCustomerRequestRequest {
  id: string;
  feedbackId: string;
}

export interface LinkCustomerToCustomerRequestRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  note?: string | undefined;
  accountRevenueCents?: string | undefined;
  accountRevenueCurrency?: string | undefined;
  accountTier?: string | undefined;
  accountSizeSegment?: string | undefined;
  accountLifecycleStatus?: string | undefined;
  accountCrmProvider?: string | undefined;
  accountCrmExternalId?: string | undefined;
}

export interface UnlinkCustomerFromCustomerRequestRequest {
  id: string;
  customerLinkId: string;
}

export interface AddCustomerRequestVoteRequest {
  id: string;
  subjectKey?: string | undefined;
  subjectHash?: string | undefined;
  subjectDisplay?: string | undefined;
  accountKey?: string | undefined;
  accountDisplay?: string | undefined;
  weight: number;
  note?: string | undefined;
  accountRevenueCents?: string | undefined;
  accountRevenueCurrency?: string | undefined;
  accountTier?: string | undefined;
  accountSizeSegment?: string | undefined;
  accountLifecycleStatus?: string | undefined;
  accountCrmProvider?: string | undefined;
  accountCrmExternalId?: string | undefined;
}

export interface RemoveCustomerRequestVoteRequest {
  id: string;
  voteId: string;
}

export interface AddCustomerRequestNoteRequest {
  id: string;
  body: string;
}

export interface DeleteCustomerRequestNoteRequest {
  id: string;
  noteId: string;
}

export interface MergeCustomerRequestsRequest {
  sourceId: string;
  targetId: string;
  idempotencyKey: string;
}

export interface LinkCustomerRequestIssueRequest {
  id: string;
  provider: string;
  externalUrl: string;
  externalKey?: string | undefined;
  title?: string | undefined;
  status?: string | undefined;
}

export interface UnlinkCustomerRequestIssueRequest {
  id: string;
  issueLinkId: string;
}

export interface RecordCustomerRequestIssueSyncRequest {
  id: string;
  issueLinkId: string;
  syncState: CustomerRequestIssueSyncState;
  status?: string | undefined;
  externalStatusCategory?: string | undefined;
  externalAssignee?: string | undefined;
  externalUpdatedAt?: string | undefined;
  syncError?: string | undefined;
}

export interface CustomerRequestService {
  ListCustomerRequests(request: ListCustomerRequestsRequest): Promise<ListCustomerRequestsResponse>;
  GetCustomerRequestScoringSettings(
    request: GetCustomerRequestScoringSettingsRequest,
  ): Promise<CustomerRequestScoringSettings>;
  UpdateCustomerRequestScoringSettings(
    request: UpdateCustomerRequestScoringSettingsRequest,
  ): Promise<CustomerRequestScoringSettings>;
  ListCustomerRequestSavedViews(
    request: ListCustomerRequestSavedViewsRequest,
  ): Promise<ListCustomerRequestSavedViewsResponse>;
  CreateCustomerRequestSavedView(
    request: CreateCustomerRequestSavedViewRequest,
  ): Promise<CustomerRequestSavedViewResponse>;
  UpdateCustomerRequestSavedView(
    request: UpdateCustomerRequestSavedViewRequest,
  ): Promise<CustomerRequestSavedViewResponse>;
  DeleteCustomerRequestSavedView(
    request: DeleteCustomerRequestSavedViewRequest,
  ): Promise<DeleteCustomerRequestSavedViewResponse>;
  GetCustomerRequest(request: GetCustomerRequestRequest): Promise<CustomerRequestDetail>;
  CreateCustomerRequest(request: CreateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UpdateCustomerRequest(request: UpdateCustomerRequestRequest): Promise<CustomerRequestDetail>;
  PromoteFeedbackToCustomerRequest(request: PromoteFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkFeedbackToCustomerRequest(request: LinkFeedbackToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkFeedbackFromCustomerRequest(request: UnlinkFeedbackFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  LinkCustomerToCustomerRequest(request: LinkCustomerToCustomerRequestRequest): Promise<CustomerRequestDetail>;
  UnlinkCustomerFromCustomerRequest(request: UnlinkCustomerFromCustomerRequestRequest): Promise<CustomerRequestDetail>;
  AddCustomerRequestVote(request: AddCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  RemoveCustomerRequestVote(request: RemoveCustomerRequestVoteRequest): Promise<CustomerRequestDetail>;
  AddCustomerRequestNote(request: AddCustomerRequestNoteRequest): Promise<CustomerRequestDetail>;
  DeleteCustomerRequestNote(request: DeleteCustomerRequestNoteRequest): Promise<CustomerRequestDetail>;
  MergeCustomerRequests(request: MergeCustomerRequestsRequest): Promise<CustomerRequestDetail>;
  LinkCustomerRequestIssue(request: LinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
  UnlinkCustomerRequestIssue(request: UnlinkCustomerRequestIssueRequest): Promise<CustomerRequestDetail>;
  RecordCustomerRequestIssueSync(request: RecordCustomerRequestIssueSyncRequest): Promise<CustomerRequestDetail>;
}
