// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/enrich_config.proto

/* eslint-disable */
import { type Dimension, type I18nString } from "./common";

export const protobufPackage = "attune.v1";

export interface EnrichConfig {
  /** Tenant override; unset = use default_prompt_template. */
  promptTemplate?:
    | string
    | undefined;
  /**
   * Built-in default prompt body, always returned so the console can
   * offer a "restore default" affordance.
   */
  defaultPromptTemplate: string;
  /**
   * Per-tenant Dimension set. Migration 014 seeds 3 dims (type +
   * severity + labels) on every fresh tenant; operators may add /
   * remove / edit any dim from here.
   */
  dimensions: Dimension[];
  /** Resolved prompt policy metadata for the active tenant config. */
  promptPolicy?:
    | EnrichPromptPolicy
    | undefined;
  /** Recent immutable prompt-policy snapshots, newest first. */
  promptVersions: EnrichPromptVersion[];
  /** Operator-authored prompt behavior knobs layered onto the built-in policy. */
  policyConfig?: EnrichPromptPolicyConfig | undefined;
}

export interface GetEnrichConfigRequest {
}

export interface GetEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface UpdateEnrichConfigRequest {
  /** Omit / null to restore the built-in default prompt. */
  promptTemplate?:
    | string
    | undefined;
  /** Empty list clears all dims (LLM still emits title + rationale). */
  dimensions: Dimension[];
  policyConfig?: EnrichPromptPolicyConfig | undefined;
}

export interface UpdateEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface PreviewEnrichPromptRequest {
  sampleContent: string;
  /** Optional unsaved prompt draft; omitted means preview the persisted config. */
  promptTemplate?:
    | string
    | undefined;
  /** Optional unsaved Dimension draft; omitted means preview persisted Dimensions. */
  dimensions: Dimension[];
  /**
   * When true, prompt_template/dimensions are treated as the draft config,
   * including an intentionally empty dimensions list.
   */
  useDraftConfig: boolean;
  policyConfig?: EnrichPromptPolicyConfig | undefined;
}

export interface PreviewEnrichPromptResponse {
  renderedPrompt: string;
  promptPolicy?: EnrichPromptPolicy | undefined;
}

/** GetEvalSuggestions returns off-list values the LLM suggested during eval. */
export interface GetEvalSuggestionsRequest {
}

export interface GetEvalSuggestionsResponse {
  /** Coverage per dimension: 1.0 = all on-list, 0.85 = 15% dropped. */
  coverage: { [key: string]: number };
  /** Top suggested candidates sorted by confidence descending. */
  candidates: SuggestedCandidate[];
  /** Actionable recommendations for high-confidence candidates. */
  recommendations: SuggestedRecommendation[];
}

export interface GetEvalSuggestionsResponse_CoverageEntry {
  key: string;
  value: number;
}

/** SuggestedCandidate is one off-list value with analysis metadata. */
export interface SuggestedCandidate {
  dim: string;
  value: string;
  count: number;
  confidence: number;
  coverageImpact: number;
}

/** SuggestedRecommendation is an actionable suggestion for the operator. */
export interface SuggestedRecommendation {
  action: string;
  dim: string;
  value: string;
  reason: string;
  impact: string;
}

/** PromoteSuggestedValue adds a value to the dimension taxonomy. */
export interface PromoteSuggestedValueRequest {
  dimensionName: string;
  value: string;
  displayName?: I18nString | undefined;
}

export interface PromoteSuggestedValueResponse {
  /** The updated dimension with the new taxonomy value. */
  dimension?: Dimension | undefined;
}

export interface EnrichPromptPolicy {
  policyId: string;
  policyVersion: string;
  promptVersion: string;
  mode: string;
  promptSource: string;
  templateLanguage: string;
  displayLocale: string;
  displayLanguageName: string;
  variables: EnrichPromptVariable[];
  outputs: EnrichPromptOutput[];
  warnings: EnrichPromptWarning[];
  policyConfig?: EnrichPromptPolicyConfig | undefined;
  promptFingerprint: string;
  schemaFingerprint: string;
}

export interface EnrichPromptPolicyConfig {
  /**
   * source_and_display keeps source-language title/rationale plus display fields.
   * display_only writes all summary fields in the tenant display language.
   */
  outputLanguagePolicy: string;
  titleMaxChars: number;
  rationaleMaxChars: number;
  displayFieldsRequired?:
    | boolean
    | undefined;
  /** concise or neutral. */
  tone: string;
  domainGuidance: string;
}

export interface EnrichPromptVariable {
  name: string;
  required: boolean;
  meaning: string;
}

export interface EnrichPromptOutput {
  name: string;
  required: boolean;
  language: string;
}

export interface EnrichPromptWarning {
  code: string;
  severity: string;
  message: string;
}

export interface EnrichPromptVersion {
  id: string;
  promptVersion: string;
  policyId: string;
  policyVersion: string;
  mode: string;
  promptSource: string;
  createdAt: string;
  isActive: boolean;
  hasTemplate: boolean;
  dimensionsCount: number;
  warnings: string[];
  /**
   * Snapshot values restored by activation. Admin-only Console API already
   * exposes the active prompt and dimensions; history includes them so an
   * operator can inspect a rollback target before activating it.
   */
  promptTemplate?: string | undefined;
  dimensions: Dimension[];
  policyConfig?: EnrichPromptPolicyConfig | undefined;
  promptFingerprint: string;
  schemaFingerprint: string;
}

export interface ActivateEnrichPromptVersionRequest {
  versionId: string;
}

export interface ActivateEnrichPromptVersionResponse {
  config?: EnrichConfig | undefined;
}

export interface ListEnrichPromptVersionsRequest {
  /** Cursor from the previous response. It is the last seen version id. */
  cursor?: string | undefined;
  limit?:
    | number
    | undefined;
  /**
   * Case-insensitive search across version identity, fingerprints, warnings,
   * dimensions, and custom prompt body.
   */
  q?: string | undefined;
}

export interface ListEnrichPromptVersionsResponse {
  versions: EnrichPromptVersion[];
  nextCursor?: string | undefined;
}

/**
 * EnrichConfigService manages per-tenant enricher prompt + the
 * metadata-driven Dimension set (#10 → E3 proposal
 * docs/proposals/2026/06/2026-06-07-flat-labels.md).
 */
export interface EnrichConfigService {
  /** GET /fb/v1/console/enrich-config */
  GetEnrichConfig(request: GetEnrichConfigRequest): Promise<GetEnrichConfigResponse>;
  /** PUT /fb/v1/console/enrich-config */
  UpdateEnrichConfig(request: UpdateEnrichConfigRequest): Promise<UpdateEnrichConfigResponse>;
  /** POST /fb/v1/console/enrich-config/preview */
  PreviewEnrichPrompt(request: PreviewEnrichPromptRequest): Promise<PreviewEnrichPromptResponse>;
  /**
   * POST /fb/v1/console/enrich-config/eval-suggestions:analyze
   * Runs an LLM-backed eval sample and returns off-list suggested values.
   */
  GetEvalSuggestions(request: GetEvalSuggestionsRequest): Promise<GetEvalSuggestionsResponse>;
  /**
   * POST /fb/v1/console/enrich-config/promote
   * Promotes a suggested value to the dimension taxonomy.
   */
  PromoteSuggestedValue(request: PromoteSuggestedValueRequest): Promise<PromoteSuggestedValueResponse>;
  /**
   * POST /fb/v1/console/enrich-config/versions/{version_id}:activate
   * Restores a previous immutable prompt-policy snapshot.
   */
  ActivateEnrichPromptVersion(
    request: ActivateEnrichPromptVersionRequest,
  ): Promise<ActivateEnrichPromptVersionResponse>;
  /**
   * GET /fb/v1/console/enrich-config/versions
   * Lists immutable prompt-policy snapshots newest first.
   */
  ListEnrichPromptVersions(request: ListEnrichPromptVersionsRequest): Promise<ListEnrichPromptVersionsResponse>;
}
