// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/enrich_config.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum ModuleMode {
  MODULE_MODE_UNSPECIFIED = 0,
  MODULE_MODE_FREEFORM = 1,
  MODULE_MODE_CONSTRAINED = 2,
  UNRECOGNIZED = -1,
}

export interface EnrichConfig {
  /** Tenant override; unset means "use default_prompt_template". */
  promptTemplate?:
    | string
    | undefined;
  /** Built-in default — always returned so the console can restore it. */
  defaultPromptTemplate: string;
  modules: string[];
  moduleMode: ModuleMode;
}

export interface GetEnrichConfigRequest {
}

export interface GetEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface UpdateEnrichConfigRequest {
  /** Omit or null to restore the built-in default prompt. */
  promptTemplate?:
    | string
    | undefined;
  /** Empty clears the whitelist (free-form mode). */
  modules: string[];
}

export interface UpdateEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface PreviewEnrichPromptRequest {
  sampleContent: string;
}

export interface PreviewEnrichPromptResponse {
  renderedPrompt: string;
}

/** EnrichConfigService manages per-tenant enricher prompt + module whitelist (#10). */
export interface EnrichConfigService {
  /** GET /fb/v1/console/enrich-config */
  GetEnrichConfig(request: GetEnrichConfigRequest): Promise<GetEnrichConfigResponse>;
  /** PUT /fb/v1/console/enrich-config */
  UpdateEnrichConfig(request: UpdateEnrichConfigRequest): Promise<UpdateEnrichConfigResponse>;
  /** POST /fb/v1/console/enrich-config/preview */
  PreviewEnrichPrompt(request: PreviewEnrichPromptRequest): Promise<PreviewEnrichPromptResponse>;
}
