// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/enrich_config.proto

/* eslint-disable */
import { type Dimension, type I18nString } from "./common";

export const protobufPackage = "attune.v1";

export interface EnrichConfig {
  /** Tenant override; unset = use default_prompt_template. */
  promptTemplate?:
    | string
    | undefined;
  /**
   * Built-in default prompt body, always returned so the console can
   * offer a "restore default" affordance.
   */
  defaultPromptTemplate: string;
  /**
   * Per-tenant Dimension set. Migration 014 seeds 3 dims (type +
   * severity + labels) on every fresh tenant; operators may add /
   * remove / edit any dim from here.
   */
  dimensions: Dimension[];
}

export interface GetEnrichConfigRequest {
}

export interface GetEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface UpdateEnrichConfigRequest {
  /** Omit / null to restore the built-in default prompt. */
  promptTemplate?:
    | string
    | undefined;
  /** Empty list clears all dims (LLM still emits title + rationale). */
  dimensions: Dimension[];
}

export interface UpdateEnrichConfigResponse {
  config?: EnrichConfig | undefined;
}

export interface PreviewEnrichPromptRequest {
  sampleContent: string;
}

export interface PreviewEnrichPromptResponse {
  renderedPrompt: string;
}

/** GetEvalSuggestions returns off-list values the LLM suggested during eval. */
export interface GetEvalSuggestionsRequest {
}

export interface GetEvalSuggestionsResponse {
  /** Coverage per dimension: 1.0 = all on-list, 0.85 = 15% dropped. */
  coverage: { [key: string]: number };
  /** Top suggested candidates sorted by confidence descending. */
  candidates: SuggestedCandidate[];
  /** Actionable recommendations for high-confidence candidates. */
  recommendations: SuggestedRecommendation[];
}

export interface GetEvalSuggestionsResponse_CoverageEntry {
  key: string;
  value: number;
}

/** SuggestedCandidate is one off-list value with analysis metadata. */
export interface SuggestedCandidate {
  dim: string;
  value: string;
  count: number;
  confidence: number;
  coverageImpact: number;
}

/** SuggestedRecommendation is an actionable suggestion for the operator. */
export interface SuggestedRecommendation {
  action: string;
  dim: string;
  value: string;
  reason: string;
  impact: string;
}

/** PromoteSuggestedValue adds a value to the dimension taxonomy. */
export interface PromoteSuggestedValueRequest {
  dimensionName: string;
  value: string;
  displayName?: I18nString | undefined;
}

export interface PromoteSuggestedValueResponse {
  /** The updated dimension with the new taxonomy value. */
  dimension?: Dimension | undefined;
}

/**
 * EnrichConfigService manages per-tenant enricher prompt + the
 * metadata-driven Dimension set (#10 → E3 proposal
 * docs/proposals/2026/06/2026-06-07-flat-labels.md).
 */
export interface EnrichConfigService {
  /** GET /fb/v1/console/enrich-config */
  GetEnrichConfig(request: GetEnrichConfigRequest): Promise<GetEnrichConfigResponse>;
  /** PUT /fb/v1/console/enrich-config */
  UpdateEnrichConfig(request: UpdateEnrichConfigRequest): Promise<UpdateEnrichConfigResponse>;
  /** POST /fb/v1/console/enrich-config/preview */
  PreviewEnrichPrompt(request: PreviewEnrichPromptRequest): Promise<PreviewEnrichPromptResponse>;
  /**
   * GET /fb/v1/console/enrich-config/eval-suggestions
   * Returns off-list values the LLM suggested during the most recent eval run.
   */
  GetEvalSuggestions(request: GetEvalSuggestionsRequest): Promise<GetEvalSuggestionsResponse>;
  /**
   * POST /fb/v1/console/enrich-config/promote
   * Promotes a suggested value to the dimension taxonomy.
   */
  PromoteSuggestedValue(request: PromoteSuggestedValueRequest): Promise<PromoteSuggestedValueResponse>;
}
