// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/external_sync.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum ExternalSyncDirection {
  EXTERNAL_SYNC_DIRECTION_UNSPECIFIED = "EXTERNAL_SYNC_DIRECTION_UNSPECIFIED",
  EXTERNAL_SYNC_DIRECTION_PULL = "EXTERNAL_SYNC_DIRECTION_PULL",
  EXTERNAL_SYNC_DIRECTION_PUSH = "EXTERNAL_SYNC_DIRECTION_PUSH",
  EXTERNAL_SYNC_DIRECTION_BIDIRECTIONAL = "EXTERNAL_SYNC_DIRECTION_BIDIRECTIONAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncRunTrigger {
  EXTERNAL_SYNC_RUN_TRIGGER_UNSPECIFIED = "EXTERNAL_SYNC_RUN_TRIGGER_UNSPECIFIED",
  EXTERNAL_SYNC_RUN_TRIGGER_MANUAL = "EXTERNAL_SYNC_RUN_TRIGGER_MANUAL",
  EXTERNAL_SYNC_RUN_TRIGGER_SCHEDULE = "EXTERNAL_SYNC_RUN_TRIGGER_SCHEDULE",
  EXTERNAL_SYNC_RUN_TRIGGER_RETRY = "EXTERNAL_SYNC_RUN_TRIGGER_RETRY",
  EXTERNAL_SYNC_RUN_TRIGGER_SYSTEM = "EXTERNAL_SYNC_RUN_TRIGGER_SYSTEM",
  EXTERNAL_SYNC_RUN_TRIGGER_WEBHOOK = "EXTERNAL_SYNC_RUN_TRIGGER_WEBHOOK",
  EXTERNAL_SYNC_RUN_TRIGGER_BACKFILL = "EXTERNAL_SYNC_RUN_TRIGGER_BACKFILL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncRunStatus {
  EXTERNAL_SYNC_RUN_STATUS_UNSPECIFIED = "EXTERNAL_SYNC_RUN_STATUS_UNSPECIFIED",
  EXTERNAL_SYNC_RUN_STATUS_QUEUED = "EXTERNAL_SYNC_RUN_STATUS_QUEUED",
  EXTERNAL_SYNC_RUN_STATUS_RUNNING = "EXTERNAL_SYNC_RUN_STATUS_RUNNING",
  EXTERNAL_SYNC_RUN_STATUS_SUCCEEDED = "EXTERNAL_SYNC_RUN_STATUS_SUCCEEDED",
  EXTERNAL_SYNC_RUN_STATUS_PARTIAL = "EXTERNAL_SYNC_RUN_STATUS_PARTIAL",
  EXTERNAL_SYNC_RUN_STATUS_FAILED = "EXTERNAL_SYNC_RUN_STATUS_FAILED",
  EXTERNAL_SYNC_RUN_STATUS_CANCELLED = "EXTERNAL_SYNC_RUN_STATUS_CANCELLED",
  EXTERNAL_SYNC_RUN_STATUS_DEAD = "EXTERNAL_SYNC_RUN_STATUS_DEAD",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncEventSignatureStatus {
  EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_UNSPECIFIED = "EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_UNSPECIFIED",
  EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_VERIFIED = "EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_VERIFIED",
  EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_FAILED = "EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_FAILED",
  EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_NOT_REQUIRED = "EXTERNAL_SYNC_EVENT_SIGNATURE_STATUS_NOT_REQUIRED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncEventStatus {
  EXTERNAL_SYNC_EVENT_STATUS_UNSPECIFIED = "EXTERNAL_SYNC_EVENT_STATUS_UNSPECIFIED",
  EXTERNAL_SYNC_EVENT_STATUS_RECEIVED = "EXTERNAL_SYNC_EVENT_STATUS_RECEIVED",
  EXTERNAL_SYNC_EVENT_STATUS_REPLAYED = "EXTERNAL_SYNC_EVENT_STATUS_REPLAYED",
  EXTERNAL_SYNC_EVENT_STATUS_IGNORED = "EXTERNAL_SYNC_EVENT_STATUS_IGNORED",
  EXTERNAL_SYNC_EVENT_STATUS_FAILED = "EXTERNAL_SYNC_EVENT_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncConflictResolution {
  EXTERNAL_SYNC_CONFLICT_RESOLUTION_UNSPECIFIED = "EXTERNAL_SYNC_CONFLICT_RESOLUTION_UNSPECIFIED",
  EXTERNAL_SYNC_CONFLICT_RESOLUTION_LOCAL_WINS = "EXTERNAL_SYNC_CONFLICT_RESOLUTION_LOCAL_WINS",
  EXTERNAL_SYNC_CONFLICT_RESOLUTION_EXTERNAL_WINS = "EXTERNAL_SYNC_CONFLICT_RESOLUTION_EXTERNAL_WINS",
  EXTERNAL_SYNC_CONFLICT_RESOLUTION_MANUAL_MERGE = "EXTERNAL_SYNC_CONFLICT_RESOLUTION_MANUAL_MERGE",
  EXTERNAL_SYNC_CONFLICT_RESOLUTION_IGNORED = "EXTERNAL_SYNC_CONFLICT_RESOLUTION_IGNORED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExternalSyncQualificationCheckStatus {
  EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_UNSPECIFIED = "EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_UNSPECIFIED",
  EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_OK = "EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_OK",
  EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_WARNING = "EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_WARNING",
  EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_FAILED = "EXTERNAL_SYNC_QUALIFICATION_CHECK_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ExternalConnection {
  id: string;
  tenantId: string;
  provider: string;
  name: string;
  enabled: boolean;
  status: string;
  authType: string;
  baseUrl: string;
  providerConfigJson: string;
  scopes: string[];
  lastTestedAt: string;
  lastTestStatus: string;
  lastError: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  webhookSecretConfigured: boolean;
}

export interface ExternalObjectMapping {
  id: string;
  tenantId: string;
  connectionId: string;
  localObjectType: string;
  externalObjectType: string;
  direction: ExternalSyncDirection;
  fieldMappingJson: string;
  statusMappingJson: string;
  conflictPolicy: string;
  tombstonePolicy: string;
  enabled: boolean;
  mappingVersion: number;
  createdAt: string;
  updatedAt: string;
}

export interface ExternalObjectSchema {
  type: string;
  fields: string[];
  requiredFields: string[];
  writableFields: string[];
}

export interface ExternalSyncRun {
  id: string;
  tenantId: string;
  connectionId: string;
  mappingId: string;
  direction: ExternalSyncDirection;
  trigger: ExternalSyncRunTrigger;
  status: ExternalSyncRunStatus;
  attempts: number;
  nextRetryAt: string;
  startedAt: string;
  finishedAt: string;
  cursorBeforeJson: string;
  cursorAfterJson: string;
  recordsSeen: number;
  recordsChanged: number;
  recordsFailed: number;
  conflictsCreated: number;
  errorKind: string;
  errorMessage: string;
  actorId: string;
  createdAt: string;
  updatedAt: string;
  inFlight: boolean;
}

export interface ExternalSyncAttempt {
  id: string;
  runId: string;
  attemptNumber: number;
  startedAt: string;
  finishedAt: string;
  result: string;
  httpStatus: number;
  providerRequestId: string;
  retryAfter: string;
  errorKind: string;
  errorMessage: string;
}

export interface ExternalSyncRecordFailure {
  id: string;
  tenantId: string;
  runId: string;
  mappingId: string;
  operation: string;
  localObjectId: string;
  externalKey: string;
  failureKind: string;
  message: string;
  payloadDigest: string;
  retryMode: string;
  normalizedPayloadJson: string;
  retryable: boolean;
  resolvedAt: string;
  resolvedBy: string;
  createdAt: string;
}

export interface ExternalSyncConflict {
  id: string;
  tenantId: string;
  mappingId: string;
  localObjectId: string;
  externalKey: string;
  conflictKind: string;
  status: string;
  localSnapshotJson: string;
  externalSnapshotJson: string;
  resolution: string;
  resolvedAt: string;
  resolvedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface ExternalSyncEvent {
  id: string;
  tenantId: string;
  connectionId: string;
  mappingId: string;
  provider: string;
  eventType: string;
  externalEventId: string;
  dedupeKey: string;
  signatureStatus: ExternalSyncEventSignatureStatus;
  status: ExternalSyncEventStatus;
  payloadDigest: string;
  normalizedPayloadJson: string;
  receivedAt: string;
  replayedAt: string;
  replayedBy: string;
  runId: string;
  failureReason: string;
  createdAt: string;
  updatedAt: string;
}

export interface ExternalSyncRunDetail {
  run?: ExternalSyncRun | undefined;
  attempts: ExternalSyncAttempt[];
  failures: ExternalSyncRecordFailure[];
  conflicts: ExternalSyncConflict[];
}

export interface ExternalSyncRecordTimelineEntry {
  kind: string;
  occurredAt: string;
  runId: string;
  status: string;
  operation: string;
  localObjectId: string;
  externalKey: string;
  summary: string;
  detailJson: string;
}

export interface ExternalSyncHealthResponse {
  enabledConnections: number;
  failingConnections: number;
  staleConnections: number;
  activeRuns: number;
  retryableRuns: number;
  deadRuns: number;
  openConflicts: number;
  newestSuccessfulRunAt: string;
  disabledConnections: number;
  throttledRuns: number;
  unauthorizedRuns: number;
  providerUnavailableRuns: number;
  delayedRetryRuns: number;
  newestRetryAfter: string;
  degradedConnections: number;
  quarantinedConnections: number;
}

export interface ExternalSyncQualificationCheck {
  name: string;
  status: ExternalSyncQualificationCheckStatus;
  summary: string;
  detailJson: string;
}

export interface ListExternalConnectionsRequest {
}

export interface ListExternalConnectionsResponse {
  connections: ExternalConnection[];
}

export interface CreateExternalConnectionRequest {
  provider: string;
  name: string;
  authType: string;
  credential: string;
  baseUrl: string;
  providerConfigJson: string;
  scopes: string[];
  enabled?: boolean | undefined;
  webhookSecret: string;
}

export interface UpdateExternalConnectionRequest {
  id: string;
  name?: string | undefined;
  enabled?: boolean | undefined;
  credential?: string | undefined;
  baseUrl?: string | undefined;
  providerConfigJson?: string | undefined;
  scopes: string[];
  webhookSecret?: string | undefined;
}

export interface DeleteExternalConnectionRequest {
  id: string;
}

export interface DeleteExternalConnectionResponse {
}

export interface TestExternalConnectionRequest {
  id: string;
}

export interface TestExternalConnectionResponse {
  ok: boolean;
  error: string;
  latencyMs: string;
}

export interface ResumeExternalConnectionRequest {
  id: string;
}

export interface QualifyExternalConnectionRequest {
  id: string;
}

export interface QualifyExternalConnectionResponse {
  connectionId: string;
  ready: boolean;
  checks: ExternalSyncQualificationCheck[];
}

export interface DiscoverExternalConnectionSchemaRequest {
  id: string;
}

export interface DiscoverExternalConnectionSchemaResponse {
  schemas: ExternalObjectSchema[];
}

export interface ListExternalObjectMappingsRequest {
  connectionId: string;
}

export interface ListExternalObjectMappingsResponse {
  mappings: ExternalObjectMapping[];
}

export interface UpdateExternalObjectMappingRequest {
  id: string;
  direction: ExternalSyncDirection;
  fieldMappingJson: string;
  statusMappingJson: string;
  conflictPolicy: string;
  tombstonePolicy: string;
  enabled?: boolean | undefined;
}

export interface PreviewExternalObjectMappingRequest {
  id: string;
  fieldMappingJson?: string | undefined;
  statusMappingJson?: string | undefined;
}

export interface PreviewExternalObjectMappingResponse {
  schema?: ExternalObjectSchema | undefined;
  errors: string[];
  warnings: string[];
}

export interface ResetExternalSyncCursorRequest {
  id: string;
}

export interface ResetExternalSyncCursorResponse {
  mapping?: ExternalObjectMapping | undefined;
  run?: ExternalSyncRun | undefined;
}

export interface RequestExternalSyncBackfillRequest {
  id: string;
  resetCursor: boolean;
}

export interface RequestExternalSyncBackfillResponse {
  mapping?: ExternalObjectMapping | undefined;
  run?: ExternalSyncRun | undefined;
}

export interface RequestExternalSyncRunRequest {
  connectionId: string;
  mappingId: string;
  direction: ExternalSyncDirection;
}

export interface ListExternalSyncRunsRequest {
  connectionId: string;
  mappingId: string;
  status: string;
  limit: number;
  beforeId: string;
}

export interface ListExternalSyncRunsResponse {
  runs: ExternalSyncRun[];
  nextBeforeId: string;
}

export interface GetExternalSyncRunRequest {
  id: string;
}

export interface GetExternalSyncRecordTimelineRequest {
  mappingId: string;
  localObjectId: string;
  externalKey: string;
  limit: number;
}

export interface ExternalSyncRecordTimelineResponse {
  entries: ExternalSyncRecordTimelineEntry[];
}

export interface RetryExternalSyncRunRequest {
  id: string;
}

export interface RetryExternalSyncFailureRequest {
  id: string;
}

export interface ResolveExternalSyncConflictRequest {
  id: string;
  resolution: ExternalSyncConflictResolution;
}

export interface BatchResolveExternalSyncConflictsRequest {
  ids: string[];
  resolution: ExternalSyncConflictResolution;
}

export interface BatchResolveExternalSyncConflictsResponse {
  conflicts: ExternalSyncConflict[];
  resolvedCount: number;
}

export interface ListExternalSyncEventsRequest {
  connectionId: string;
  status: string;
  limit: number;
  beforeId: string;
}

export interface ListExternalSyncEventsResponse {
  events: ExternalSyncEvent[];
  nextBeforeId: string;
}

export interface GetExternalSyncEventRequest {
  id: string;
}

export interface ReplayExternalSyncEventRequest {
  id: string;
}

export interface ReplayExternalSyncEventResponse {
  event?: ExternalSyncEvent | undefined;
  run?: ExternalSyncRun | undefined;
}

export interface GetExternalSyncHealthRequest {
}

/**
 * ExternalSyncService manages tenant-scoped external system connections and
 * the sync-run ledger that keeps Attune objects aligned with external issues.
 */
export interface ExternalSyncService {
  ListExternalConnections(request: ListExternalConnectionsRequest): Promise<ListExternalConnectionsResponse>;
  CreateExternalConnection(request: CreateExternalConnectionRequest): Promise<ExternalConnection>;
  UpdateExternalConnection(request: UpdateExternalConnectionRequest): Promise<ExternalConnection>;
  DeleteExternalConnection(request: DeleteExternalConnectionRequest): Promise<DeleteExternalConnectionResponse>;
  TestExternalConnection(request: TestExternalConnectionRequest): Promise<TestExternalConnectionResponse>;
  ResumeExternalConnection(request: ResumeExternalConnectionRequest): Promise<ExternalConnection>;
  QualifyExternalConnection(request: QualifyExternalConnectionRequest): Promise<QualifyExternalConnectionResponse>;
  DiscoverExternalConnectionSchema(
    request: DiscoverExternalConnectionSchemaRequest,
  ): Promise<DiscoverExternalConnectionSchemaResponse>;
  ListExternalObjectMappings(request: ListExternalObjectMappingsRequest): Promise<ListExternalObjectMappingsResponse>;
  UpdateExternalObjectMapping(request: UpdateExternalObjectMappingRequest): Promise<ExternalObjectMapping>;
  PreviewExternalObjectMapping(
    request: PreviewExternalObjectMappingRequest,
  ): Promise<PreviewExternalObjectMappingResponse>;
  ResetExternalSyncCursor(request: ResetExternalSyncCursorRequest): Promise<ResetExternalSyncCursorResponse>;
  RequestExternalSyncBackfill(
    request: RequestExternalSyncBackfillRequest,
  ): Promise<RequestExternalSyncBackfillResponse>;
  RequestExternalSyncRun(request: RequestExternalSyncRunRequest): Promise<ExternalSyncRun>;
  ListExternalSyncRuns(request: ListExternalSyncRunsRequest): Promise<ListExternalSyncRunsResponse>;
  GetExternalSyncRun(request: GetExternalSyncRunRequest): Promise<ExternalSyncRunDetail>;
  GetExternalSyncRecordTimeline(
    request: GetExternalSyncRecordTimelineRequest,
  ): Promise<ExternalSyncRecordTimelineResponse>;
  RetryExternalSyncRun(request: RetryExternalSyncRunRequest): Promise<ExternalSyncRun>;
  RetryExternalSyncFailure(request: RetryExternalSyncFailureRequest): Promise<ExternalSyncRecordFailure>;
  ResolveExternalSyncConflict(request: ResolveExternalSyncConflictRequest): Promise<ExternalSyncConflict>;
  BatchResolveExternalSyncConflicts(
    request: BatchResolveExternalSyncConflictsRequest,
  ): Promise<BatchResolveExternalSyncConflictsResponse>;
  ListExternalSyncEvents(request: ListExternalSyncEventsRequest): Promise<ListExternalSyncEventsResponse>;
  GetExternalSyncEvent(request: GetExternalSyncEventRequest): Promise<ExternalSyncEvent>;
  ReplayExternalSyncEvent(request: ReplayExternalSyncEventRequest): Promise<ReplayExternalSyncEventResponse>;
  GetExternalSyncHealth(request: GetExternalSyncHealthRequest): Promise<ExternalSyncHealthResponse>;
}
