// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/gdpr.proto

/* eslint-disable */
import { type HttpBody } from "../../google/api/httpbody";

export const protobufPackage = "attune.v1";

export enum GdprExportStatus {
  GDPR_EXPORT_STATUS_UNSPECIFIED = "GDPR_EXPORT_STATUS_UNSPECIFIED",
  GDPR_EXPORT_STATUS_QUEUED = "GDPR_EXPORT_STATUS_QUEUED",
  GDPR_EXPORT_STATUS_RUNNING = "GDPR_EXPORT_STATUS_RUNNING",
  GDPR_EXPORT_STATUS_COMPLETED = "GDPR_EXPORT_STATUS_COMPLETED",
  GDPR_EXPORT_STATUS_FAILED = "GDPR_EXPORT_STATUS_FAILED",
  GDPR_EXPORT_STATUS_EXPIRED = "GDPR_EXPORT_STATUS_EXPIRED",
  GDPR_EXPORT_STATUS_REVOKED = "GDPR_EXPORT_STATUS_REVOKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum GdprRequestStatus {
  GDPR_REQUEST_STATUS_UNSPECIFIED = "GDPR_REQUEST_STATUS_UNSPECIFIED",
  GDPR_REQUEST_STATUS_QUEUED = "GDPR_REQUEST_STATUS_QUEUED",
  GDPR_REQUEST_STATUS_RUNNING = "GDPR_REQUEST_STATUS_RUNNING",
  GDPR_REQUEST_STATUS_READY = "GDPR_REQUEST_STATUS_READY",
  GDPR_REQUEST_STATUS_DOWNLOADED = "GDPR_REQUEST_STATUS_DOWNLOADED",
  GDPR_REQUEST_STATUS_COMPLETED = "GDPR_REQUEST_STATUS_COMPLETED",
  GDPR_REQUEST_STATUS_FAILED = "GDPR_REQUEST_STATUS_FAILED",
  GDPR_REQUEST_STATUS_EXPIRED = "GDPR_REQUEST_STATUS_EXPIRED",
  GDPR_REQUEST_STATUS_SCHEDULED = "GDPR_REQUEST_STATUS_SCHEDULED",
  GDPR_REQUEST_STATUS_CANCELLED = "GDPR_REQUEST_STATUS_CANCELLED",
  GDPR_REQUEST_STATUS_REVOKED = "GDPR_REQUEST_STATUS_REVOKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum GdprRequestType {
  GDPR_REQUEST_TYPE_UNSPECIFIED = "GDPR_REQUEST_TYPE_UNSPECIFIED",
  GDPR_REQUEST_TYPE_EXPORT = "GDPR_REQUEST_TYPE_EXPORT",
  GDPR_REQUEST_TYPE_DELETE = "GDPR_REQUEST_TYPE_DELETE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ExportGdprSubjectRequest {
  subjectKey: string;
}

export interface ExportGdprSubjectResponse {
  jobId: string;
  status: GdprExportStatus;
  retryAfterSeconds: number;
}

export interface GetGdprExportRequest {
  jobId: string;
}

export interface DownloadGdprExportRequest {
  jobId: string;
}

export interface RevokeGdprExportRequest {
  jobId: string;
}

export interface RevokeGdprExportResponse {
  jobId: string;
  status: GdprExportStatus;
  requestStatus: GdprRequestStatus;
}

export interface GdprExportStatusResponse {
  jobId: string;
  subjectKey: string;
  subjectDisplay: string;
  status: GdprExportStatus;
  retryAfterSeconds: number;
  downloadPath?: string | undefined;
  archiveFilename?: string | undefined;
  error?: string | undefined;
  feedbackCount: number;
  tagAssignmentCount: number;
  feedbackAuditCount: number;
  llmAuditCount: number;
  createdAt: string;
  startedAt?: string | undefined;
  completedAt?: string | undefined;
  expiresAt?: string | undefined;
  downloadedAt?: string | undefined;
  revokedAt?: string | undefined;
}

export interface DeleteGdprSubjectRequest {
  subjectKey: string;
}

export interface DeleteGdprSubjectResponse {
  requestId: string;
  status: GdprRequestStatus;
  executeAfter?: string | undefined;
  subjectKey: string;
  feedbackCount: number;
  tagAssignmentCount: number;
  feedbackAuditCount: number;
  llmAuditCount: number;
  outboxCount: number;
}

export interface CancelGdprRequestRequest {
  requestId: string;
}

export interface CancelGdprRequestResponse {
  requestId: string;
  status: GdprRequestStatus;
}

export interface ListGdprRequestsRequest {
  cursor?: string | undefined;
  limit: number;
  requestType: string;
}

export interface GdprRequestSummary {
  requestId: string;
  requestType: GdprRequestType;
  status: GdprRequestStatus;
  subjectKey: string;
  subjectDisplay: string;
  createdBy: string;
  feedbackCount: number;
  tagAssignmentCount: number;
  feedbackAuditCount: number;
  llmAuditCount: number;
  createdAt: string;
  startedAt?: string | undefined;
  completedAt?: string | undefined;
  expiresAt?: string | undefined;
  downloadedAt?: string | undefined;
  archiveFilename?: string | undefined;
  error?: string | undefined;
  executeAfter?: string | undefined;
  cancelledAt?: string | undefined;
  revokedAt?: string | undefined;
  outboxCount: number;
}

export interface ListGdprRequestsResponse {
  items: GdprRequestSummary[];
  nextCursor?: string | undefined;
}

export interface GetGdprOperationsRequest {
}

export interface GdprStepUpStatus {
  satisfied: boolean;
  passwordAllowed: boolean;
  method: string;
  ttlSeconds: number;
  verifiedAt?: string | undefined;
  expiresAt?: string | undefined;
}

export interface GdprOperationsResponse {
  stepUp?: GdprStepUpStatus | undefined;
  exportTtlSeconds: number;
  auditRetentionDays: number;
  auditPruneIntervalSeconds: number;
  queuedRequestCount: number;
  activeRequestCount: number;
  readyExportCount: number;
  nextExportExpiryAt?: string | undefined;
  hashedAuditResidue: boolean;
  backupsMayRetainUntilRotation: boolean;
  legalHoldSupported: boolean;
  deleteGraceWindowSeconds: number;
  scheduledDeleteCount: number;
}

export interface VerifyGdprStepUpRequest {
  password?: string | undefined;
}

export interface VerifyGdprStepUpResponse {
  stepUp?: GdprStepUpStatus | undefined;
}

export interface GdprService {
  ExportGdprSubject(request: ExportGdprSubjectRequest): Promise<ExportGdprSubjectResponse>;
  GetGdprExport(request: GetGdprExportRequest): Promise<GdprExportStatusResponse>;
  DownloadGdprExport(request: DownloadGdprExportRequest): Promise<HttpBody>;
  RevokeGdprExport(request: RevokeGdprExportRequest): Promise<RevokeGdprExportResponse>;
  DeleteGdprSubject(request: DeleteGdprSubjectRequest): Promise<DeleteGdprSubjectResponse>;
  CancelGdprRequest(request: CancelGdprRequestRequest): Promise<CancelGdprRequestResponse>;
  ListGdprRequests(request: ListGdprRequestsRequest): Promise<ListGdprRequestsResponse>;
  GetGdprOperations(request: GetGdprOperationsRequest): Promise<GdprOperationsResponse>;
  VerifyGdprStepUp(request: VerifyGdprStepUpRequest): Promise<VerifyGdprStepUpResponse>;
}
