// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/guard_policy.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface GuardPolicy {
  id: string;
  /** absent for system policies */
  tenantId?: string | undefined;
  name: string;
  /** baseline | default | override */
  kind: string;
  enabled: boolean;
  priority: number;
  target?: GuardTarget | undefined;
  rules: GuardRule[];
  /** system | tenant */
  scope: string;
}

export interface GuardTarget {
  channels: string[];
  sourceIds: string[];
  sourceTags: string[];
  purposes: string[];
  stages: string[];
  environments: string[];
}

export interface GuardRule {
  /** v1: pii */
  guard: string;
  /** llm_input | llm_output | outbound | tool_call */
  stage: string;
  entities: string[];
  /** off | audit | redact | block */
  action: string;
  replacement: string;
}

export interface ListGuardPoliciesRequest {
}

export interface ListGuardPoliciesResponse {
  items: GuardPolicy[];
}

export interface CreateGuardPolicyRequest {
  policy?: GuardPolicy | undefined;
}

export interface PatchGuardPolicyRequest {
  id: string;
  policy?: GuardPolicy | undefined;
}

export interface DeleteGuardPolicyRequest {
  id: string;
}

export interface DeleteGuardPolicyResponse {
}

export interface UpdateGuardPoliciesRequest {
  policies: GuardPolicy[];
}

export interface UpdateGuardPoliciesResponse {
  items: GuardPolicy[];
}

export interface ResolveGuardPolicyRequest {
  channel: string;
  sourceId: string;
  sourceTags: string[];
  /** defaults server-side to enrich */
  purpose: string;
  environment: string;
}

export interface ResolveGuardPolicyResponse {
  rules: GuardRule[];
}

/**
 * GuardPolicyService manages tenant-scoped guard policies and effective-policy
 * previews for the Console. System policies are returned read-only by list and
 * participate in effective resolution, but tenant sessions only write
 * tenant-scoped rows.
 */
export interface GuardPolicyService {
  /** GET /fb/v1/console/guard-policies */
  ListGuardPolicies(request: ListGuardPoliciesRequest): Promise<ListGuardPoliciesResponse>;
  /** POST /fb/v1/console/guard-policies — create one tenant policy. */
  CreateGuardPolicy(request: CreateGuardPolicyRequest): Promise<GuardPolicy>;
  /** PATCH /fb/v1/console/guard-policies/{id} — replace one tenant policy. */
  PatchGuardPolicy(request: PatchGuardPolicyRequest): Promise<GuardPolicy>;
  /** DELETE /fb/v1/console/guard-policies/{id} */
  DeleteGuardPolicy(request: DeleteGuardPolicyRequest): Promise<DeleteGuardPolicyResponse>;
  /** PUT /fb/v1/console/guard-policies — replace current tenant policies. */
  UpdateGuardPolicies(request: UpdateGuardPoliciesRequest): Promise<UpdateGuardPoliciesResponse>;
  /** POST /fb/v1/console/guard-policies/effective — preview resolved rules. */
  ResolveGuardPolicy(request: ResolveGuardPolicyRequest): Promise<ResolveGuardPolicyResponse>;
}
