// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/inbound_source.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/** InboundSource never carries the secret — it is write-only once stored. */
export interface InboundSource {
  id: string;
  tenantId: string;
  /** "webhook" | "email" | "slack" | "zendesk" | "intercom" | future channels */
  channel: string;
  name: string;
  slug: string;
  enabled: boolean;
  /** RFC3339, null if never received */
  lastEventAt?:
    | string
    | undefined;
  /** poll-mode cursor; 0 for push channels */
  lastUid: string;
  /** empty if healthy */
  lastError: string;
  /** RFC3339 */
  createdAt: string;
  /** RFC3339 */
  updatedAt: string;
  /** Sync progress stats (populated for poll-mode channels like Zendesk). */
  ticketsSynced?: string | undefined;
  lastSyncedTicketId?: string | undefined;
  backfillDone?: boolean | undefined;
}

export interface ListInboundSourcesRequest {
}

export interface ListInboundSourcesResponse {
  items: InboundSource[];
}

export interface GetInboundSourceRequest {
  /** path param (UUID) */
  id: string;
}

/**
 * CreateInboundSourceRequest — one of webhook_config / email_config is
 * required based on channel. The framework selects the relevant payload;
 * the other is ignored.
 */
export interface CreateInboundSourceRequest {
  channel: string;
  name: string;
  webhookConfig?: WebhookCreateConfig | undefined;
  emailConfig?: EmailCreateConfig | undefined;
  slackConfig?: SlackConnConfig | undefined;
  zendeskConfig?: ZendeskConnConfig | undefined;
  intercomConfig?: IntercomConnConfig | undefined;
}

/**
 * CreateInboundSourceResponse always carries the persisted InboundSource.
 * For webhook channels, webhook_secret_reveal is also populated — this is
 * the only place the raw secret is ever transmitted; clients must store
 * it immediately because rotate is the only path to a new value.
 */
export interface CreateInboundSourceResponse {
  source?: InboundSource | undefined;
  webhookSecretReveal?: WebhookSecretReveal | undefined;
}

/**
 * WebhookCreateConfig has no body today — the secret is generated
 * server-side. The empty message is a placeholder so future webhook
 * options (e.g., HMAC algorithm override) can be added without breaking
 * CreateInboundSourceRequest's shape.
 */
export interface WebhookCreateConfig {
}

export interface EmailCreateConfig {
  host: string;
  port: number;
  tls: boolean;
  username: string;
  password: string;
  /** defaults to "INBOX" */
  folder: string;
  /** "now" | "all_unseen" (default "now") */
  startFrom: string;
  /** "mark_seen" | "keep_unseen" | "move_to:<folder>" (default "mark_seen") */
  afterIngest: string;
}

/**
 * WebhookSecretReveal — one-time payload returned at Create + Rotate so
 * admins can publish the URL + secret to their automation. The secret
 * is lowercase-hex-encoded; signature is HMAC-SHA256(secret_raw_bytes,
 * "<X-Attune-Timestamp>.<body>") (spec §Webhook adapter). The
 * signature header is hex-encoded (e.g. "sha256=ab12…").
 */
export interface WebhookSecretReveal {
  url: string;
  secretHex: string;
  curlExample: string;
}

export interface RotateInboundSourceSecretRequest {
  /** path param (UUID) */
  id: string;
}

export interface RotateInboundSourceSecretResponse {
  secretHex: string;
  /** RFC3339, end of 24h grace */
  nextEligibleAt: string;
}

export interface PauseInboundSourceRequest {
  id: string;
}

export interface ResumeInboundSourceRequest {
  id: string;
}

export interface DeleteInboundSourceRequest {
  id: string;
}

export interface DeleteInboundSourceResponse {
}

/**
 * TestInboundConnectionRequest validates an IMAP config without
 * persisting it. Returns ok=false + error message rather than 5xx when
 * the upstream rejects credentials or channel access.
 */
export interface TestInboundConnectionRequest {
  /** currently "email", "slack", "zendesk", or "intercom" */
  channel: string;
  emailConfig?: EmailConnConfig | undefined;
  slackConfig?: SlackConnConfig | undefined;
  zendeskConfig?: ZendeskConnConfig | undefined;
  intercomConfig?: IntercomConnConfig | undefined;
}

export interface TestInboundConnectionResponse {
  ok: boolean;
  error?: string | undefined;
  latencyMs?: string | undefined;
}

export interface EmailConnConfig {
  host: string;
  port: number;
  tls: boolean;
  username: string;
  password: string;
  folder: string;
}

export interface SlackConnConfig {
  botToken: string;
  /** optional for auth-only test / required for create */
  channelId: string;
}

export interface SlackChannel {
  id: string;
  name: string;
  isPrivate: boolean;
  isArchived: boolean;
  isShared: boolean;
}

export interface DiscoverSlackChannelsRequest {
  slackConfig?: SlackConnConfig | undefined;
}

export interface DiscoverSlackChannelsResponse {
  channels: SlackChannel[];
}

/**
 * ZendeskConnConfig carries the Zendesk connection parameters for create
 * and test-connection flows. Auth supports "api_token" (email + API
 * token, sunsetting 2027-04-30) and "oauth" (OAuth 2.0 client
 * credentials).
 */
export interface ZendeskConnConfig {
  subdomain: string;
  /** "api_token" | "oauth" */
  authMode: string;
  /** api_token auth fields. */
  email?: string | undefined;
  apiToken?: string | undefined;
  startFrom?:
    | string
    | undefined;
  /** OAuth paste-mode fields (replaces old client-credential fields). */
  oauthAccessToken?: string | undefined;
  oauthRefreshToken?:
    | string
    | undefined;
  /** for refresh grant */
  oauthClientIdV2?:
    | string
    | undefined;
  /** for refresh grant */
  oauthClientSecretV2?:
    | string
    | undefined;
  /** Advanced config. */
  filterTags: string[];
  filterExcludeTags: string[];
  filterStatuses: string[];
  maxCommentFetches?: number | undefined;
}

/**
 * IntercomConnConfig carries the Intercom connection parameters for
 * create and test-connection flows. Auth is a private-app Access Token
 * (Bearer) — Intercom's documented model for same-workspace server
 * integrations; OAuth applies to public/multi-workspace apps (#32).
 */
export interface IntercomConnConfig {
  /** "us" | "eu" | "au" */
  region: string;
  /** write-only, never returned */
  accessToken: string;
  /** "now" (default) | "full" */
  startFrom?:
    | string
    | undefined;
  /** open/closed/snoozed; empty = all */
  filterStates: string[];
  maxDetailFetches?: number | undefined;
}

/**
 * InboundSourceService manages a tenant's inbound source rows (#66
 * channel-agnostic inbound framework). Sources back the webhook,
 * email IMAP, Slack, Zendesk, and Intercom adapters; future channels
 * (RSS, scrape, MQ, …) hang off the same shape.
 */
export interface InboundSourceService {
  /** GET /fb/v1/console/inbound/sources */
  ListInboundSources(request: ListInboundSourcesRequest): Promise<ListInboundSourcesResponse>;
  /** GET /fb/v1/console/inbound/sources/{id} */
  GetInboundSource(request: GetInboundSourceRequest): Promise<InboundSource>;
  /**
   * POST /fb/v1/console/inbound/sources — create webhook, email, Slack, or Zendesk source.
   * Webhook responses include a one-time secret reveal (url + secret +
   * example); the raw secret is never returned again.
   */
  CreateInboundSource(request: CreateInboundSourceRequest): Promise<CreateInboundSourceResponse>;
  /**
   * POST /fb/v1/console/inbound/sources/{id}/rotate-secret — webhook only.
   * Returns 409 with rotation_in_grace_window error if a prior rotation
   * is still inside its 24h grace.
   */
  RotateInboundSourceSecret(request: RotateInboundSourceSecretRequest): Promise<RotateInboundSourceSecretResponse>;
  /** POST /fb/v1/console/inbound/sources/{id}/pause — disables the source. */
  PauseInboundSource(request: PauseInboundSourceRequest): Promise<InboundSource>;
  /** POST /fb/v1/console/inbound/sources/{id}/resume — re-enables. */
  ResumeInboundSource(request: ResumeInboundSourceRequest): Promise<InboundSource>;
  /** DELETE /fb/v1/console/inbound/sources/{id} */
  DeleteInboundSource(request: DeleteInboundSourceRequest): Promise<DeleteInboundSourceResponse>;
  /**
   * POST /fb/v1/console/inbound/sources/test-connection — email,
   * Slack, or Zendesk only, no state changes. Validates the configured
   * auth path.
   */
  TestInboundConnection(request: TestInboundConnectionRequest): Promise<TestInboundConnectionResponse>;
  /**
   * POST /fb/v1/console/inbound/sources/slack/discover — returns the
   * readable channels for a Slack bot token so Console can let the
   * operator select a channel without hand-typing opaque IDs.
   */
  DiscoverSlackChannels(request: DiscoverSlackChannelsRequest): Promise<DiscoverSlackChannelsResponse>;
}
