// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/ingest.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * IngestRequest is the JSON body of POST /v1/feedback/ingest.
 *
 * JSON field names follow the protoJSON default (lowerCamelCase), which exactly
 * reproduces today's wire: content / source / sourceUser / sourceMeta / pageUrl.
 */
export interface IngestRequest {
  /** The feedback text. Required; the handler caps it at 5000 chars. */
  content: string;
  /**
   * Inbound channel/source identity ("api", "web", …). Channel-agnostic and
   * validated against the handler allow-list; defaults to "api" when empty.
   */
  source: string;
  /** Opaque end-user identifier from the originating system (optional). */
  sourceUser: string;
  /** Arbitrary source-specific metadata (optional). */
  sourceMeta?:
    | { [key: string]: any }
    | undefined;
  /** Originating page URL, for the in-app web widget (optional). */
  pageUrl: string;
}

/** IngestResponse is returned on 200. */
export interface IngestResponse {
  /**
   * The stored feedback row id.
   *
   * NOTE: per the protoJSON spec, int64 serializes as a JSON *string*
   * ({"id":"123"}). Deliberate — JavaScript cannot safely parse 64-bit integers.
   */
  id: string;
  /** Enrichment lifecycle state at ingest time (always "pending" here). */
  enrichmentStatus: string;
}

/** Feedback is a console feedback list row. */
export interface Feedback {
  /** → JSON string */
  id: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  pageUrl: string;
  enrichedTitle?:
    | string
    | undefined;
  /** bug | feature | ops | question | other */
  enrichedKind?:
    | string
    | undefined;
  /** P0 | P1 | P2 | P3 */
  enrichedSeverity?: string | undefined;
  enrichedModules: string[];
  enrichedPriority?:
    | number
    | undefined;
  /** pending | enriching | done | failed */
  enrichmentStatus: string;
  /** RFC3339 */
  createdAt: string;
}

/** FeedbackDetail is the single-row view: the list fields plus extras (flat). */
export interface FeedbackDetail {
  id: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  pageUrl: string;
  enrichedTitle?: string | undefined;
  enrichedKind?: string | undefined;
  enrichedSeverity?: string | undefined;
  enrichedModules: string[];
  enrichedPriority?: number | undefined;
  enrichmentStatus: string;
  createdAt: string;
  sourceMeta?: { [key: string]: any } | undefined;
  attachments: Attachment[];
  enrichmentError?:
    | string
    | undefined;
  /** RFC3339 */
  enrichedAt?: string | undefined;
}

export interface Attachment {
  url: string;
  mime?: string | undefined;
  size?: string | undefined;
}

export interface ListFeedbackRequest {
  /** last row id; opaque to the client */
  cursor?: string | undefined;
  limit?: number | undefined;
  kind?: string | undefined;
  severity?:
    | string
    | undefined;
  /** full-text query */
  q?: string | undefined;
}

export interface ListFeedbackResponse {
  items: Feedback[];
  /** absent when no more pages */
  nextCursor?: string | undefined;
}

export interface GetFeedbackRequest {
  /** path param */
  id: string;
}

export interface GetFeedbackStatsRequest {
}

export interface GetFeedbackStatsResponse {
  periodStart: string;
  periodEnd: string;
  total: string;
  byKind: { [key: string]: string };
}

export interface GetFeedbackStatsResponse_ByKindEntry {
  key: string;
  value: string;
}

/**
 * FeedbackService is attune's feedback API. Today it exposes Ingest
 * (POST /v1/feedback/ingest, public, API-key auth); the console feedback reads
 * (list / stats / detail) join it as the migration proceeds.
 *
 * We do NOT generate server stubs — chi routing stays. The google.api.http
 * annotation exists only so protoc-gen-openapi emits the REST path + operation
 * into the OpenAPI document. (ts-proto with onlyTypes ignores this service.)
 */
export interface FeedbackService {
  Ingest(request: IngestRequest): Promise<IngestResponse>;
  /** GET /fb/v1/console/feedback (console; session auth) */
  ListFeedback(request: ListFeedbackRequest): Promise<ListFeedbackResponse>;
  /** GET /fb/v1/console/feedback/{id} */
  GetFeedback(request: GetFeedbackRequest): Promise<FeedbackDetail>;
  /** GET /fb/v1/console/feedback/stats */
  GetFeedbackStats(request: GetFeedbackStatsRequest): Promise<GetFeedbackStatsResponse>;
}
