// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/ingest.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * IngestRequest is the JSON body of POST /v1/feedback/ingest.
 *
 * JSON field names follow the protoJSON default (lowerCamelCase), which exactly
 * reproduces today's wire: content / source / sourceUser / sourceMeta / pageUrl.
 */
export interface IngestRequest {
  /** The feedback text. Required; the handler caps it at 5000 chars. */
  content: string;
  /**
   * Inbound channel/source identity ("api", "web", …). Channel-agnostic and
   * validated against the handler allow-list; defaults to "api" when empty.
   */
  source: string;
  /** Opaque end-user identifier from the originating system (optional). */
  sourceUser: string;
  /** Arbitrary source-specific metadata (optional). */
  sourceMeta?:
    | { [key: string]: any }
    | undefined;
  /** Originating page URL, for the in-app web widget (optional). */
  pageUrl: string;
}

/** IngestResponse is returned on 200. */
export interface IngestResponse {
  /**
   * The stored feedback row id.
   *
   * NOTE: per the protoJSON spec, int64 serializes as a JSON *string*
   * ({"id":"123"}). Deliberate — JavaScript cannot safely parse 64-bit integers.
   */
  id: string;
  /** Enrichment lifecycle state at ingest time (always "pending" here). */
  enrichmentStatus: string;
}

/**
 * FeedbackService is attune's feedback API. Today it exposes Ingest
 * (POST /v1/feedback/ingest, public, API-key auth); the console feedback reads
 * (list / stats / detail) join it as the migration proceeds.
 *
 * We do NOT generate server stubs — chi routing stays. The google.api.http
 * annotation exists only so protoc-gen-openapi emits the REST path + operation
 * into the OpenAPI document. (ts-proto with onlyTypes ignores this service.)
 */
export interface FeedbackService {
  Ingest(request: IngestRequest): Promise<IngestResponse>;
}
