// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/llm_config.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * LLMChannel never returns api_key. API keys are write-only and persisted
 * encrypted with the shared Tink keyset.
 */
export interface LLMChannel {
  id: string;
  name: string;
  /** openai-compat | openai-responses | anthropic | gemini */
  protocol: string;
  baseUrl: string;
  /** bearer | none */
  authMode: string;
  hasApiKey: boolean;
  credentialKeyId: string;
  /** enabled | disabled | draining */
  status: string;
  priority: number;
  weight: number;
  timeoutSeconds: number;
  createdAt: string;
  updatedAt: string;
  lastTestedAt?: string | undefined;
  lastTestStatus: string;
  lastError: string;
}

export interface ListLLMChannelsRequest {
}

export interface ListLLMChannelsResponse {
  items: LLMChannel[];
}

export interface CreateLLMChannelRequest {
  name: string;
  protocol: string;
  baseUrl: string;
  /** defaults to bearer */
  authMode: string;
  /** write-only */
  apiKey?:
    | string
    | undefined;
  /** defaults to enabled */
  status: string;
  priority: number;
  /** omitted defaults to 1; explicit 0 is valid */
  weight?:
    | number
    | undefined;
  /** omitted defaults to 60 */
  timeoutSeconds?: number | undefined;
}

export interface GetLLMChannelRequest {
  id: string;
}

export interface UpdateLLMChannelRequest {
  id: string;
  name: string;
  protocol: string;
  baseUrl: string;
  authMode: string;
  /** omitted = keep existing; set only to rotate */
  apiKey?: string | undefined;
  status: string;
  priority: number;
  /** omitted keeps existing value */
  weight?:
    | number
    | undefined;
  /** omitted keeps existing value */
  timeoutSeconds?: number | undefined;
}

export interface DeleteLLMChannelRequest {
  id: string;
}

export interface DeleteLLMChannelResponse {
}

export interface TestLLMChannelRequest {
  id: string;
  /** optional; defaults to highest-priority enabled ability */
  providerModel: string;
  /** optional; defaults to a tiny attune-ok prompt */
  prompt: string;
}

export interface TestLLMChannelResponse {
  ok: boolean;
  providerModel: string;
  text: string;
  inputTokens: number;
  outputTokens: number;
  latencyMs: string;
  channel?: LLMChannel | undefined;
}

export interface LLMProviderModel {
  id: string;
  displayName: string;
  ownedBy: string;
}

export interface ListLLMChannelModelsRequest {
  channelId: string;
}

export interface ListLLMChannelModelsResponse {
  items: LLMProviderModel[];
}

export interface LLMChannelAbility {
  id: string;
  channelId: string;
  logicalModel: string;
  providerModel: string;
  enabled: boolean;
  priority: number;
  weight: number;
  createdAt: string;
  updatedAt: string;
}

export interface ListLLMChannelAbilitiesRequest {
  channelId: string;
}

export interface ListLLMChannelAbilitiesResponse {
  items: LLMChannelAbility[];
}

export interface UpsertLLMChannelAbilityRequest {
  channelId: string;
  logicalModel: string;
  providerModel: string;
  /** defaults to true when omitted */
  enabled?: boolean | undefined;
  priority: number;
  /** omitted defaults to 1; explicit 0 is valid */
  weight?: number | undefined;
}

export interface DeleteLLMChannelAbilityRequest {
  channelId: string;
  logicalModel: string;
}

export interface DeleteLLMChannelAbilityResponse {
}

export interface LLMRoute {
  id: string;
  /** empty = global default */
  tenantId: string;
  purpose: string;
  logicalModel: string;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ListLLMRoutesRequest {
}

export interface ListLLMRoutesResponse {
  items: LLMRoute[];
}

export interface UpsertLLMRouteRequest {
  /** empty = global default */
  tenantId: string;
  purpose: string;
  logicalModel: string;
  /** defaults to true when omitted */
  enabled?: boolean | undefined;
}

export interface DeleteLLMRouteRequest {
  tenantId: string;
  purpose: string;
}

export interface DeleteLLMRouteResponse {
}

/** LLMConfigService manages DB-backed provider channels and routes. */
export interface LLMConfigService {
  ListLLMChannels(request: ListLLMChannelsRequest): Promise<ListLLMChannelsResponse>;
  CreateLLMChannel(request: CreateLLMChannelRequest): Promise<LLMChannel>;
  GetLLMChannel(request: GetLLMChannelRequest): Promise<LLMChannel>;
  UpdateLLMChannel(request: UpdateLLMChannelRequest): Promise<LLMChannel>;
  DeleteLLMChannel(request: DeleteLLMChannelRequest): Promise<DeleteLLMChannelResponse>;
  TestLLMChannel(request: TestLLMChannelRequest): Promise<TestLLMChannelResponse>;
  ListLLMChannelModels(request: ListLLMChannelModelsRequest): Promise<ListLLMChannelModelsResponse>;
  ListLLMChannelAbilities(request: ListLLMChannelAbilitiesRequest): Promise<ListLLMChannelAbilitiesResponse>;
  UpsertLLMChannelAbility(request: UpsertLLMChannelAbilityRequest): Promise<LLMChannelAbility>;
  DeleteLLMChannelAbility(request: DeleteLLMChannelAbilityRequest): Promise<DeleteLLMChannelAbilityResponse>;
  ListLLMRoutes(request: ListLLMRoutesRequest): Promise<ListLLMRoutesResponse>;
  UpsertLLMRoute(request: UpsertLLMRouteRequest): Promise<LLMRoute>;
  DeleteLLMRoute(request: DeleteLLMRouteRequest): Promise<DeleteLLMRouteResponse>;
}
