// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/notify_target.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/** NotifyTarget never carries the secret — it is write-only once stored. */
export interface NotifyTarget {
  id: string;
  /** lark-bot | raw-webhook | slack-bot | email */
  destinationType: string;
  /** pool | radar | all */
  audience: string;
  url: string;
  timeoutSeconds: number;
  disabled: boolean;
  /** RFC3339 */
  createdAt: string;
  /** RFC3339, null if never failed */
  lastFailureAt?: string | undefined;
  lastError: string;
}

export interface ListNotifyTargetsRequest {
}

export interface ListNotifyTargetsResponse {
  items: NotifyTarget[];
}

export interface CreateNotifyTargetRequest {
  destinationType: string;
  /** defaults to "all" */
  audience: string;
  url: string;
  secret?:
    | string
    | undefined;
  /** defaults to 10 */
  timeoutSeconds: number;
  disabled: boolean;
}

export interface UpdateNotifyTargetRequest {
  /** path param (UUID) */
  id: string;
  audience?: string | undefined;
  url?: string | undefined;
  secret?: string | undefined;
  timeoutSeconds?: number | undefined;
  disabled?: boolean | undefined;
}

export interface DeleteNotifyTargetRequest {
  /** path param (UUID) */
  id: string;
}

export interface DeleteNotifyTargetResponse {
}

export interface TestNotifyTargetRequest {
  /** path param (UUID) */
  id: string;
}

export interface TestNotifyTargetResponse {
  ok: boolean;
  statusCode?: number | undefined;
  latencyMs?: string | undefined;
}

/** NotifyTargetService manages a tenant's outbound notification destinations. */
export interface NotifyTargetService {
  /** GET /fb/v1/console/notify-targets */
  ListNotifyTargets(request: ListNotifyTargetsRequest): Promise<ListNotifyTargetsResponse>;
  /** POST /fb/v1/console/notify-targets */
  CreateNotifyTarget(request: CreateNotifyTargetRequest): Promise<NotifyTarget>;
  /** PATCH /fb/v1/console/notify-targets/{id} */
  UpdateNotifyTarget(request: UpdateNotifyTargetRequest): Promise<NotifyTarget>;
  /** DELETE /fb/v1/console/notify-targets/{id} (204) */
  DeleteNotifyTarget(request: DeleteNotifyTargetRequest): Promise<DeleteNotifyTargetResponse>;
  /** POST /fb/v1/console/notify-targets/{id}/test */
  TestNotifyTarget(request: TestNotifyTargetRequest): Promise<TestNotifyTargetResponse>;
}
