// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/search.proto

/* eslint-disable */
import { type FeedbackFilter } from "./common";
import { type Feedback } from "./ingest";

export const protobufPackage = "attune.v1";

/** SemanticSearchRequest is the query envelope for semantic search. */
export interface SemanticSearchRequest {
  /** The natural language query string. */
  q: string;
  /** Maximum results to return (default: 20, max: 100). */
  limit?:
    | number
    | undefined;
  /** Minimum similarity threshold (0.0-1.0). Results below this are excluded. */
  minSimilarity?:
    | number
    | undefined;
  /** Additional filters to apply on top of semantic ranking. */
  filter?:
    | FeedbackFilter
    | undefined;
  /** Weight for semantic (embedding) similarity (0.0-1.0, default: 0.7). */
  semanticWeight?:
    | number
    | undefined;
  /** Weight for keyword (full-text) similarity (0.0-1.0, default: 0.3). */
  keywordWeight?: number | undefined;
}

/** SemanticSearchResponse contains the ranked search results. */
export interface SemanticSearchResponse {
  /** Ranked results ordered by combined similarity score. */
  hits: SemanticSearchHit[];
  /** The embedding model used for this search. */
  embeddingModel: string;
  /** Count of feedback rows that have embeddings in this tenant. */
  totalWithEmbeddings: number;
  /** True if semantic search was unavailable and results are keyword-only. */
  usedKeywordFallback: boolean;
}

/** SemanticSearchHit is a single search result with ranking metadata. */
export interface SemanticSearchHit {
  /** The feedback row. */
  feedback?:
    | Feedback
    | undefined;
  /** Semantic (embedding) similarity score (0.0-1.0). */
  similarity: number;
  /** Keyword (full-text) relevance score (0.0-1.0). */
  keywordScore: number;
  /** How this result was matched: "semantic", "keyword", or "hybrid". */
  matchType: string;
}

/**
 * SearchService provides semantic search over feedback (#30).
 * Uses pgvector embeddings when available, falls back to keyword search.
 */
export interface SearchService {
  SemanticSearch(request: SemanticSearchRequest): Promise<SemanticSearchResponse>;
}
