// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/session.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface LoginRequest {
  email: string;
  password: string;
  /** safe-path-validated server-side; defaults to /console/ */
  redirectUri: string;
}

export interface LoginResponse {
  redirect: string;
}

export interface GetMeRequest {
}

export interface GetMeResponse {
  tenant?: Tenant | undefined;
  user?: SessionUser | undefined;
  csrfToken: string;
}

/** Tenant is the console-facing tenant record. */
export interface Tenant {
  id: string;
  slug: string;
  name: string;
  larkTenantKey?:
    | string
    | undefined;
  /** BCP 47 */
  locale: string;
  /** IANA tz */
  timezone: string;
}

/** SessionUser is the logged-in console user. */
export interface SessionUser {
  openId: string;
  name: string;
  avatarUrl?:
    | string
    | undefined;
  /** admin | member */
  role: string;
}

export interface LogoutRequest {
}

export interface LogoutResponse {
}

/** SessionService backs the console session (login, current tenant + user, logout). */
export interface SessionService {
  /**
   * POST /fb/v1/console/install/login — local admin password login (#66 Plan T11).
   * Replaces the deleted Lark OAuth flow. The server sets the session cookie
   * and returns the safe-validated redirect path the SPA should navigate to.
   */
  Login(request: LoginRequest): Promise<LoginResponse>;
  /** GET /fb/v1/console/me */
  GetMe(request: GetMeRequest): Promise<GetMeResponse>;
  /** POST /fb/v1/console/logout — clears the session cookie (204). */
  Logout(request: LogoutRequest): Promise<LogoutResponse>;
}
