// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/survey.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum SurveyType {
  SURVEY_TYPE_UNSPECIFIED = "SURVEY_TYPE_UNSPECIFIED",
  SURVEY_TYPE_CSAT = "SURVEY_TYPE_CSAT",
  SURVEY_TYPE_CES = "SURVEY_TYPE_CES",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyCampaignStatus {
  SURVEY_CAMPAIGN_STATUS_UNSPECIFIED = "SURVEY_CAMPAIGN_STATUS_UNSPECIFIED",
  SURVEY_CAMPAIGN_STATUS_DRAFT = "SURVEY_CAMPAIGN_STATUS_DRAFT",
  SURVEY_CAMPAIGN_STATUS_ACTIVE = "SURVEY_CAMPAIGN_STATUS_ACTIVE",
  SURVEY_CAMPAIGN_STATUS_ARCHIVED = "SURVEY_CAMPAIGN_STATUS_ARCHIVED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyTriggerEvent {
  SURVEY_TRIGGER_EVENT_UNSPECIFIED = "SURVEY_TRIGGER_EVENT_UNSPECIFIED",
  SURVEY_TRIGGER_EVENT_WORKFLOW_TRANSITION = "SURVEY_TRIGGER_EVENT_WORKFLOW_TRANSITION",
  SURVEY_TRIGGER_EVENT_REPLY_SENT = "SURVEY_TRIGGER_EVENT_REPLY_SENT",
  SURVEY_TRIGGER_EVENT_MANUAL_LINK = "SURVEY_TRIGGER_EVENT_MANUAL_LINK",
  SURVEY_TRIGGER_EVENT_REQUEST_RESOLVED = "SURVEY_TRIGGER_EVENT_REQUEST_RESOLVED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyDistributionMode {
  SURVEY_DISTRIBUTION_MODE_UNSPECIFIED = "SURVEY_DISTRIBUTION_MODE_UNSPECIFIED",
  SURVEY_DISTRIBUTION_MODE_CONTACT_EMAIL = "SURVEY_DISTRIBUTION_MODE_CONTACT_EMAIL",
  SURVEY_DISTRIBUTION_MODE_SOURCE_LINK = "SURVEY_DISTRIBUTION_MODE_SOURCE_LINK",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyDedupePolicy {
  SURVEY_DEDUPE_POLICY_UNSPECIFIED = "SURVEY_DEDUPE_POLICY_UNSPECIFIED",
  SURVEY_DEDUPE_POLICY_ONE_PER_SOURCE = "SURVEY_DEDUPE_POLICY_ONE_PER_SOURCE",
  SURVEY_DEDUPE_POLICY_ONE_PER_RESOLUTION = "SURVEY_DEDUPE_POLICY_ONE_PER_RESOLUTION",
  SURVEY_DEDUPE_POLICY_ONE_PER_TRIGGER = "SURVEY_DEDUPE_POLICY_ONE_PER_TRIGGER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyDeliveryStatus {
  SURVEY_DELIVERY_STATUS_UNSPECIFIED = "SURVEY_DELIVERY_STATUS_UNSPECIFIED",
  SURVEY_DELIVERY_STATUS_PENDING = "SURVEY_DELIVERY_STATUS_PENDING",
  SURVEY_DELIVERY_STATUS_ACCEPTED = "SURVEY_DELIVERY_STATUS_ACCEPTED",
  SURVEY_DELIVERY_STATUS_DELIVERED = "SURVEY_DELIVERY_STATUS_DELIVERED",
  SURVEY_DELIVERY_STATUS_REJECTED = "SURVEY_DELIVERY_STATUS_REJECTED",
  SURVEY_DELIVERY_STATUS_BOUNCED = "SURVEY_DELIVERY_STATUS_BOUNCED",
  SURVEY_DELIVERY_STATUS_COMPLAINED = "SURVEY_DELIVERY_STATUS_COMPLAINED",
  SURVEY_DELIVERY_STATUS_DELAYED = "SURVEY_DELIVERY_STATUS_DELAYED",
  SURVEY_DELIVERY_STATUS_NOT_APPLICABLE = "SURVEY_DELIVERY_STATUS_NOT_APPLICABLE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyResponseStatus {
  SURVEY_RESPONSE_STATUS_UNSPECIFIED = "SURVEY_RESPONSE_STATUS_UNSPECIFIED",
  SURVEY_RESPONSE_STATUS_NOT_STARTED = "SURVEY_RESPONSE_STATUS_NOT_STARTED",
  SURVEY_RESPONSE_STATUS_OPENED = "SURVEY_RESPONSE_STATUS_OPENED",
  SURVEY_RESPONSE_STATUS_STARTED = "SURVEY_RESPONSE_STATUS_STARTED",
  SURVEY_RESPONSE_STATUS_COMPLETED = "SURVEY_RESPONSE_STATUS_COMPLETED",
  SURVEY_RESPONSE_STATUS_EXPIRED = "SURVEY_RESPONSE_STATUS_EXPIRED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveySuppressionStatus {
  SURVEY_SUPPRESSION_STATUS_UNSPECIFIED = "SURVEY_SUPPRESSION_STATUS_UNSPECIFIED",
  SURVEY_SUPPRESSION_STATUS_NOT_SUPPRESSED = "SURVEY_SUPPRESSION_STATUS_NOT_SUPPRESSED",
  SURVEY_SUPPRESSION_STATUS_SUPPRESSED = "SURVEY_SUPPRESSION_STATUS_SUPPRESSED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyLowScoreReviewStatus {
  SURVEY_LOW_SCORE_REVIEW_STATUS_UNSPECIFIED = "SURVEY_LOW_SCORE_REVIEW_STATUS_UNSPECIFIED",
  SURVEY_LOW_SCORE_REVIEW_STATUS_OPEN = "SURVEY_LOW_SCORE_REVIEW_STATUS_OPEN",
  SURVEY_LOW_SCORE_REVIEW_STATUS_IN_REVIEW = "SURVEY_LOW_SCORE_REVIEW_STATUS_IN_REVIEW",
  SURVEY_LOW_SCORE_REVIEW_STATUS_RESOLVED = "SURVEY_LOW_SCORE_REVIEW_STATUS_RESOLVED",
  SURVEY_LOW_SCORE_REVIEW_STATUS_DISMISSED = "SURVEY_LOW_SCORE_REVIEW_STATUS_DISMISSED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyLowScoreSeverity {
  SURVEY_LOW_SCORE_SEVERITY_UNSPECIFIED = "SURVEY_LOW_SCORE_SEVERITY_UNSPECIFIED",
  SURVEY_LOW_SCORE_SEVERITY_LOW = "SURVEY_LOW_SCORE_SEVERITY_LOW",
  SURVEY_LOW_SCORE_SEVERITY_MEDIUM = "SURVEY_LOW_SCORE_SEVERITY_MEDIUM",
  SURVEY_LOW_SCORE_SEVERITY_HIGH = "SURVEY_LOW_SCORE_SEVERITY_HIGH",
  SURVEY_LOW_SCORE_SEVERITY_CRITICAL = "SURVEY_LOW_SCORE_SEVERITY_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyAnalyticsSegmentDimension {
  SURVEY_ANALYTICS_SEGMENT_DIMENSION_UNSPECIFIED = "SURVEY_ANALYTICS_SEGMENT_DIMENSION_UNSPECIFIED",
  SURVEY_ANALYTICS_SEGMENT_DIMENSION_SOURCE_TYPE = "SURVEY_ANALYTICS_SEGMENT_DIMENSION_SOURCE_TYPE",
  SURVEY_ANALYTICS_SEGMENT_DIMENSION_CAMPAIGN = "SURVEY_ANALYTICS_SEGMENT_DIMENSION_CAMPAIGN",
  SURVEY_ANALYTICS_SEGMENT_DIMENSION_DISTRIBUTION_MODE = "SURVEY_ANALYTICS_SEGMENT_DIMENSION_DISTRIBUTION_MODE",
  SURVEY_ANALYTICS_SEGMENT_DIMENSION_TRIGGER_EVENT = "SURVEY_ANALYTICS_SEGMENT_DIMENSION_TRIGGER_EVENT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyAnalyticsInsightSeverity {
  SURVEY_ANALYTICS_INSIGHT_SEVERITY_UNSPECIFIED = "SURVEY_ANALYTICS_INSIGHT_SEVERITY_UNSPECIFIED",
  SURVEY_ANALYTICS_INSIGHT_SEVERITY_INFO = "SURVEY_ANALYTICS_INSIGHT_SEVERITY_INFO",
  SURVEY_ANALYTICS_INSIGHT_SEVERITY_WARNING = "SURVEY_ANALYTICS_INSIGHT_SEVERITY_WARNING",
  SURVEY_ANALYTICS_INSIGHT_SEVERITY_CRITICAL = "SURVEY_ANALYTICS_INSIGHT_SEVERITY_CRITICAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyCampaignHealthStatus {
  SURVEY_CAMPAIGN_HEALTH_STATUS_UNSPECIFIED = "SURVEY_CAMPAIGN_HEALTH_STATUS_UNSPECIFIED",
  SURVEY_CAMPAIGN_HEALTH_STATUS_HEALTHY = "SURVEY_CAMPAIGN_HEALTH_STATUS_HEALTHY",
  SURVEY_CAMPAIGN_HEALTH_STATUS_NEEDS_ATTENTION = "SURVEY_CAMPAIGN_HEALTH_STATUS_NEEDS_ATTENTION",
  SURVEY_CAMPAIGN_HEALTH_STATUS_BLOCKED = "SURVEY_CAMPAIGN_HEALTH_STATUS_BLOCKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyCampaignHealthCheckStatus {
  SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_UNSPECIFIED = "SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_UNSPECIFIED",
  SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_PASS = "SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_PASS",
  SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_WARN = "SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_WARN",
  SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_FAIL = "SURVEY_CAMPAIGN_HEALTH_CHECK_STATUS_FAIL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyRecoverySlaStatus {
  SURVEY_RECOVERY_SLA_STATUS_UNSPECIFIED = "SURVEY_RECOVERY_SLA_STATUS_UNSPECIFIED",
  SURVEY_RECOVERY_SLA_STATUS_ON_TRACK = "SURVEY_RECOVERY_SLA_STATUS_ON_TRACK",
  SURVEY_RECOVERY_SLA_STATUS_DUE_SOON = "SURVEY_RECOVERY_SLA_STATUS_DUE_SOON",
  SURVEY_RECOVERY_SLA_STATUS_OVERDUE = "SURVEY_RECOVERY_SLA_STATUS_OVERDUE",
  SURVEY_RECOVERY_SLA_STATUS_CLOSED = "SURVEY_RECOVERY_SLA_STATUS_CLOSED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SurveyRecoveryNotificationStatus {
  SURVEY_RECOVERY_NOTIFICATION_STATUS_UNSPECIFIED = "SURVEY_RECOVERY_NOTIFICATION_STATUS_UNSPECIFIED",
  SURVEY_RECOVERY_NOTIFICATION_STATUS_PENDING = "SURVEY_RECOVERY_NOTIFICATION_STATUS_PENDING",
  SURVEY_RECOVERY_NOTIFICATION_STATUS_DELIVERED = "SURVEY_RECOVERY_NOTIFICATION_STATUS_DELIVERED",
  SURVEY_RECOVERY_NOTIFICATION_STATUS_FAILED = "SURVEY_RECOVERY_NOTIFICATION_STATUS_FAILED",
  SURVEY_RECOVERY_NOTIFICATION_STATUS_DEAD = "SURVEY_RECOVERY_NOTIFICATION_STATUS_DEAD",
  SURVEY_RECOVERY_NOTIFICATION_STATUS_SUPPRESSED = "SURVEY_RECOVERY_NOTIFICATION_STATUS_SUPPRESSED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface SurveyCampaign {
  id: string;
  name: string;
  surveyType: SurveyType;
  status: SurveyCampaignStatus;
  triggerEvent: SurveyTriggerEvent;
  distributionMode: SurveyDistributionMode;
  dedupePolicy: SurveyDedupePolicy;
  triggerFilter?: { [key: string]: any } | undefined;
  content?: { [key: string]: any } | undefined;
  locale: string;
  contentVersion: number;
  samplingPercent: number;
  minDaysBetweenContact: number;
  expiresAfterDays: number;
  maxDailyInvitations: number;
  lowScoreThreshold: number;
  requireRecentCustomerActivity: boolean;
  recentActivityDays: number;
  suppressAutoResolved: boolean;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string | undefined;
}

export interface ListSurveyCampaignsRequest {
  status: SurveyCampaignStatus;
  limit: number;
}

export interface ListSurveyCampaignsResponse {
  campaigns: SurveyCampaign[];
}

export interface CreateSurveyCampaignRequest {
  name: string;
  surveyType: SurveyType;
  status: SurveyCampaignStatus;
  triggerEvent: SurveyTriggerEvent;
  distributionMode: SurveyDistributionMode;
  dedupePolicy: SurveyDedupePolicy;
  triggerFilter?: { [key: string]: any } | undefined;
  content?: { [key: string]: any } | undefined;
  locale: string;
  samplingPercent?: number | undefined;
  minDaysBetweenContact?: number | undefined;
  expiresAfterDays?: number | undefined;
  maxDailyInvitations?: number | undefined;
  lowScoreThreshold?: number | undefined;
  requireRecentCustomerActivity?: boolean | undefined;
  recentActivityDays?: number | undefined;
  suppressAutoResolved?: boolean | undefined;
}

export interface UpdateSurveyCampaignRequest {
  id: string;
  name?: string | undefined;
  status: SurveyCampaignStatus;
  triggerEvent: SurveyTriggerEvent;
  distributionMode: SurveyDistributionMode;
  dedupePolicy: SurveyDedupePolicy;
  triggerFilter?: { [key: string]: any } | undefined;
  content?: { [key: string]: any } | undefined;
  locale?: string | undefined;
  samplingPercent?: number | undefined;
  minDaysBetweenContact?: number | undefined;
  expiresAfterDays?: number | undefined;
  maxDailyInvitations?: number | undefined;
  lowScoreThreshold?: number | undefined;
  requireRecentCustomerActivity?: boolean | undefined;
  recentActivityDays?: number | undefined;
  suppressAutoResolved?: boolean | undefined;
}

export interface ArchiveSurveyCampaignRequest {
  id: string;
}

export interface CreateSurveyHostedLinkRequest {
  campaignId: string;
  sourceType: string;
  sourceId: string;
  requestId?: string | undefined;
  context?: { [key: string]: any } | undefined;
}

export interface PreviewSurveyRecipientsRequest {
  campaignId: string;
  sourceType: string;
  sourceId: string;
  requestId?: string | undefined;
  context?: { [key: string]: any } | undefined;
  limit: number;
}

export interface PreviewSurveyRecipientsResponse {
  campaignId: string;
  triggerMatched: boolean;
  sampleIncluded: boolean;
  matchedCount: number;
  eligibleCount: number;
  suppressedCount: number;
  recipients: SurveyRecipientPreview[];
  suppressionReasonDistribution: SurveySuppressionReasonBucket[];
  deliveryReady: boolean;
  deliveryBlocker: string;
}

export interface SurveyRecipientPreview {
  sourceType: string;
  sourceId: string;
  requestId?: string | undefined;
  contactId?: string | undefined;
  channel: string;
  displayName: string;
  subjectDisplay: string;
  eligible: boolean;
  suppressionReason: string;
  recipientSnapshot?: { [key: string]: any } | undefined;
  lastActivityAt?: string | undefined;
}

export interface SendSurveyTestEmailRequest {
  campaignId: string;
  toEmail: string;
}

export interface SendSurveyTestEmailResponse {
  ok: boolean;
  provider: string;
  sentAt: string;
}

export interface GetSurveyCampaignHealthRequest {
  campaignId: string;
}

export interface SurveyCampaignHealth {
  campaignId: string;
  status: SurveyCampaignHealthStatus;
  readinessScore: number;
  funnel?: SurveyCampaignHealthFunnel | undefined;
  checks: SurveyCampaignHealthCheck[];
  suppressionReasonDistribution: SurveySuppressionReasonBucket[];
  generatedAt: string;
}

export interface SurveyCampaignHealthFunnel {
  invitationCount: number;
  pendingCount: number;
  delayedCount: number;
  deliveredCount: number;
  openedCount: number;
  completedCount: number;
  suppressedCount: number;
  expiredCount: number;
  rejectedCount: number;
  lowScoreCount: number;
  openLowScoreReviewCount: number;
  overdueLowScoreReviewCount: number;
  deliveryRate: number;
  openRate: number;
  responseRate: number;
  suppressionRate: number;
  expiredRate: number;
  recoveryOverdueRate: number;
}

export interface SurveyCampaignHealthCheck {
  id: string;
  status: SurveyCampaignHealthCheckStatus;
  title: string;
  summary: string;
  recommendedAction: string;
  evidence: string;
}

export interface RecordSurveyProviderEventRequest {
  invitationId?: string | undefined;
  provider: string;
  providerEventType: string;
  providerMessageId: string;
  providerEventKey: string;
  payload?: { [key: string]: any } | undefined;
  occurredAt?: string | undefined;
}

export interface SurveyInvitation {
  id: string;
  campaignId: string;
  requestId?: string | undefined;
  contactId?: string | undefined;
  sourceType: string;
  sourceId: string;
  distributionMode: SurveyDistributionMode;
  deliveryStatus: SurveyDeliveryStatus;
  responseStatus: SurveyResponseStatus;
  suppressionStatus: SurveySuppressionStatus;
  suppressionReason: string;
  campaignSnapshot?: { [key: string]: any } | undefined;
  recipientSnapshot?: { [key: string]: any } | undefined;
  publicUrl?: string | undefined;
  expiresAt?: string | undefined;
  deliveredAt?: string | undefined;
  openedAt?: string | undefined;
  respondedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deliveryRetryable: boolean;
}

export interface ListSurveyInvitationsRequest {
  campaignId?: string | undefined;
  responseStatus: SurveyResponseStatus;
  suppressionStatus: SurveySuppressionStatus;
  limit: number;
}

export interface ListSurveyInvitationsResponse {
  invitations: SurveyInvitation[];
}

export interface RetrySurveyInvitationDeliveryRequest {
  id: string;
}

export interface SurveyResponse {
  id: string;
  campaignId: string;
  invitationId: string;
  requestId?: string | undefined;
  contactId?: string | undefined;
  sourceType: string;
  sourceId: string;
  score: number;
  comment: string;
  locale: string;
  lowScore: boolean;
  submittedAt: string;
  lowScoreReview?: SurveyLowScoreReview | undefined;
  accountContext?: SurveyAccountContext | undefined;
}

/**
 * SurveyAccountContext normalizes account/company hints attached to a survey
 * invitation or response so recovery queues can be scoped by account.
 */
export interface SurveyAccountContext {
  accountKey: string;
  accountDisplay: string;
  source: string;
}

export interface ListSurveyResponsesRequest {
  campaignId?: string | undefined;
  lowScoreOnly?: boolean | undefined;
  from?: string | undefined;
  to?: string | undefined;
  limit: number;
  recoverySlaStatus?: SurveyRecoverySlaStatus | undefined;
  recoveryBlockerReason?: string | undefined;
  reviewSeverity?: SurveyLowScoreSeverity | undefined;
  ownerMemberId?: string | undefined;
  accountKey?: string | undefined;
}

export interface ListSurveyResponsesResponse {
  responses: SurveyResponse[];
}

export interface SurveyLowScoreReview {
  responseId: string;
  status: SurveyLowScoreReviewStatus;
  severity: SurveyLowScoreSeverity;
  ownerMemberId: string;
  rootCause: string;
  actionTaken: string;
  customerContacted: boolean;
  dueAt?: string | undefined;
  reviewedAt?: string | undefined;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  slaStatus: SurveyRecoverySlaStatus;
  blockerReason: string;
  nextBestAction: string;
  riskScore: number;
  recoveryNotificationStatus: SurveyRecoveryNotificationStatus;
  recoveryNotificationReason: string;
  recoveryNotificationDeliveredAt?: string | undefined;
  recoveryNotificationLastError: string;
}

export interface UpdateSurveyLowScoreReviewRequest {
  responseId: string;
  status: SurveyLowScoreReviewStatus;
  severity: SurveyLowScoreSeverity;
  ownerMemberId?: string | undefined;
  rootCause?: string | undefined;
  actionTaken?: string | undefined;
  customerContacted?: boolean | undefined;
  dueAt?: string | undefined;
}

export interface BatchUpdateSurveyLowScoreReviewsRequest {
  responseIds: string[];
  status: SurveyLowScoreReviewStatus;
  severity: SurveyLowScoreSeverity;
  ownerMemberId?: string | undefined;
  rootCause?: string | undefined;
  actionTaken?: string | undefined;
  customerContacted?: boolean | undefined;
  dueAt?: string | undefined;
}

export interface BatchUpdateSurveyLowScoreReviewsResponse {
  reviews: SurveyLowScoreReview[];
}

export interface AssignSurveyLowScoreReviewsRequest {
  responseIds: string[];
  candidateOwnerMemberIds: string[];
  dueInHours?: number | undefined;
}

export interface AssignSurveyLowScoreReviewsResponse {
  reviews: SurveyLowScoreReview[];
  decisions: SurveyRecoveryAssignmentDecision[];
}

export interface SurveyRecoveryAssignmentDecision {
  responseId: string;
  ownerMemberId: string;
  previousOwnerMemberId?: string | undefined;
  dueAt: string;
  severity: SurveyLowScoreSeverity;
  escalated: boolean;
  reason: string;
  workloadScoreBefore: number;
  workloadScoreAfter: number;
}

export interface EscalateSurveyLowScoreReviewsRequest {
  responseIds: string[];
  dueInHours?: number | undefined;
  note?: string | undefined;
}

export interface EscalateSurveyLowScoreReviewsResponse {
  reviews: SurveyLowScoreReview[];
  decisions: SurveyRecoveryEscalationDecision[];
}

export interface SurveyRecoveryEscalationDecision {
  responseId: string;
  previousSeverity: SurveyLowScoreSeverity;
  severity: SurveyLowScoreSeverity;
  previousDueAt?: string | undefined;
  dueAt: string;
  ownerMissing: boolean;
  dueAtChanged: boolean;
  reason: string;
  actionTaken: string;
}

export interface GetSurveyAnalyticsRequest {
  campaignId?: string | undefined;
  from?: string | undefined;
  to?: string | undefined;
}

export interface SurveyAnalytics {
  campaignId?: string | undefined;
  invitationCount: number;
  deliveredCount: number;
  suppressedCount: number;
  completedCount: number;
  lowScoreCount: number;
  averageScore: number;
  responseRate: number;
  scoreDistribution: SurveyScoreBucket[];
  suppressionReasonDistribution: SurveySuppressionReasonBucket[];
  averageResponseSeconds: number;
  positiveScoreCount: number;
  positiveScoreRate: number;
  openLowScoreReviewCount: number;
  overdueLowScoreReviewCount: number;
  notStartedCount: number;
  openedCount: number;
  expiredCount: number;
  unassignedLowScoreReviewCount: number;
  criticalLowScoreReviewCount: number;
  pendingCustomerContactReviewCount: number;
  oldestOpenLowScoreReviewDueAt?: string | undefined;
  overdueRecoveryQueueCount: number;
  unassignedRecoveryQueueCount: number;
  pendingContactRecoveryQueueCount: number;
  missingRootCauseRecoveryQueueCount: number;
  missingActionRecoveryQueueCount: number;
  ownerRecoveryLoads: SurveyRecoveryOwnerLoad[];
  pendingDeliveryCount: number;
  delayedDeliveryCount: number;
  rejectedDeliveryCount: number;
}

export interface SurveyRecoveryOwnerLoad {
  ownerMemberId: string;
  openCount: number;
  overdueCount: number;
  dueSoonCount: number;
  criticalCount: number;
  pendingContactCount: number;
  oldestOpenDueAt?: string | undefined;
  workloadScore: number;
}

export interface GetSurveyAnalyticsTrendRequest {
  campaignId?: string | undefined;
  from?: string | undefined;
  to?: string | undefined;
}

export interface GetSurveyAnalyticsTrendResponse {
  buckets: SurveyAnalyticsTrendBucket[];
}

export interface SurveyAnalyticsTrendBucket {
  date: string;
  invitationCount: number;
  deliveredCount: number;
  suppressedCount: number;
  completedCount: number;
  lowScoreCount: number;
  positiveScoreCount: number;
  averageScore: number;
  responseRate: number;
  notStartedCount: number;
  openedCount: number;
  expiredCount: number;
}

export interface GetSurveyAnalyticsSegmentsRequest {
  campaignId?: string | undefined;
  from?: string | undefined;
  to?: string | undefined;
  dimension: SurveyAnalyticsSegmentDimension;
  limit: number;
}

export interface GetSurveyAnalyticsSegmentsResponse {
  segments: SurveyAnalyticsSegment[];
}

export interface SurveyAnalyticsSegment {
  dimension: SurveyAnalyticsSegmentDimension;
  key: string;
  label: string;
  campaignId?: string | undefined;
  invitationCount: number;
  deliveredCount: number;
  suppressedCount: number;
  completedCount: number;
  lowScoreCount: number;
  positiveScoreCount: number;
  expiredCount: number;
  averageScore: number;
  responseRate: number;
  lowScoreRate: number;
  positiveScoreRate: number;
  suppressionRate: number;
  averageResponseSeconds: number;
  attentionScore: number;
}

export interface GetSurveyAnalyticsInsightsRequest {
  campaignId?: string | undefined;
  from?: string | undefined;
  to?: string | undefined;
  limit: number;
}

export interface GetSurveyAnalyticsInsightsResponse {
  insights: SurveyAnalyticsInsight[];
}

export interface SurveyAnalyticsInsight {
  id: string;
  severity: SurveyAnalyticsInsightSeverity;
  title: string;
  summary: string;
  metric: string;
  value: number;
  threshold: number;
  segmentKey?: string | undefined;
  segmentLabel?: string | undefined;
  segmentDimension: SurveyAnalyticsSegmentDimension;
  recommendedAction: string;
  rank: number;
}

export interface SurveyScoreBucket {
  score: number;
  count: number;
}

export interface SurveySuppressionReasonBucket {
  reason: string;
  count: number;
}

export interface PublicSurvey {
  campaignId: string;
  invitationId: string;
  surveyType: SurveyType;
  title: string;
  intro: string;
  question: string;
  commentPrompt: string;
  thankYou: string;
  locale: string;
  minScore: number;
  maxScore: number;
  expiresAt?: string | undefined;
  responseStatus: SurveyResponseStatus;
  unsubscribeUrl?: string | undefined;
}

export interface GetPublicSurveyRequest {
  token: string;
}

export interface SubmitPublicSurveyResponseRequest {
  token: string;
  score: number;
  comment: string;
  locale: string;
}

export interface PublicSurveyResponseReceipt {
  responseId: string;
  thankYou: string;
  lowScore: boolean;
}

export interface SurveyService {
  ListSurveyCampaigns(request: ListSurveyCampaignsRequest): Promise<ListSurveyCampaignsResponse>;
  CreateSurveyCampaign(request: CreateSurveyCampaignRequest): Promise<SurveyCampaign>;
  UpdateSurveyCampaign(request: UpdateSurveyCampaignRequest): Promise<SurveyCampaign>;
  ArchiveSurveyCampaign(request: ArchiveSurveyCampaignRequest): Promise<SurveyCampaign>;
  CreateSurveyHostedLink(request: CreateSurveyHostedLinkRequest): Promise<SurveyInvitation>;
  PreviewSurveyRecipients(request: PreviewSurveyRecipientsRequest): Promise<PreviewSurveyRecipientsResponse>;
  SendSurveyTestEmail(request: SendSurveyTestEmailRequest): Promise<SendSurveyTestEmailResponse>;
  GetSurveyCampaignHealth(request: GetSurveyCampaignHealthRequest): Promise<SurveyCampaignHealth>;
  RecordSurveyProviderEvent(request: RecordSurveyProviderEventRequest): Promise<SurveyInvitation>;
  ListSurveyInvitations(request: ListSurveyInvitationsRequest): Promise<ListSurveyInvitationsResponse>;
  RetrySurveyInvitationDelivery(request: RetrySurveyInvitationDeliveryRequest): Promise<SurveyInvitation>;
  ListSurveyResponses(request: ListSurveyResponsesRequest): Promise<ListSurveyResponsesResponse>;
  GetSurveyAnalytics(request: GetSurveyAnalyticsRequest): Promise<SurveyAnalytics>;
  GetSurveyAnalyticsTrend(request: GetSurveyAnalyticsTrendRequest): Promise<GetSurveyAnalyticsTrendResponse>;
  GetSurveyAnalyticsSegments(request: GetSurveyAnalyticsSegmentsRequest): Promise<GetSurveyAnalyticsSegmentsResponse>;
  GetSurveyAnalyticsInsights(request: GetSurveyAnalyticsInsightsRequest): Promise<GetSurveyAnalyticsInsightsResponse>;
  UpdateSurveyLowScoreReview(request: UpdateSurveyLowScoreReviewRequest): Promise<SurveyLowScoreReview>;
  BatchUpdateSurveyLowScoreReviews(
    request: BatchUpdateSurveyLowScoreReviewsRequest,
  ): Promise<BatchUpdateSurveyLowScoreReviewsResponse>;
  AssignSurveyLowScoreReviews(
    request: AssignSurveyLowScoreReviewsRequest,
  ): Promise<AssignSurveyLowScoreReviewsResponse>;
  EscalateSurveyLowScoreReviews(
    request: EscalateSurveyLowScoreReviewsRequest,
  ): Promise<EscalateSurveyLowScoreReviewsResponse>;
}

export interface PublicSurveyService {
  GetPublicSurvey(request: GetPublicSurveyRequest): Promise<PublicSurvey>;
  SubmitPublicSurveyResponse(request: SubmitPublicSurveyResponseRequest): Promise<PublicSurveyResponseReceipt>;
}
