// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/usage.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface GetUsageRequest {
  /** Reserved for future billing surfaces; currently ignored by the handler. */
  granularity: string;
  range: string;
}

export interface GetUsageResponse {
  /** RFC3339 period bounds (current calendar month, UTC). */
  periodStart: string;
  periodEnd: string;
  /** Total ingested rows in the period. (int64 → JSON string.) */
  total: string;
  /** Per-day buckets. */
  series: UsageBucket[];
  /** Plan quota; absent until billing lands. (int64 → JSON string.) */
  quota?: string | undefined;
}

export interface UsageBucket {
  /** RFC3339 day bucket (UTC). */
  bucket: string;
  /** Rows in the bucket. (int64 → JSON string.) */
  value: string;
}

/** UsageService serves the console usage dashboard. */
export interface UsageService {
  /** GET /fb/v1/console/usage — ingest volume for the current calendar month. */
  GetUsage(request: GetUsageRequest): Promise<GetUsageResponse>;
}
