// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/usage.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum UsageGranularity {
  USAGE_GRANULARITY_UNSPECIFIED = "USAGE_GRANULARITY_UNSPECIFIED",
  USAGE_GRANULARITY_DAY = "USAGE_GRANULARITY_DAY",
  USAGE_GRANULARITY_WEEK = "USAGE_GRANULARITY_WEEK",
  USAGE_GRANULARITY_MONTH = "USAGE_GRANULARITY_MONTH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface GetUsageRequest {
  /** Reserved for future billing surfaces; currently ignored by the handler. */
  granularity: string;
  range: string;
}

export interface GetUsageResponse {
  /** RFC3339 period bounds (current calendar month, UTC). */
  periodStart: string;
  periodEnd: string;
  /** Total ingested rows in the period. (int64 → JSON string.) */
  total: string;
  /** Per-day buckets. */
  series: UsageBucket[];
  /** Plan quota; absent until billing lands. (int64 → JSON string.) */
  quota?: string | undefined;
}

export interface UsageBucket {
  /** RFC3339 day bucket (UTC). */
  bucket: string;
  /** Rows in the bucket. (int64 → JSON string.) */
  value: string;
}

export interface GetLLMUsageRequest {
  /** day | week | month. Defaults to week. */
  granularity: UsageGranularity;
  /** Grafana-style from expression: now-7d | now-30d | now-90d | now/M. Defaults to now-30d. */
  range: string;
}

export interface GetLLMUsageResponse {
  periodStart: string;
  periodEnd: string;
  granularity: string;
  series: LLMUsageBucket[];
  /** JSON string */
  promptTokens: string;
  /** JSON string */
  completionTokens: string;
  costUsd: number;
  /** JSON string */
  calls: string;
  /** JSON string */
  errors: string;
}

export interface LLMUsageBucket {
  /** RFC3339 bucket boundary (UTC) */
  bucket: string;
  tenantId: string;
  modelId: string;
  /** JSON string */
  promptTokens: string;
  /** JSON string */
  completionTokens: string;
  costUsd: number;
  /** JSON string */
  calls: string;
  /** JSON string */
  errors: string;
}

/** UsageService serves the console usage dashboard. */
export interface UsageService {
  /** GET /fb/v1/console/usage — ingest volume for the current calendar month. */
  GetUsage(request: GetUsageRequest): Promise<GetUsageResponse>;
  /** GET /fb/v1/console/llm-usage — LLM token and cost usage. */
  GetLLMUsage(request: GetLLMUsageRequest): Promise<GetLLMUsageResponse>;
}
