// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/workflow.proto

/* eslint-disable */
import { type I18nString } from "./common";

export const protobufPackage = "attune.v1";

export interface WorkflowState {
  id: string;
  /**
   * Stable machine key (slug, ^[a-z][a-z0-9_]{0,30}$), immutable after
   * creation — mirrors Dimension.name. The SPA renders display_name.
   */
  name: string;
  color: string;
  category: string;
  position: number;
  isDefault: boolean;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  /** Per-locale display name; the SPA resolves, the backend never does. */
  displayName?: I18nString | undefined;
}

export interface WorkflowTransition {
  id: string;
  fromStateId: string;
  toStateId: string;
}

export interface ListStatesRequest {
  includeArchived: boolean;
}

export interface ListStatesResponse {
  states: WorkflowState[];
}

export interface CreateStateRequest {
  /** Stable machine key (slug); see WorkflowState.name. */
  name: string;
  color: string;
  category: string;
  position: number;
  displayName?: I18nString | undefined;
}

export interface CreateStateResponse {
  state?: WorkflowState | undefined;
}

export interface UpdateStateRequest {
  id: string;
  /**
   * Deprecated: the machine key (name) is immutable; send display_name to
   * relabel a state. Retained for wire compatibility; ignored by the server.
   */
  name?: string | undefined;
  color?: string | undefined;
  position?: number | undefined;
  isDefault?: boolean | undefined;
  displayName?: I18nString | undefined;
}

export interface UpdateStateResponse {
  state?: WorkflowState | undefined;
}

export interface ArchiveStateRequest {
  id: string;
}

export interface ArchiveStateResponse {
}

export interface ListTransitionsRequest {
}

export interface ListTransitionsResponse {
  transitions: WorkflowTransition[];
}

export interface ReplaceTransitionsRequest {
  transitions: WorkflowTransitionEdge[];
}

export interface WorkflowTransitionEdge {
  fromStateId: string;
  toStateId: string;
}

export interface ReplaceTransitionsResponse {
  transitions: WorkflowTransition[];
}

export interface TransitionFeedbackRequest {
  feedbackId: string;
  toStateId: string;
  comment: string;
}

export interface TransitionFeedbackResponse {
  feedbackId: string;
  fromState?: WorkflowState | undefined;
  toState?: WorkflowState | undefined;
}

export interface BatchTransitionFeedbackRequest {
  feedbackIds: string[];
  toStateId: string;
  comment: string;
}

export interface BatchTransitionFailure {
  feedbackId: string;
  code: string;
  message: string;
}

export interface BatchTransitionFeedbackResponse {
  succeeded: number;
  failed: BatchTransitionFailure[];
}

export interface AuditEntry {
  id: string;
  feedbackId: string;
  entityType: string;
  fieldName: string;
  oldValue: string;
  newValue: string;
  comment: string;
  changedBy: string;
  createdAt: string;
}

export interface ListAuditRequest {
  feedbackId: string;
  cursor?: string | undefined;
  limit?: number | undefined;
}

export interface ListAuditResponse {
  entries: AuditEntry[];
  nextCursor?: string | undefined;
}

export interface SeedDefaultsRequest {
}

export interface SeedDefaultsResponse {
}

export interface WorkflowService {
  ListStates(request: ListStatesRequest): Promise<ListStatesResponse>;
  CreateState(request: CreateStateRequest): Promise<CreateStateResponse>;
  UpdateState(request: UpdateStateRequest): Promise<UpdateStateResponse>;
  ArchiveState(request: ArchiveStateRequest): Promise<ArchiveStateResponse>;
  ListTransitions(request: ListTransitionsRequest): Promise<ListTransitionsResponse>;
  ReplaceTransitions(request: ReplaceTransitionsRequest): Promise<ReplaceTransitionsResponse>;
  SeedDefaults(request: SeedDefaultsRequest): Promise<SeedDefaultsResponse>;
  TransitionFeedback(request: TransitionFeedbackRequest): Promise<TransitionFeedbackResponse>;
  BatchTransitionFeedback(request: BatchTransitionFeedbackRequest): Promise<BatchTransitionFeedbackResponse>;
  ListAudit(request: ListAuditRequest): Promise<ListAuditResponse>;
}
