// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: attune/v1/common.proto

package attunev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponse is the JSON body returned on any 4xx/5xx across attune's HTTP
// APIs — a stable machine-readable `code`, a human-facing `message`, and the
// request id for support/tracing:
//
//	{"code":"validation","message":"content is required","requestId":"abc123"}
//
// One envelope for the public ingest API and the console alike.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable error code, e.g. unauthorized / bad_request / validation /
	// not_found / conflict / internal. Safe for clients to switch on.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-facing message. Not stable; do not switch on it.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The request id (chi X-Request-ID) for support / log correlation.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_attune_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attune_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_attune_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// I18nString is attune's per-locale display map (E3 metadata-driven
// Dimensions, proposal 2026-06-07-flat-labels.md). Keys are BCP 47
// locale tags ("zh", "en", "ja", "zh-Hant", ...) plus the reserved
// "default" key used as the universal fallback. Resolution chain
// (handled in the console SPA): preferred locale list → "default" →
// any non-empty entry. The backend never resolves — it returns the
// full map so the same payload serves every caller.
type I18NString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I18NString) Reset() {
	*x = I18NString{}
	mi := &file_attune_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I18NString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NString) ProtoMessage() {}

func (x *I18NString) ProtoReflect() protoreflect.Message {
	mi := &file_attune_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NString.ProtoReflect.Descriptor instead.
func (*I18NString) Descriptor() ([]byte, []int) {
	return file_attune_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *I18NString) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Taxonomy is one allowed value for a Dimension. `value` is the
// stable machine identifier the LLM emits and SQL filters use;
// `display_name` is the i18n surface the console renders and the
// operator freely edits without affecting persisted data or wire
// contracts.
type Taxonomy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	DisplayName   *I18NString            `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taxonomy) Reset() {
	*x = Taxonomy{}
	mi := &file_attune_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taxonomy) ProtoMessage() {}

func (x *Taxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_attune_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taxonomy.ProtoReflect.Descriptor instead.
func (*Taxonomy) Descriptor() ([]byte, []int) {
	return file_attune_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Taxonomy) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Taxonomy) GetDisplayName() *I18NString {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

// Dimension is one enrichment axis the LLM populates for each row.
// Per-tenant DimensionSet is open in count and closed in shape —
// adding any new dim is a Settings edit, not a code change.
type Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable machine key: ^[a-z][a-z0-9_]{0,30}$. Immutable after
	// creation; rename = delete + recreate.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Per-locale display surface for the dim itself.
	DisplayName *I18NString `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// "single" — LLM picks one value (or none if !required).
	// "multi"  — LLM picks 0..N values.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Allowed values; empty + kind=multi = freeform (GitHub-labels style).
	Taxonomy []*Taxonomy `protobuf:"bytes,4,rep,name=taxonomy,proto3" json:"taxonomy,omitempty"`
	// Subset of taxonomy.value whose presence on a row flips is_urgent.
	UrgentSet []string `protobuf:"bytes,5,rep,name=urgent_set,json=urgentSet,proto3" json:"urgent_set,omitempty"`
	// When true, the LLM's JSON schema marks this property required.
	Required      bool `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_attune_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_attune_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_attune_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Dimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dimension) GetDisplayName() *I18NString {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *Dimension) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Dimension) GetTaxonomy() []*Taxonomy {
	if x != nil {
		return x.Taxonomy
	}
	return nil
}

func (x *Dimension) GetUrgentSet() []string {
	if x != nil {
		return x.UrgentSet
	}
	return nil
}

func (x *Dimension) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_attune_v1_common_proto protoreflect.FileDescriptor

var file_attune_v1_common_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x5c, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x49, 0x31, 0x38, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x3c, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x31,
	0x38, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x3a,
	0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x08, 0x54, 0x61,
	0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x0c,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x31, 0x38, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x31, 0x38, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f,
	0x6d, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x52, 0x08, 0x74,
	0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x72, 0x67, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75, 0x72, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x42, 0x9f, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e,
	0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x50, 0x68, 0x69, 0x78, 0x73, 0x75, 0x72, 0x61, 0x2f, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x74, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x15, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_attune_v1_common_proto_rawDescOnce sync.Once
	file_attune_v1_common_proto_rawDescData []byte
)

func file_attune_v1_common_proto_rawDescGZIP() []byte {
	file_attune_v1_common_proto_rawDescOnce.Do(func() {
		file_attune_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attune_v1_common_proto_rawDesc), len(file_attune_v1_common_proto_rawDesc)))
	})
	return file_attune_v1_common_proto_rawDescData
}

var file_attune_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_attune_v1_common_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: attune.v1.ErrorResponse
	(*I18NString)(nil),    // 1: attune.v1.I18nString
	(*Taxonomy)(nil),      // 2: attune.v1.Taxonomy
	(*Dimension)(nil),     // 3: attune.v1.Dimension
	nil,                   // 4: attune.v1.I18nString.EntriesEntry
}
var file_attune_v1_common_proto_depIdxs = []int32{
	4, // 0: attune.v1.I18nString.entries:type_name -> attune.v1.I18nString.EntriesEntry
	1, // 1: attune.v1.Taxonomy.display_name:type_name -> attune.v1.I18nString
	1, // 2: attune.v1.Dimension.display_name:type_name -> attune.v1.I18nString
	2, // 3: attune.v1.Dimension.taxonomy:type_name -> attune.v1.Taxonomy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_attune_v1_common_proto_init() }
func file_attune_v1_common_proto_init() {
	if File_attune_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attune_v1_common_proto_rawDesc), len(file_attune_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attune_v1_common_proto_goTypes,
		DependencyIndexes: file_attune_v1_common_proto_depIdxs,
		MessageInfos:      file_attune_v1_common_proto_msgTypes,
	}.Build()
	File_attune_v1_common_proto = out.File
	file_attune_v1_common_proto_goTypes = nil
	file_attune_v1_common_proto_depIdxs = nil
}
