// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: attune/v1/common.proto

package attunev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponse is the JSON body returned on any 4xx/5xx across attune's HTTP
// APIs — a stable machine-readable `code`, a human-facing `message`, and the
// request id for support/tracing:
//
//	{"code":"validation","message":"content is required","requestId":"abc123"}
//
// One envelope for the public ingest API and the console alike.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable error code, e.g. unauthorized / bad_request / validation /
	// not_found / conflict / internal. Safe for clients to switch on.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-facing message. Not stable; do not switch on it.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The request id (chi X-Request-ID) for support / log correlation.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_attune_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attune_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_attune_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_attune_v1_common_proto protoreflect.FileDescriptor

var file_attune_v1_common_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x5c, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x42, 0x9f, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65,
	0x2e, 0x76, 0x31, 0x42, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50,
	0x68, 0x69, 0x78, 0x73, 0x75, 0x72, 0x61, 0x2f, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74,
	0x74, 0x75, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x09, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x15, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x41, 0x74, 0x74, 0x75, 0x6e, 0x65, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_attune_v1_common_proto_rawDescOnce sync.Once
	file_attune_v1_common_proto_rawDescData []byte
)

func file_attune_v1_common_proto_rawDescGZIP() []byte {
	file_attune_v1_common_proto_rawDescOnce.Do(func() {
		file_attune_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attune_v1_common_proto_rawDesc), len(file_attune_v1_common_proto_rawDesc)))
	})
	return file_attune_v1_common_proto_rawDescData
}

var file_attune_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_attune_v1_common_proto_goTypes = []any{
	(*ErrorResponse)(nil), // 0: attune.v1.ErrorResponse
}
var file_attune_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attune_v1_common_proto_init() }
func file_attune_v1_common_proto_init() {
	if File_attune_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attune_v1_common_proto_rawDesc), len(file_attune_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attune_v1_common_proto_goTypes,
		DependencyIndexes: file_attune_v1_common_proto_depIdxs,
		MessageInfos:      file_attune_v1_common_proto_msgTypes,
	}.Build()
	File_attune_v1_common_proto = out.File
	file_attune_v1_common_proto_goTypes = nil
	file_attune_v1_common_proto_depIdxs = nil
}
