package main

import "github.com/Phixsura/attune/internal/pkg/ptrext"

type dashboard struct {
	UID         string         `json:"uid"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Tags        []string       `json:"tags"`
	Timezone    string         `json:"timezone"`
	Schema      int            `json:"schemaVersion"`
	Version     int            `json:"version"`
	Refresh     string         `json:"refresh"`
	Time        map[string]any `json:"time"`
	Templating  map[string]any `json:"templating"`
	Links       []link         `json:"links,omitempty"`
	Panels      []panel        `json:"panels"`
	Filename    string         `json:"-"`
}

type link struct {
	Title       string `json:"title"`
	Type        string `json:"type"`
	UID         string `json:"uid"`
	IncludeVars bool   `json:"includeVars"`
	KeepTime    bool   `json:"keepTime"`
}

type panel struct {
	ID          int            `json:"id"`
	Type        string         `json:"type"`
	Title       string         `json:"title"`
	Description string         `json:"description,omitempty"`
	GridPos     gridPos        `json:"gridPos"`
	Targets     []target       `json:"targets,omitempty"`
	FieldConfig map[string]any `json:"fieldConfig,omitempty"`
	Options     map[string]any `json:"options,omitempty"`
}

type target struct {
	Expr         string `json:"expr"`
	Legend       string `json:"legendFormat,omitempty"`
	RefID        string `json:"refId"`
	Instant      bool   `json:"instant,omitempty"`
	Range        bool   `json:"range,omitempty"`
	Format       string `json:"format,omitempty"`
	EditorMode   string `json:"editorMode,omitempty"`
	Exemplar     bool   `json:"exemplar,omitempty"`
	Interval     string `json:"interval,omitempty"`
	IntervalFact int    `json:"intervalFactor,omitempty"`
}

type gridPos struct {
	H int `json:"h"`
	W int `json:"w"`
	X int `json:"x"`
	Y int `json:"y"`
}

type queryVar struct {
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Datasource any            `json:"datasource"`
	Query      string         `json:"query"`
	Refresh    int            `json:"refresh"`
	IncludeAll bool           `json:"includeAll"`
	Multi      bool           `json:"multi"`
	AllValue   string         `json:"allValue,omitempty"`
	Current    map[string]any `json:"current"`
}

const generatedDescription = "Generated by go run ./internal/tools/observabilitydash. Do not edit JSON by hand."

func newDashboard(uid, title, filename string, tags []string, vars ...queryVar) dashboard {
	return dashboard{
		UID:         uid,
		Title:       title,
		Description: generatedDescription,
		Tags:        append([]string{"attune"}, tags...),
		Timezone:    "browser",
		Schema:      39,
		Version:     1,
		Refresh:     "1m",
		Time:        map[string]any{"from": "now-6h", "to": "now"},
		Templating:  map[string]any{"list": vars},
		Filename:    filename,
	}
}

func tenantVar(metric string) queryVar {
	return queryVar{
		Name:       "tenant",
		Type:       "query",
		Datasource: nil,
		Query:      "label_values(" + metric + ", tenant)",
		Refresh:    1,
		IncludeAll: true,
		Multi:      true,
		AllValue:   ".*",
		Current:    map[string]any{"selected": true, "text": "All", "value": "$__all"},
	}
}

func labelVar(name, metric, label string) queryVar {
	return queryVar{
		Name:       name,
		Type:       "query",
		Datasource: nil,
		Query:      "label_values(" + metric + ", " + label + ")",
		Refresh:    1,
		IncludeAll: true,
		Multi:      true,
		AllValue:   ".*",
		Current:    map[string]any{"selected": true, "text": "All", "value": "$__all"},
	}
}

func targetExpr(ref, expr, legend string) target {
	return target{Expr: zero(expr), Legend: legend, RefID: ref}
}

func targetExprSparse(ref, expr, legend string) target {
	return target{Expr: expr, Legend: legend, RefID: ref}
}

func statDesc(id int, title, desc, expr, unit string, pos gridPos, thresholds []threshold) panel {
	return panel{
		ID:          id,
		Type:        "stat",
		Title:       title,
		Description: desc,
		GridPos:     pos,
		Targets:     []target{targetExpr("A", expr, title)},
		FieldConfig: statField(title, unit, thresholds...),
		Options: map[string]any{
			"colorMode":   "value",
			"graphMode":   "none",
			"justifyMode": "center",
			"reduceOptions": map[string]any{
				"calcs":  []string{"lastNotNull"},
				"fields": "",
				"values": false,
			},
			"textMode":   "value",
			"wideLayout": true,
		},
	}
}

func seriesDesc(id int, title, desc string, targets []target, unit string, pos gridPos) panel {
	p := panel{
		ID:          id,
		Type:        "timeseries",
		Title:       title,
		Description: desc,
		GridPos:     pos,
		Targets:     targets,
		FieldConfig: field(unit),
		Options:     legendOptions(),
	}
	applyDefaultAxis(p.FieldConfig, unit)
	return p
}

func seriesDescAxis(id int, title, desc string, targets []target, unit string, pos gridPos, softMax float64) panel {
	p := seriesDesc(id, title, desc, targets, unit, pos)
	p.FieldConfig["defaults"].(map[string]any)["custom"].(map[string]any)["axisSoftMin"] = 0
	p.FieldConfig["defaults"].(map[string]any)["custom"].(map[string]any)["axisSoftMax"] = softMax
	return p
}

func applyDefaultAxis(config map[string]any, unit string) {
	defaults := config["defaults"].(map[string]any)
	custom := defaults["custom"].(map[string]any)
	custom["axisSoftMin"] = 0
	switch unit {
	case "reqps":
		custom["axisSoftMax"] = 1
	case "s":
		custom["axisSoftMax"] = 2
	case "short":
		custom["axisSoftMax"] = 1
	case "bytes":
		custom["axisSoftMax"] = 1024
	case "currencyUSD":
		custom["axisSoftMax"] = 1
	}
}

func barDesc(id int, title, desc string, targets []target, unit string, pos gridPos) panel {
	return panel{
		ID:          id,
		Type:        "barchart",
		Title:       title,
		Description: desc,
		GridPos:     pos,
		Targets:     targets,
		FieldConfig: field(unit),
		Options:     map[string]any{"orientation": "horizontal", "legend": legendTable()},
	}
}

func textPanel(id int, title, desc, content string, pos gridPos) panel {
	return panel{
		ID:          id,
		Type:        "text",
		Title:       title,
		Description: desc,
		GridPos:     pos,
		Options: map[string]any{
			"mode":    "markdown",
			"content": content,
		},
	}
}

func rowPanel(id int, title string, y int) panel {
	return panel{
		ID:      id,
		Type:    "row",
		Title:   title,
		GridPos: gp(0, y, 24, 1),
	}
}

func shiftPanels(dy int, panels ...panel) []panel {
	shifted := make([]panel, 0, len(panels))
	for _, p := range panels {
		p.GridPos.Y += dy
		shifted = append(shifted, p)
	}
	return shifted
}

type threshold struct {
	Color string
	Value *float64
}

func field(unit string, thresholds ...threshold) map[string]any {
	defaults := map[string]any{
		"custom": map[string]any{
			"drawStyle":         "line",
			"lineInterpolation": "smooth",
			"fillOpacity":       10,
			"lineWidth":         2,
			"showPoints":        "never",
			"spanNulls":         true,
		},
		"noValue": "0",
	}
	if unit != "" {
		defaults["unit"] = unit
	}
	if len(thresholds) > 0 {
		steps := make([]map[string]any, 0, len(thresholds))
		for _, step := range thresholds {
			raw := map[string]any{"color": step.Color}
			if step.Value != nil {
				raw["value"] = ptrext.Indirect(step.Value)
			} else {
				raw["value"] = nil
			}
			steps = append(steps, raw)
		}
		defaults["thresholds"] = map[string]any{"mode": "absolute", "steps": steps}
	}
	return map[string]any{"defaults": defaults}
}

func statField(displayName, unit string, thresholds ...threshold) map[string]any {
	cfg := field(unit, thresholds...)
	defaults := cfg["defaults"].(map[string]any)
	defaults["displayName"] = displayName
	return cfg
}

func legendOptions() map[string]any {
	return map[string]any{"legend": legendTable(), "tooltip": map[string]any{"mode": "multi", "sort": "none"}}
}

func legendTable() map[string]any {
	return map[string]any{"displayMode": "table", "placement": "bottom"}
}

func gp(x, y, w, h int) gridPos {
	return gridPos{X: x, Y: y, W: w, H: h}
}

func zero(expr string) string {
	return "(" + expr + ") or vector(0)"
}

func fp(v float64) *float64 {
	return ptrext.Of(v)
}

func greenWarnRed(warn, crit float64) []threshold {
	return []threshold{
		{Color: "green"},
		{Color: "orange", Value: fp(warn)},
		{Color: "red", Value: fp(crit)},
	}
}

func redWarnGreen(warn, good float64) []threshold {
	return []threshold{
		{Color: "red"},
		{Color: "orange", Value: fp(warn)},
		{Color: "green", Value: fp(good)},
	}
}

func greenRed(crit float64) []threshold {
	return []threshold{
		{Color: "green"},
		{Color: "red", Value: fp(crit)},
	}
}
