package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Phixsura/attune/internal/pkg/ptrext"
)

const reliabilityCatalogTSPath = "console/src/features/reliability/reliability-catalog.ts"

func writeReliabilityCatalog() error {
	body, err := renderReliabilityCatalogTS(reliabilityCatalog())
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(reliabilityCatalogTSPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(reliabilityCatalogTSPath, body, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", reliabilityCatalogTSPath, err)
	}
	return nil
}

func renderReliabilityCatalogTS(entries []reliabilitySLO) ([]byte, error) {
	b := ptrext.Of(strings.Builder{})
	b.WriteString("// Code generated by go run ./internal/tools/observabilitydash. Do not edit by hand.\n")
	b.WriteString("\n")
	b.WriteString("export type ReliabilityScope = 'tenant' | 'global' | 'destination_type'\n")
	b.WriteString("export type ReliabilityBurnKind = 'error' | 'success'\n")
	b.WriteString("\n")
	b.WriteString("export interface ReliabilityCatalogEntry {\n")
	b.WriteString("  key: string\n")
	b.WriteString("  alertName: string\n")
	b.WriteString("  title: string\n")
	b.WriteString("  owner: string\n")
	b.WriteString("  escalation: string\n")
	b.WriteString("  scope: ReliabilityScope\n")
	b.WriteString("  alertLabel: string\n")
	b.WriteString("  objective: number\n")
	b.WriteString("  burnKind: ReliabilityBurnKind\n")
	b.WriteString("  recordedRatioBase: string\n")
	b.WriteString("  overviewDescription: string\n")
	b.WriteString("  budgetExceptionPolicy: string\n")
	b.WriteString("  budgetExceptionNote: string\n")
	b.WriteString("  policySummary: string\n")
	b.WriteString("  policyNote: string\n")
	b.WriteString("  trendLegendBase: string\n")
	b.WriteString("  tenantRankLegendBase?: string\n")
	b.WriteString("  includeInTenantRank: boolean\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export const reliabilityCatalog = [\n")
	for _, slo := range entries {
		renderReliabilityCatalogEntry(b, slo)
	}
	b.WriteString("] as const satisfies readonly ReliabilityCatalogEntry[]\n")
	b.WriteString("\n")
	b.WriteString("export type ReliabilityCatalogEntryValue = (typeof reliabilityCatalog)[number]\n")
	return []byte(b.String()), nil
}

func renderReliabilityCatalogEntry(b *strings.Builder, slo reliabilitySLO) {
	b.WriteString("  {\n")
	writeTSField(b, 4, "key", tsString(slo.Key))
	writeTSField(b, 4, "alertName", tsString(slo.AlertName))
	writeTSField(b, 4, "title", tsString(slo.Title))
	writeTSField(b, 4, "owner", tsString(slo.Owner))
	writeTSField(b, 4, "escalation", tsString(slo.Escalation))
	writeTSField(b, 4, "scope", tsString(string(slo.Scope)))
	writeTSField(b, 4, "alertLabel", tsString(slo.AlertLabel))
	writeTSField(b, 4, "objective", tsNumber(slo.Objective))
	writeTSField(b, 4, "burnKind", tsString(string(slo.BurnKind)))
	writeTSField(b, 4, "recordedRatioBase", tsString(slo.RecordedRatioBase))
	writeTSField(b, 4, "overviewDescription", tsString(slo.OverviewDescription))
	writeTSField(b, 4, "budgetExceptionPolicy", tsString(reliabilityBudgetExceptionPolicy(slo)))
	writeTSField(b, 4, "budgetExceptionNote", tsString(reliabilityBudgetExceptionNote(slo)))
	writeTSField(b, 4, "policySummary", tsString(reliabilityPolicySummary(slo)))
	writeTSField(b, 4, "policyNote", tsString(reliabilityPolicyNote(slo)))
	writeTSField(b, 4, "trendLegendBase", tsString(slo.TrendLegendBase))
	if slo.TenantRankLegendBase != "" {
		writeTSField(b, 4, "tenantRankLegendBase", tsString(slo.TenantRankLegendBase))
	}
	writeTSField(b, 4, "includeInTenantRank", tsBool(slo.IncludeInTenantRank))
	b.WriteString("  },\n")
}

func writeTSField(b *strings.Builder, indent int, name, value string) {
	prefix := strings.Repeat(" ", indent) + name + ": "
	if shouldWrapTSField(prefix, value) {
		b.WriteString(strings.Repeat(" ", indent))
		b.WriteString(name)
		b.WriteString(":\n")
		b.WriteString(strings.Repeat(" ", indent+2))
		b.WriteString(value)
		b.WriteString(",\n")
		return
	}

	b.WriteString(prefix)
	b.WriteString(value)
	b.WriteString(",\n")
}

func shouldWrapTSField(prefix, value string) bool {
	if !strings.HasPrefix(value, "'") || !strings.HasSuffix(value, "'") {
		return false
	}
	return len(prefix)+len(value)+1 > 100
}

func tsString(v string) string {
	escaped := strings.ReplaceAll(v, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `'`, `\'`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	return "'" + escaped + "'"
}

func tsBool(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func tsNumber(v float64) string {
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%g", v), "0"), ".")
}
