/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fb/v1/console/install/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 跳转飞书 OAuth 授权
         * @description 302 → 飞书授权页。state 参数防 CSRF。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 授权完成后跳回的 console 相对路径，默认 `/` */
                    redirect_uri?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重定向至飞书授权页 */
                302: {
                    headers: {
                        Location?: string;
                        /** @description 短期 oauth_state cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/install/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 飞书 OAuth 回调
         * @description 飞书 redirects here 携带 `code` 与 `state`。
         *     服务端用 code 换 user_access_token，取 tenant_key + user info，
         *     upsert tenants 行，签 session cookie，302 回 `/console`。
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 登录成功，重定向到 console 主页 */
                302: {
                    headers: {
                        /** @description attune_session（HttpOnly, Secure, SameSite=Lax） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前会话
         * @description SPA boot 时调用判断登录态。无 session → 401。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前 tenant + user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionMe"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 清 session cookie。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                204: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 反馈列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 分页游标（来自上次响应的 next_cursor） */
                    cursor?: string;
                    limit?: number;
                    /** @description 按 enriched_kind 过滤（与 domain/feedback.go ValidKinds 同步） */
                    kind?: "bug" | "feature" | "ops" | "question" | "other";
                    severity?: "P0" | "P1" | "P2" | "P3";
                    /** @description 渠道，如 api / lark / sdk */
                    source?: string;
                    /** @description 全文搜索（content + enriched_title） */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 反馈分页 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Feedback"][];
                            next_cursor?: string | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/feedback/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 反馈分布统计（当前月）
         * @description 本月按 enriched_kind 的计数分布，给控制台首页 donut 用。
         *     Phase 1.5 Layer 2 — 客户登进来不需要点列表也能一眼看
         *     本月反馈结构。范围固定本月（UTC 切日）；未来按需扩 query。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当月分布 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            period_start: string;
                            /** Format: date-time */
                            period_end: string;
                            /** Format: int64 */
                            total: number;
                            /**
                             * @description Map of enriched_kind → count. Keys mirror
                             *     domain.ValidKinds (bug/feature/ops/question/other).
                             *     Unenriched rows are bucketed into "unknown".
                             */
                            by_kind: {
                                [key: string]: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/feedback/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 反馈详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 详情（含附件、enrich 全量字段） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/notify-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前 tenant 的所有通知目标 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 通知目标列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["NotifyTarget"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * 新建一个通知目标
         * @description 受 DB UNIQUE (tenant_id, destination_type, audience) 约束——
         *     同一 (type, audience) 组合已存在时 409 Conflict。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotifyTargetCreate"];
                };
            };
            responses: {
                /** @description 新建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotifyTarget"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
                /** @description destination_type 尚未实现（slack-bot / email） */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/notify-targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除单条通知目标 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /**
         * 修改单条通知目标（sparse）
         * @description 部分更新：仅传入要改的字段。destination_type 不可改（要换类型
         *     请删旧建新——身份变了）。改 audience 命中 UNIQUE (tenant_id,
         *     destination_type, audience) 时 409。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotifyTargetPatch"];
                };
            };
            responses: {
                /** @description 更新后的 target */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotifyTarget"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/fb/v1/console/notify-targets/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 测试通知目标连通性
         * @description 服务端构造一条合成事件 `{event:"test", ts:<unix>, tenant:<slug>}`，
         *     按目标 destination_type 发出去。客户端用这个验证 webhook URL +
         *     HMAC secret + 飞书 chat_id 配对的真实可达性，不必等真反馈。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 目标返回 2xx */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            status_code?: number;
                            latency_ms: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description 目标返回非 2xx 或连接失败 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"] & {
                            status_code?: number | null;
                            latency_ms?: number | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列 API key（仅返回元数据，不返回明文） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API key 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ApiKey"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 铸新 key（明文 secret 仅此一次返回）
         * @description 明文 key 仅本响应里出现，之后只能查到 prefix。
         *     客户必须当场保存——丢失只能撤销重铸。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 用途备注，如 "prod-app" / "dev-test" */
                        label: string;
                    };
                };
            };
            responses: {
                /** @description 新建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewApiKey"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销 key（软删，留审计记录） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已撤销 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fb/v1/console/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用量看板数据
         * @description 返回当前计费周期（自然月）+ 上一周期的 ingest 计数。
         *     Stage B 仅 ingest 维度；M5 看板上线后扩 enrich / notify。
         */
        get: {
            parameters: {
                query?: {
                    granularity?: "hour" | "day";
                    range?: "current_period" | "last_period" | "last_7d" | "last_30d";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 用量序列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Tenant: {
            /** @description UUID (TEXT 列) */
            id: string;
            slug: string;
            name: string;
            lark_tenant_key?: string | null;
            /** @description BCP 47，例如 zh-CN / en-US。enrich 摘要与 digest 据此渲染。 */
            locale: string;
            /** @description IANA tz，例如 Asia/Shanghai / America/Los_Angeles。 */
            timezone: string;
        };
        SessionUser: {
            open_id: string;
            name: string;
            /** Format: uri */
            avatar_url?: string | null;
            /**
             * @description Stage B 不强制 RBAC，但字段已下发供前端隐藏管理项。
             * @enum {string}
             */
            role: "admin" | "member";
        };
        SessionMe: {
            tenant: components["schemas"]["Tenant"];
            user: components["schemas"]["SessionUser"];
            /**
             * @description 轮转策略：在 session 生命周期内固定不变；session 失效
             *     （含主动 logout）后下次 /me 返回新值。客户端把它放在
             *     内存里，每次非 GET 请求带 `X-CSRF-Token` header。
             *     不要把 token 写回 cookie——它必须是 JS 可读但非
             *     HttpOnly cookie 自动发送的，才能验证 origin。
             */
            csrf_token: string;
        };
        Feedback: {
            /** Format: int64 */
            id: number;
            content: string;
            source: string;
            type?: string;
            user_id?: string;
            page_url?: string;
            enriched_title?: string | null;
            /**
             * @description 与 domain/feedback.go ValidKinds 同步
             * @enum {string|null}
             */
            enriched_kind?: "bug" | "feature" | "ops" | "question" | "other" | null;
            /** @enum {string|null} */
            enriched_severity?: "P0" | "P1" | "P2" | "P3" | null;
            enriched_modules?: string[] | null;
            enriched_priority?: number | null;
            /** @enum {string} */
            enrichment_status: "pending" | "enriching" | "done" | "failed";
            /** Format: date-time */
            created_at: string;
        };
        FeedbackDetail: components["schemas"]["Feedback"] & {
            source_meta?: {
                [key: string]: unknown;
            };
            attachments?: {
                /** Format: uri */
                url: string;
                mime?: string;
                size?: number;
            }[];
            enrichment_error?: string | null;
            /** Format: date-time */
            enriched_at?: string | null;
        };
        NotifyTarget: {
            /** Format: uuid */
            id: string;
            /**
             * @description **Stage B 仅 `lark-bot` 与 `raw-webhook` 已实现**；
             *     slack-bot / email 在 DB CHECK 约束里预留，POST 时后端返回
             *     501 直到 adapter 实现（Wave 3+）。
             * @enum {string}
             */
            destination_type: "lark-bot" | "raw-webhook" | "slack-bot" | "email";
            /**
             * @description pool=全量反馈池；radar=高优先级雷达;all=两者皆送
             * @enum {string}
             */
            audience: "pool" | "radar" | "all";
            /**
             * Format: uri
             * @description 目的地 URL。两类 destination_type 都用同一字段：
             *       - lark-bot：飞书群「自定义机器人」的 Webhook URL
             *         (https://open.feishu.cn/open-apis/bot/v2/hook/...)
             *       - raw-webhook：任意 HTTPS endpoint（loopback 仅开发）
             */
            url: string;
            timeout_seconds?: number;
            disabled: boolean;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Phase 3.2 · 最近一次 markDead 的时间。当前失败状态指示器，
             *     而非历史日志（成功投递时清除）。非 nil = 该目标当前处于
             *     告警状态——前端应显示徽标。
             */
            last_failure_at?: string | null;
            /**
             * @description Phase 3.2 · 与 last_failure_at 配对的失败原因（截断 1000 字符）。
             *     last_failure_at 为 null 时该字段为空字符串。
             */
            last_error?: string;
        };
        NotifyTargetCreate: {
            /** @enum {string} */
            destination_type: "lark-bot" | "raw-webhook" | "slack-bot" | "email";
            /**
             * @default all
             * @enum {string}
             */
            audience: "pool" | "radar" | "all";
            /**
             * Format: uri
             * @description lark-bot：飞书群机器人 Webhook URL。
             *     raw-webhook：HTTPS 接收端 URL。
             */
            url: string;
            /**
             * @description HMAC 签名 secret。
             *     - lark-bot：飞书群机器人「签名校验」开启后填那个字符串
             *     - raw-webhook：自定义 32+ 字节随机串
             *     空字符串 = 不签名（仅 lark-bot 关签名校验时可用）
             */
            secret?: string;
            /** @default 10 */
            timeout_seconds: number;
            /** @default false */
            disabled: boolean;
        };
        /**
         * @description Sparse update — only fields present in the request body are
         *     applied. `destination_type` is intentionally omitted (changing
         *     type = different identity; delete + recreate instead).
         *     Empty `secret` string is treated as "clear the secret"; omit
         *     the key entirely to leave it unchanged.
         */
        NotifyTargetPatch: {
            /** @enum {string} */
            audience?: "pool" | "radar" | "all";
            /** Format: uri */
            url?: string;
            secret?: string;
            timeout_seconds?: number;
            disabled?: boolean;
        };
        ApiKey: {
            /** Format: uuid */
            id: string;
            /** @description 前缀 + ... + 后 4 位，用于客户辨识 */
            key_prefix: string;
            label: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        NewApiKey: components["schemas"]["ApiKey"] & {
            /** @description 明文 key。仅此一次返回，丢失只能撤销重铸。 */
            secret: string;
        };
        Usage: {
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            /** Format: int64 */
            total: number;
            series: {
                /** Format: date-time */
                bucket: string;
                /** Format: int64 */
                value: number;
            }[];
            /** @description 当前套餐月度配额；超限时拒绝 ingest */
            quota?: number | null;
        };
        Error: {
            /** @description 机器可读，如 `unauthorized` / `tenant_not_found` */
            code: string;
            /** @description 中文人类可读 */
            message: string;
            /** @description trace id，复用 chi RequestID 中间件 */
            request_id?: string;
        };
    };
    responses: {
        /** @description 请求体或参数不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未登录或 session 过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在或不属于当前 tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 违反唯一约束或并发冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
