// SPDX-License-Identifier: Apache-2.0

package intercom

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/Phixsura/attune/internal/domain"
)

const (
	// maxContentLen is the upper limit for assembled conversation content,
	// leaving headroom under the 5000-char IngestInput limit.
	maxContentLen = 4500

	partSeparator = "\n\n---\n\n"

	// keepFirstCustomer / keepLastCustomer are the customer messages
	// always retained when structural truncation kicks in.
	keepFirstCustomer = 3
	keepLastCustomer  = 2
)

// roleTag classifies a part author into the transcript tag.
const (
	tagCustomer = "[customer]"
	tagAgent    = "[agent]"
	tagBot      = "[bot]"
)

// buildIngestInput assembles a domain.IngestInput from a conversation
// with its thread parts and resolved contact metadata.
func buildIngestInput(
	srcID, srcName, workspaceID string,
	conv conversation,
	contacts map[string]intercomContact,
) domain.IngestInput {
	cr := buildContent(conv)
	primary := primaryContact(conv, contacts)
	pageURL := conversationURL(workspaceID, conv.ID)

	return domain.IngestInput{
		Source:         channelName,
		Content:        cr.text,
		Type:           inferType(conv),
		SourceUser:     resolveSourceUser(primary, conv),
		PageURL:        pageURL,
		SourceMeta:     buildIntercomSourceMeta(srcID, srcName, workspaceID, conv, primary, cr),
		IdempotencyKey: intercomIdempotencyKey(workspaceID, conv.ID, conv.UpdatedAt),
	}
}

// contentResult carries assembled content and message-role statistics.
type contentResult struct {
	text         string
	customerMsgs int
	agentMsgs    int
	botMsgs      int
	totalParts   int
}

// tagged is one transcript entry with its role classification.
type tagged struct {
	body       string
	tag        string
	isCustomer bool
	isBot      bool
}

// classifyAuthor maps an Intercom part author to a transcript tag.
// Contacts (user/lead/contact) are customers; bots (or admin parts
// generated by the AI agent) are bots; admins/teams are agents.
func classifyAuthor(a partAuthor) string {
	if a.FromAIAgent {
		return tagBot
	}
	switch a.Type {
	case "user", "lead", "contact":
		return tagCustomer
	case "bot":
		return tagBot
	default: // admin, team
		return tagAgent
	}
}

// buildContent assembles the plain-text transcript: seed message first,
// then thread parts tagged by author role. Internal notes and redacted
// parts are excluded entirely; bot parts are kept only when space
// permits. Structural truncation keeps the first 3 + last 2 customer
// messages when the full transcript exceeds maxContentLen.
func buildContent(conv conversation) contentResult {
	var entries []tagged
	var customerMsgs, agentMsgs, botMsgs int

	// Seed message counts as the first customer message when authored by
	// a contact (the overwhelmingly common case).
	seedTag := classifyAuthor(conv.Source.Author)
	if seedTag == tagCustomer {
		customerMsgs++
	}

	for _, p := range conv.Parts.Parts {
		if !includePart(p) {
			continue
		}
		body := strings.TrimSpace(p.Body)
		if body == "" {
			continue
		}
		tag := classifyAuthor(p.Author)
		switch tag {
		case tagCustomer:
			customerMsgs++
		case tagBot:
			botMsgs++
		default:
			agentMsgs++
		}
		entries = append(entries, tagged{
			body:       body,
			tag:        tag,
			isCustomer: tag == tagCustomer,
			isBot:      tag == tagBot,
		})
	}

	header := buildHeader(conv)
	text := assembleParts(header, entries)

	return contentResult{
		text:         text,
		customerMsgs: customerMsgs,
		agentMsgs:    agentMsgs,
		botMsgs:      botMsgs,
		totalParts:   len(conv.Parts.Parts),
	}
}

// includePart filters thread parts down to human-visible messages.
// Internal notes (note, note_and_reopen, …) and redacted parts never
// reach the ingested content.
func includePart(p part) bool {
	if p.Redacted {
		return false
	}
	if strings.HasPrefix(p.PartType, "note") {
		return false
	}
	return true
}

// buildHeader renders the always-kept head: title/subject + seed body.
func buildHeader(conv conversation) string {
	var b strings.Builder
	title := strings.TrimSpace(conv.Title)
	if title == "" {
		title = strings.TrimSpace(conv.Source.Subject)
	}
	if title != "" {
		b.WriteString(title)
		b.WriteString("\n\n")
	}
	seed := strings.TrimSpace(conv.Source.Body)
	if seed != "" {
		b.WriteString(classifyAuthor(conv.Source.Author))
		b.WriteString(" ")
		b.WriteString(seed)
	}
	return b.String()
}

// assembleParts builds the final transcript. Full content when it fits;
// otherwise structural truncation: keep first/last customer messages,
// drop bot messages first, insert an omission marker.
func assembleParts(header string, entries []tagged) string {
	full := buildFull(header, entries)
	if len(full) <= maxContentLen {
		return full
	}

	// First pressure valve: drop bot messages, keep human thread.
	humans := make([]tagged, 0, len(entries))
	for _, e := range entries {
		if !e.isBot {
			humans = append(humans, e)
		}
	}
	full = buildFull(header, humans)
	if len(full) <= maxContentLen {
		return full
	}
	return truncateStructurally(header, humans, full)
}

// truncateStructurally keeps the first keepFirstCustomer + last
// keepLastCustomer customer messages with an omission marker in between.
// Falls back to byte truncation when there are too few customer messages
// to split.
func truncateStructurally(header string, humans []tagged, full string) string {
	var custIdx []int
	for i, e := range humans {
		if e.isCustomer {
			custIdx = append(custIdx, i)
		}
	}
	if keepFirstCustomer+keepLastCustomer >= len(custIdx) {
		return full[:maxContentLen] + " [truncated]"
	}
	firstSet := make(map[int]bool)
	for _, idx := range custIdx[:keepFirstCustomer] {
		firstSet[idx] = true
	}
	lastSet := make(map[int]bool)
	for _, idx := range custIdx[len(custIdx)-keepLastCustomer:] {
		lastSet[idx] = true
	}
	omitted := len(custIdx) - keepFirstCustomer - keepLastCustomer

	var b strings.Builder
	b.WriteString(header)
	pastFirst := false
	for i, e := range humans {
		if !firstSet[i] && !lastSet[i] {
			continue
		}
		if !pastFirst && lastSet[i] && !firstSet[i] {
			b.WriteString(partSeparator)
			fmt.Fprintf(&b, "[... %d messages omitted ...]", omitted) // ptrext:allow fmt-writer
			pastFirst = true
		}
		b.WriteString(partSeparator)
		b.WriteString(e.tag)
		b.WriteString(" ")
		b.WriteString(e.body)
	}
	result := b.String()
	if len(result) > maxContentLen {
		result = result[:maxContentLen] + " [truncated]"
	}
	return result
}

func buildFull(header string, entries []tagged) string {
	var b strings.Builder
	b.WriteString(header)
	for _, e := range entries {
		b.WriteString(partSeparator)
		b.WriteString(e.tag)
		b.WriteString(" ")
		b.WriteString(e.body)
	}
	return b.String()
}

// inferType maps Intercom conversation metadata to an IngestInput.Type
// hint for the enrichment LLM.
func inferType(conv conversation) string {
	// Urgent priority → bug report signal.
	if conv.Priority == "priority" || conv.Priority == "urgent" || conv.Priority == "high" {
		return "bug_report"
	}
	// A low CSAT rating (1-2 of 5) → complaint.
	if conv.Rating != nil && conv.Rating.Rating > 0 && conv.Rating.Rating <= 2 {
		return "complaint"
	}
	return "" // let the LLM decide
}

// primaryContact resolves the first conversation contact through the
// batch-resolved map, falling back to the bare reference.
func primaryContact(conv conversation, contacts map[string]intercomContact) intercomContact {
	if len(conv.Contacts.Contacts) == 0 {
		return intercomContact{}
	}
	ref := conv.Contacts.Contacts[0]
	if c, ok := contacts[ref.ID]; ok {
		return c
	}
	return intercomContact{ID: ref.ID, ExternalID: ref.ExternalID}
}

// resolveSourceUser returns the best human-readable identifier for the
// conversation's primary contact, falling back to the seed author.
func resolveSourceUser(c intercomContact, conv conversation) string {
	if email := strings.TrimSpace(c.Email); email != "" {
		return email
	}
	if name := strings.TrimSpace(c.Name); name != "" {
		return name
	}
	if email := strings.TrimSpace(conv.Source.Author.Email); email != "" {
		return email
	}
	if name := strings.TrimSpace(conv.Source.Author.Name); name != "" {
		return name
	}
	if c.ID != "" {
		return "contact:" + c.ID
	}
	return ""
}

// conversationURL builds the Intercom inbox permalink for operators.
func conversationURL(workspaceID, conversationID string) string {
	return fmt.Sprintf("https://app.intercom.com/a/inbox/%s/inbox/conversation/%s", workspaceID, conversationID)
}

// buildIntercomSourceMeta assembles the source metadata map.
func buildIntercomSourceMeta(
	srcID, srcName, workspaceID string,
	conv conversation,
	primary intercomContact,
	cr contentResult,
) map[string]any {
	tagNames := make([]string, 0, len(conv.Tags.Tags))
	for _, t := range conv.Tags.Tags {
		tagNames = append(tagNames, t.Name)
	}
	tagsJSON, _ := json.Marshal(tagNames) // ptrext:allow json-marshal

	m := map[string]any{
		inboundSourceIDKey:                srcID,
		inboundSourceNameKey:              srcName,
		"intercom_workspace_id":           workspaceID,
		"intercom_conversation_id":        conv.ID,
		"intercom_conversation_url":       conversationURL(workspaceID, conv.ID),
		"intercom_state":                  conv.State,
		"intercom_priority":               conv.Priority,
		"intercom_source_type":            conv.Source.Type,
		"intercom_tags":                   string(tagsJSON),
		"intercom_contact_id":             primary.ID,
		"intercom_contact_external_id":    primary.ExternalID,
		"intercom_contact_name":           strings.TrimSpace(primary.Name),
		"intercom_contact_email":          strings.TrimSpace(primary.Email),
		"intercom_admin_assignee_id":      conv.AdminAssigneeID,
		"intercom_team_assignee_id":       conv.TeamAssigneeID,
		"intercom_ai_agent_participated":  conv.AIAgentParticipated,
		"intercom_customer_message_count": cr.customerMsgs,
		"intercom_agent_message_count":    cr.agentMsgs,
		"intercom_part_count":             cr.totalParts,
		"intercom_created_at":             conv.CreatedAt,
		"intercom_updated_at":             conv.UpdatedAt,
	}
	if conv.Company != nil {
		m["intercom_company_id"] = conv.Company.ID
		m["intercom_company_name"] = strings.TrimSpace(conv.Company.Name)
	}
	if conv.Rating != nil {
		m["intercom_rating"] = conv.Rating.Rating
		if remark := strings.TrimSpace(conv.Rating.Remark); remark != "" {
			m["intercom_rating_remark"] = remark
		}
	}
	return m
}

// matchesStateFilter returns true if the conversation passes the
// configured state filter. An empty filter matches everything.
func matchesStateFilter(conv conversation, states []string) bool {
	if len(states) == 0 {
		return true
	}
	for _, s := range states {
		if strings.EqualFold(conv.State, s) {
			return true
		}
	}
	return false
}

// intercomIdempotencyKey builds the replay-safe deduplication key.
// Includes updatedAt so conversation updates produce new feedback rows
// while replays of the same snapshot dedup.
func intercomIdempotencyKey(workspaceID, conversationID string, updatedAt int64) string {
	return "intercom_" + sanitizeKeyPart(workspaceID) + "_" +
		sanitizeKeyPart(conversationID) + "_" +
		strconv.FormatInt(updatedAt, 10)
}

// sanitizeKeyPart strips characters not allowed in idempotency keys.
func sanitizeKeyPart(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "unknown"
	}
	var b strings.Builder
	b.Grow(len(raw))
	for _, r := range raw {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_' || r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "unknown"
	}
	return out
}
