// SPDX-License-Identifier: Apache-2.0

package intercom

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/Phixsura/attune/internal/domain"
)

const (
	// maxContentLen is the upper limit for assembled conversation content,
	// leaving headroom under the 5000-char IngestInput limit.
	maxContentLen = 4500

	partSeparator = "\n\n---\n\n"

	// keepFirstCustomer / keepLastCustomer are the customer messages
	// always retained when structural truncation kicks in.
	keepFirstCustomer = 3
	keepLastCustomer  = 2
)

// roleTag classifies a part author into the transcript tag.
const (
	tagCustomer = "[customer]"
	tagAgent    = "[agent]"
	tagBot      = "[bot]"
)

// buildIngestInput assembles a domain.IngestInput from a conversation
// with its thread parts and resolved contact metadata.
func buildIngestInput(
	srcID, srcName, workspaceID, region string,
	conv conversation,
	contacts map[string]intercomContact,
	admins map[int64]intercomAdmin,
) domain.IngestInput {
	cr := buildContent(conv)
	primary := primaryContact(conv, contacts)
	pageURL := conversationURL(region, workspaceID, conv.ID)

	return domain.IngestInput{
		Source:         channelName,
		Content:        cr.text,
		Type:           inferType(conv),
		SourceUser:     resolveSourceUser(primary, conv),
		PageURL:        pageURL,
		SourceMeta:     buildIntercomSourceMeta(srcID, srcName, workspaceID, region, conv, primary, admins, cr),
		IdempotencyKey: intercomIdempotencyKey(workspaceID, conv.ID, conv.UpdatedAt),
	}
}

// contentResult carries assembled content and message-role statistics.
type contentResult struct {
	text         string
	customerMsgs int
	agentMsgs    int
	botMsgs      int
	totalParts   int
}

// tagged is one transcript entry with its role classification.
type tagged struct {
	body       string
	tag        string
	isCustomer bool
	isBot      bool
}

// classifyAuthor maps an Intercom part author to a transcript tag.
// Contacts (user/lead/contact) are customers; bots (or admin parts
// generated by the AI agent) are bots; admins/teams are agents.
func classifyAuthor(a partAuthor) string {
	if a.FromAIAgent {
		return tagBot
	}
	switch a.Type {
	case "user", "lead", "contact":
		return tagCustomer
	case "bot":
		return tagBot
	default: // admin, team
		return tagAgent
	}
}

// buildContent assembles the plain-text transcript: seed message first,
// then thread parts tagged by author role. Internal notes and redacted
// parts are excluded entirely; bot parts are kept only when space
// permits. Structural truncation keeps the first 3 + last 2 customer
// messages when the full transcript exceeds maxContentLen.
func buildContent(conv conversation) contentResult {
	var entries []tagged
	var customerMsgs, agentMsgs, botMsgs int

	// Seed message counts as the first customer message when authored by
	// a contact (the overwhelmingly common case) and actually has text.
	if classifyAuthor(conv.Source.Author) == tagCustomer &&
		strings.TrimSpace(stripHTMLTags(conv.Source.Body)) != "" {
		customerMsgs++
	}

	for _, p := range conv.Parts.Parts {
		if !includePart(p) {
			continue
		}
		body := strings.TrimSpace(p.Body)
		if body == "" {
			continue
		}
		tag := classifyAuthor(p.Author)
		switch tag {
		case tagCustomer:
			customerMsgs++
		case tagBot:
			botMsgs++
		default:
			agentMsgs++
		}
		entries = append(entries, tagged{
			body:       body,
			tag:        tag,
			isCustomer: tag == tagCustomer,
			isBot:      tag == tagBot,
		})
	}

	header := buildHeader(conv)
	text := assembleParts(header, entries)

	return contentResult{
		text:         text,
		customerMsgs: customerMsgs,
		agentMsgs:    agentMsgs,
		botMsgs:      botMsgs,
		totalParts:   len(conv.Parts.Parts),
	}
}

// includePart filters thread parts down to human-visible messages.
// Internal notes (note, note_and_reopen, …) and redacted parts never
// reach the ingested content.
func includePart(p part) bool {
	if p.Redacted {
		return false
	}
	if strings.HasPrefix(p.PartType, "note") {
		return false
	}
	return true
}

// buildHeader renders the always-kept head: title/subject + seed body.
// The seed body is HTML-stripped: search results (and hence the
// degraded summary-fallback path) carry source.body as HTML —
// display_as=plaintext only applies to the detail endpoint's parts.
func buildHeader(conv conversation) string {
	var b strings.Builder
	title := strings.TrimSpace(stripHTMLTags(conv.Title))
	if title == "" {
		title = strings.TrimSpace(stripHTMLTags(conv.Source.Subject))
	}
	if title != "" {
		b.WriteString(title)
		b.WriteString("\n\n")
	}
	seed := strings.TrimSpace(stripHTMLTags(conv.Source.Body))
	if seed != "" {
		b.WriteString(classifyAuthor(conv.Source.Author))
		b.WriteString(" ")
		b.WriteString(seed)
	}
	return b.String()
}

// htmlBlockBreaks maps the block/line-break tags Intercom's serializer
// emits to newlines before tag stripping.
var htmlBlockBreaks = strings.NewReplacer("</p>", "\n", "</P>", "\n", "<br>", "\n", "<br/>", "\n", "<br />", "\n")

// htmlEntities unescapes the entities Intercom's serializer emits.
var htmlEntities = strings.NewReplacer("&amp;", "&", "&lt;", "<", "&gt;", ">", "&quot;", `"`, "&#39;", "'", "&nbsp;", " ")

// stripHTMLTags removes markup from Intercom HTML bodies, turning block
// boundaries into newlines. Tag-free input skips the tag scan but still
// unescapes entities — Intercom HTML-encodes text content regardless of
// whether the body happens to contain markup, and "&amp;" must not read
// differently depending on a sibling tag.
func stripHTMLTags(s string) string {
	if !strings.ContainsRune(s, '<') {
		if strings.ContainsRune(s, '&') {
			return htmlEntities.Replace(s)
		}
		return s
	}
	s = htmlBlockBreaks.Replace(s)
	var b strings.Builder
	b.Grow(len(s))
	inTag := false
	for _, r := range s {
		switch {
		case r == '<':
			inTag = true
		case r == '>':
			inTag = false
		case !inTag:
			b.WriteRune(r)
		}
	}
	return strings.TrimSpace(htmlEntities.Replace(b.String()))
}

// assembleParts builds the final transcript. Full content when it fits;
// otherwise structural truncation: keep first/last customer messages,
// drop bot messages first, insert an omission marker.
func assembleParts(header string, entries []tagged) string {
	full := buildFull(header, entries)
	if len(full) <= maxContentLen {
		return full
	}

	// First pressure valve: drop bot messages, keep human thread.
	humans := make([]tagged, 0, len(entries))
	for _, e := range entries {
		if !e.isBot {
			humans = append(humans, e)
		}
	}
	full = buildFull(header, humans)
	if len(full) <= maxContentLen {
		return full
	}
	return truncateStructurally(header, humans, full)
}

// truncateStructurally keeps the head through the keepFirstCustomer-th
// customer message and the tail from the keepLastCustomer-th-from-last
// customer message onward — agent replies inside the kept ranges stay,
// so the transcript keeps its conversational shape. The omission marker
// counts every dropped message (customer AND agent), not just customer
// ones. Falls back to byte truncation when there are too few customer
// messages to split.
func truncateStructurally(header string, humans []tagged, full string) string {
	var custIdx []int
	for i, e := range humans {
		if e.isCustomer {
			custIdx = append(custIdx, i)
		}
	}
	if keepFirstCustomer+keepLastCustomer >= len(custIdx) {
		return truncateBytesRuneSafe(full, maxContentLen) + " [truncated]"
	}
	headEnd := custIdx[keepFirstCustomer-1]
	tailStart := custIdx[len(custIdx)-keepLastCustomer]
	// custIdx is strictly increasing and (guard above) has at least
	// keepFirst+keepLast+1 entries, so tailStart ≥ headEnd+2: at least
	// one message is always omitted between the kept ranges.
	omitted := tailStart - headEnd - 1

	var b strings.Builder
	b.WriteString(header)
	for i := 0; i <= headEnd; i++ {
		b.WriteString(partSeparator)
		b.WriteString(humans[i].tag)
		b.WriteString(" ")
		b.WriteString(humans[i].body)
	}
	b.WriteString(partSeparator)
	fmt.Fprintf(&b, "[... %d messages omitted ...]", omitted) // ptrext:allow fmt-writer
	for i := tailStart; i < len(humans); i++ {
		b.WriteString(partSeparator)
		b.WriteString(humans[i].tag)
		b.WriteString(" ")
		b.WriteString(humans[i].body)
	}
	result := b.String()
	if len(result) > maxContentLen {
		result = truncateBytesRuneSafe(result, maxContentLen) + " [truncated]"
	}
	return result
}

// truncateBytesRuneSafe cuts s to at most maxBytes without splitting a
// UTF-8 rune (a mid-rune cut would produce invalid UTF-8 that
// PostgreSQL rejects, permanently failing the ingest).
func truncateBytesRuneSafe(s string, maxBytes int) string {
	if len(s) <= maxBytes {
		return s
	}
	cut := maxBytes
	for cut > 0 && !utf8.RuneStart(s[cut]) {
		cut--
	}
	return s[:cut]
}

func buildFull(header string, entries []tagged) string {
	var b strings.Builder
	b.WriteString(header)
	for _, e := range entries {
		b.WriteString(partSeparator)
		b.WriteString(e.tag)
		b.WriteString(" ")
		b.WriteString(e.body)
	}
	return b.String()
}

// inferType maps Intercom conversation metadata to an IngestInput.Type
// hint for the enrichment LLM. Priority is the strongest signal, then
// human CSAT, then the Fin AI agent's exit state: a conversation Fin
// escalated or that got negative feedback is a product-pain signal.
func inferType(conv conversation) string {
	// Urgent priority → bug report signal.
	if conv.Priority == "priority" || conv.Priority == "urgent" || conv.Priority == "high" {
		return "bug_report"
	}
	// A low CSAT rating (1-2 of 5) → complaint.
	if conv.Rating != nil && conv.Rating.Rating > 0 && conv.Rating.Rating <= 2 {
		return "complaint"
	}
	// Fin resolution telemetry: escalation / negative feedback → complaint.
	if conv.AIAgent != nil {
		switch conv.AIAgent.ResolutionState {
		case "escalated", "negative_feedback":
			return "complaint"
		}
	}
	return "" // let the LLM decide
}

// primaryContact resolves the first conversation contact through the
// batch-resolved map, falling back to the bare reference.
func primaryContact(conv conversation, contacts map[string]intercomContact) intercomContact {
	if len(conv.Contacts.Contacts) == 0 {
		return intercomContact{}
	}
	ref := conv.Contacts.Contacts[0]
	if c, ok := contacts[ref.ID]; ok {
		return c
	}
	return intercomContact{ID: ref.ID, ExternalID: ref.ExternalID}
}

// resolveSourceUser returns the best human-readable identifier for the
// conversation's primary contact, falling back to the seed author.
func resolveSourceUser(c intercomContact, conv conversation) string {
	if email := strings.TrimSpace(c.Email); email != "" {
		return email
	}
	if name := strings.TrimSpace(c.Name); name != "" {
		return name
	}
	if email := strings.TrimSpace(conv.Source.Author.Email); email != "" {
		return email
	}
	if name := strings.TrimSpace(conv.Source.Author.Name); name != "" {
		return name
	}
	if c.ID != "" {
		return "contact:" + c.ID
	}
	return ""
}

// conversationURL builds the Intercom inbox permalink for operators.
// The app host is regional: EU/AU workspaces live on app.eu/.au
// subdomains — a US-host link would 404 for them.
func conversationURL(region, workspaceID, conversationID string) string {
	host := "app.intercom.com"
	switch strings.ToLower(strings.TrimSpace(region)) {
	case "eu":
		host = "app.eu.intercom.com"
	case "au":
		host = "app.au.intercom.com"
	}
	return fmt.Sprintf("https://%s/a/inbox/%s/inbox/conversation/%s", host, workspaceID, conversationID)
}

// buildIntercomSourceMeta assembles the source metadata map.
func buildIntercomSourceMeta(
	srcID, srcName, workspaceID, region string,
	conv conversation,
	primary intercomContact,
	admins map[int64]intercomAdmin,
	cr contentResult,
) map[string]any {
	tagNames := make([]string, 0, len(conv.Tags.Tags))
	for _, t := range conv.Tags.Tags {
		tagNames = append(tagNames, t.Name)
	}
	tagsJSON, _ := json.Marshal(tagNames) // ptrext:allow json-marshal

	m := map[string]any{
		inboundSourceIDKey:                srcID,
		inboundSourceNameKey:              srcName,
		"intercom_workspace_id":           workspaceID,
		"intercom_conversation_id":        conv.ID,
		"intercom_conversation_url":       conversationURL(region, workspaceID, conv.ID),
		"intercom_state":                  conv.State,
		"intercom_priority":               conv.Priority,
		"intercom_source_type":            conv.Source.Type,
		"intercom_tags":                   string(tagsJSON),
		"intercom_contact_id":             primary.ID,
		"intercom_contact_external_id":    primary.ExternalID,
		"intercom_contact_name":           strings.TrimSpace(primary.Name),
		"intercom_contact_email":          strings.TrimSpace(primary.Email),
		"intercom_admin_assignee_id":      conv.AdminAssigneeID,
		"intercom_team_assignee_id":       conv.TeamAssigneeID,
		"intercom_ai_agent_participated":  conv.AIAgentParticipated,
		"intercom_customer_message_count": cr.customerMsgs,
		"intercom_agent_message_count":    cr.agentMsgs,
		"intercom_part_count":             cr.totalParts,
		"intercom_created_at":             conv.CreatedAt,
		"intercom_updated_at":             conv.UpdatedAt,
	}
	addCompanyMeta(m, conv)
	addOptionalMeta(m, conv, admins)
	return m
}

// addCompanyMeta emits the company identity + revenue context
// (GET /companies/{id}) — feeds automatic account attribution and the
// revenue-weighted decision score at promote.
func addCompanyMeta(m map[string]any, conv conversation) {
	if conv.Company == nil {
		return
	}
	m["intercom_company_id"] = conv.Company.ID
	m["intercom_company_name"] = strings.TrimSpace(conv.Company.Name)
	if conv.Company.MonthlySpend > 0 {
		m["intercom_company_monthly_spend"] = conv.Company.MonthlySpend
	}
	if plan := strings.TrimSpace(conv.Company.Plan.Name); plan != "" {
		m["intercom_company_plan"] = plan
	}
	if conv.Company.Size > 0 {
		m["intercom_company_size"] = conv.Company.Size
	}
	if industry := strings.TrimSpace(conv.Company.Industry); industry != "" {
		m["intercom_company_industry"] = industry
	}
}

// addOptionalMeta emits rating, customer-side URL, teammate name, custom
// attributes, and Fin AI-agent exit telemetry when present.
func addOptionalMeta(m map[string]any, conv conversation, admins map[int64]intercomAdmin) {
	if conv.Rating != nil {
		m["intercom_rating"] = conv.Rating.Rating
		if remark := strings.TrimSpace(conv.Rating.Remark); remark != "" {
			m["intercom_rating_remark"] = remark
		}
	}
	// The page the customer started the conversation from (Messenger
	// conversations carry the in-app URL — the customer-side context;
	// PageURL stays the operator-side inbox permalink).
	if u := strings.TrimSpace(conv.Source.URL); u != "" {
		m["intercom_source_url"] = u
	}
	// Teammate resolution: assignee IDs become human-readable names so
	// operators see who owns the conversation without opening Intercom.
	if conv.AdminAssigneeID > 0 {
		if ad, ok := admins[conv.AdminAssigneeID]; ok && strings.TrimSpace(ad.Name) != "" {
			m["intercom_teammate_name"] = strings.TrimSpace(ad.Name)
		}
	}
	// Operator-defined structured data (order IDs, plan tiers, error
	// codes) — JSON passthrough, same pattern as zendesk_custom_fields.
	if len(conv.CustomAttributes) > 0 {
		attrsJSON, _ := json.Marshal(conv.CustomAttributes) // ptrext:allow json-marshal
		m["intercom_custom_attributes"] = string(attrsJSON)
	}
	// Fin AI-agent exit telemetry — an escalated / negative-feedback
	// resolution routes very differently from a confirmed resolution.
	if conv.AIAgent != nil {
		if rs := conv.AIAgent.ResolutionState; rs != "" {
			m["intercom_ai_resolution_state"] = rs
		}
		if conv.AIAgent.Rating > 0 {
			m["intercom_ai_rating"] = conv.AIAgent.Rating
		}
		if lat := conv.AIAgent.LastAnswerType; lat != "" {
			m["intercom_ai_last_answer_type"] = lat
		}
	}
}

// matchesFilter returns true if the conversation passes the configured
// state + tag filters. Empty filters match everything. Filtering runs on
// search-result data only (states and tags are present on summaries), so
// filtered conversations never consume detail-fetch budget.
func matchesFilter(conv conversation, cfg Config) bool {
	if !matchesStateFilter(conv, cfg.FilterStates) {
		return false
	}
	// Exclude tags: if the conversation has ANY excluded tag, skip.
	for _, et := range cfg.FilterExcludeTags {
		for _, tag := range conv.Tags.Tags {
			if strings.EqualFold(tag.Name, et) {
				return false
			}
		}
	}
	// Required tags: conversation must have ALL required tags.
	for _, rt := range cfg.FilterTags {
		found := false
		for _, tag := range conv.Tags.Tags {
			if strings.EqualFold(tag.Name, rt) {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

// matchesStateFilter returns true if the conversation passes the
// configured state filter. An empty filter matches everything.
func matchesStateFilter(conv conversation, states []string) bool {
	if len(states) == 0 {
		return true
	}
	for _, s := range states {
		if strings.EqualFold(conv.State, s) {
			return true
		}
	}
	return false
}

// intercomIdempotencyKey builds the replay-safe deduplication key.
// Includes updatedAt so conversation updates produce new feedback rows
// while replays of the same snapshot dedup.
func intercomIdempotencyKey(workspaceID, conversationID string, updatedAt int64) string {
	return "intercom_" + sanitizeKeyPart(workspaceID) + "_" +
		sanitizeKeyPart(conversationID) + "_" +
		strconv.FormatInt(updatedAt, 10)
}

// sanitizeKeyPart strips characters not allowed in idempotency keys.
func sanitizeKeyPart(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "unknown"
	}
	var b strings.Builder
	b.Grow(len(raw))
	for _, r := range raw {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_' || r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "unknown"
	}
	return out
}
