// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/audit.proto

/* eslint-disable */
import { type HttpBody } from "../../google/api/httpbody";

export const protobufPackage = "attune.v1";

export interface AuditLogEntry {
  id: string;
  actorType: string;
  actorId: string;
  actorEmail: string;
  actorIp: string;
  actorUserAgent: string;
  action: string;
  targetType: string;
  targetId: string;
  summary: string;
  beforeJson: string;
  afterJson: string;
  createdAt: string;
}

export interface ListAuditLogRequest {
  action: string;
  actorType: string;
  actorId: string;
  targetType: string;
  targetId: string;
  from: string;
  to: string;
  limit: number;
  cursor?: string | undefined;
  actions: string[];
}

export interface ListAuditLogResponse {
  items: AuditLogEntry[];
  nextCursor?: string | undefined;
}

export interface ExportAuditLogCSVRequest {
  action: string;
  actorType: string;
  actorId: string;
  targetType: string;
  targetId: string;
  from: string;
  to: string;
  actions: string[];
}

export interface CreateAuditEvidenceExportRequest {
  from: string;
  to: string;
  actions: string[];
  actorType: string;
  actorId: string;
  targetType: string;
  targetId: string;
}

export interface CreateAuditEvidenceExportResponse {
  jobId: string;
  status: string;
  retryAfterSeconds: number;
}

export interface GetAuditEvidenceExportRequest {
  jobId: string;
}

export interface GetAuditEvidenceExportResponse {
  jobId: string;
  status: string;
  totalEvents: number;
  createdAt: string;
  startedAt?: string | undefined;
  completedAt?: string | undefined;
  expiresAt?: string | undefined;
  downloadedAt?: string | undefined;
  downloadPath?: string | undefined;
  archiveFilename?: string | undefined;
  error?: string | undefined;
  retryAfterSeconds: number;
}

export interface DownloadAuditEvidenceExportRequest {
  jobId: string;
}

export interface AuditLogService {
  ListAuditLog(request: ListAuditLogRequest): Promise<ListAuditLogResponse>;
  ExportAuditLogCSV(request: ExportAuditLogCSVRequest): Promise<HttpBody>;
  CreateAuditEvidenceExport(request: CreateAuditEvidenceExportRequest): Promise<CreateAuditEvidenceExportResponse>;
  GetAuditEvidenceExport(request: GetAuditEvidenceExportRequest): Promise<GetAuditEvidenceExportResponse>;
  DownloadAuditEvidenceExport(request: DownloadAuditEvidenceExportRequest): Promise<HttpBody>;
}
