// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/classification_quality.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface GetClassificationQualityRequest {
  currentFrom: string;
  currentTo: string;
  baselineFrom: string;
  baselineTo: string;
  /** hour | day */
  bucketWidth: string;
  source: string;
  logicalModel: string;
  providerModel: string;
  channelId: string;
  dimensionName: string;
  severity: string;
  lowConfidenceThreshold: number;
  limit: number;
}

export interface GetClassificationQualitySamplesRequest {
  ids: string[];
}

export interface GetClassificationQualityResponse {
  generatedAt: string;
  dataThrough: string;
  rollupLagSeconds: string;
  currentFrom: string;
  currentTo: string;
  baselineFrom: string;
  baselineTo: string;
  bucketWidth: string;
  summary?: ClassificationQualitySummary | undefined;
  series: ClassificationQualityTimeBucket[];
  dimensions: ClassificationDimensionDrift[];
  warnings: ClassificationQualityWarning[];
  samples: ClassificationQualitySample[];
}

export interface GetClassificationQualitySamplesResponse {
  samples: ClassificationQualitySample[];
}

export interface ClassificationQualitySummary {
  classificationEvents: string;
  failedAttempts: string;
  averageConfidence: number;
  lowConfidenceRate: number;
  offListRate: number;
  unknownDimensionRate: number;
  parseFailureRate: number;
  terminalFailureRate: number;
  worstSeverity: string;
}

export interface ClassificationQualityTimeBucket {
  bucket: string;
  classificationEvents: string;
  failedAttempts: string;
  averageConfidence: number;
  lowConfidenceRate: number;
  offListRate: number;
  unknownDimensionRate: number;
  parseFailureRate: number;
  terminalFailureRate: number;
}

export interface ClassificationDimensionDrift {
  dimensionName: string;
  severity: string;
  status: string;
  currentCount: string;
  baselineCount: string;
  jsDistance: number;
  psi: number;
  lowConfidenceRate: number;
  offListRate: number;
  unknownDimensionRate: number;
  values: ClassificationValueDrift[];
  sampleFeedbackIds: string[];
}

export interface ClassificationValueDrift {
  valueHash: string;
  valueDisplay: string;
  valueStatus: string;
  currentCount: string;
  baselineCount: string;
  currentShare: number;
  baselineShare: number;
  shareDeltaPp: number;
  contribution: number;
  sampleFeedbackIds: string[];
}

export interface ClassificationQualityWarning {
  reason: string;
  severity: string;
  dimensionName: string;
  valueDisplay: string;
  value: number;
  threshold: number;
  message: string;
  sampleFeedbackIds: string[];
}

export interface ClassificationQualitySample {
  id: string;
  createdAt: string;
  enrichedAt?: string | undefined;
  source: string;
  title: string;
  displayTitle?: string | undefined;
  enrichmentStatus: string;
  classificationConfidence?: number | undefined;
  signalReason: string;
}

/**
 * ClassificationQualityService serves the console classification quality
 * dashboard and its bounded sample drill-downs.
 */
export interface ClassificationQualityService {
  GetClassificationQuality(request: GetClassificationQualityRequest): Promise<GetClassificationQualityResponse>;
  GetClassificationQualitySamples(
    request: GetClassificationQualitySamplesRequest,
  ): Promise<GetClassificationQualitySamplesResponse>;
}
