// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/cohort_sync.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface CohortSource {
  id: string;
  provider: string;
  name: string;
  authType: string;
  baseUrl: string;
  enabled: boolean;
  status: string;
  lastSyncAt?: Date | undefined;
  lastError: string;
  webhookUrl: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

export interface ListCohortSourcesRequest {
}

export interface ListCohortSourcesResponse {
  sources: CohortSource[];
}

export interface CreateCohortSourceRequest {
  provider: string;
  name: string;
  authType: string;
  credential: string;
  webhookSecret?: string | undefined;
  baseUrl?: string | undefined;
  providerConfigJson?: string | undefined;
  enabled: boolean;
}

export interface UpdateCohortSourceRequest {
  id: string;
  name?: string | undefined;
  enabled?: boolean | undefined;
  credential?: string | undefined;
  baseUrl?: string | undefined;
  providerConfigJson?: string | undefined;
}

export interface DeleteCohortSourceRequest {
  id: string;
}

export interface DeleteCohortSourceResponse {
}

export interface TestCohortSourceRequest {
  id: string;
}

export interface TestCohortSourceResponse {
  ok: boolean;
  error: string;
}

export interface Cohort {
  id: string;
  cohortSourceId: string;
  externalCohortId: string;
  name: string;
  description: string;
  staleTtlDays: number;
  memberCount: number;
  enabled: boolean;
  lastSyncedAt?: Date | undefined;
  lastError: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

export interface ListCohortsRequest {
  sourceId?: string | undefined;
}

export interface ListCohortsResponse {
  cohorts: Cohort[];
}

export interface UpdateCohortRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  staleTtlDays?: number | undefined;
  enabled?: boolean | undefined;
}

export interface SyncCohortRequest {
  id: string;
}

export interface SyncCohortResponse {
  run?: CohortSyncRun | undefined;
}

export interface CohortSyncRun {
  id: string;
  cohortId: string;
  trigger: string;
  status: string;
  membersAdded: number;
  membersRemoved: number;
  membersTotal: number;
  errorMessage: string;
  startedAt?: Date | undefined;
  finishedAt?: Date | undefined;
  createdAt?: Date | undefined;
}

export interface ListCohortSyncRunsRequest {
  cohortId: string;
  limit?: number | undefined;
}

export interface ListCohortSyncRunsResponse {
  runs: CohortSyncRun[];
}

export interface GetCohortSyncHealthRequest {
}

export interface CohortSyncHealth {
  sourceCount: number;
  activeSources: number;
  errorSources: number;
  cohortCount: number;
  totalActiveMembers: number;
}

/**
 * CohortSyncService manages tenant-scoped cohort source connections,
 * cohort definitions, and sync run history.
 */
export interface CohortSyncService {
  ListCohortSources(request: ListCohortSourcesRequest): Promise<ListCohortSourcesResponse>;
  CreateCohortSource(request: CreateCohortSourceRequest): Promise<CohortSource>;
  UpdateCohortSource(request: UpdateCohortSourceRequest): Promise<CohortSource>;
  DeleteCohortSource(request: DeleteCohortSourceRequest): Promise<DeleteCohortSourceResponse>;
  TestCohortSource(request: TestCohortSourceRequest): Promise<TestCohortSourceResponse>;
  ListCohorts(request: ListCohortsRequest): Promise<ListCohortsResponse>;
  UpdateCohort(request: UpdateCohortRequest): Promise<Cohort>;
  SyncCohort(request: SyncCohortRequest): Promise<SyncCohortResponse>;
  ListCohortSyncRuns(request: ListCohortSyncRunsRequest): Promise<ListCohortSyncRunsResponse>;
  GetCohortSyncHealth(request: GetCohortSyncHealthRequest): Promise<CohortSyncHealth>;
}
