// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/digest_subscription.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * DigestSubscription is a tenant's daily digest config. Delivery is to the
 * tenant's raw-webhook notify target whose audience='digest'.
 */
export interface DigestSubscription {
  enabled: boolean;
  /** daily | weekly */
  frequency: string;
  /** tenant-local hour 0..23 */
  sendHour: number;
  /** 0=Sun .. 6=Sat, used when frequency=weekly */
  byweekday?:
    | number
    | undefined;
  /** IANA override; empty => tenant default */
  timezone?:
    | string
    | undefined;
  /** >= this many enriched rows => LLM themes */
  llmMinFeedback: number;
  sendOnEmpty: boolean;
  /** optional LLM naming override */
  themePrompt?:
    | string
    | undefined;
  /** RFC3339, read-only (scheduler cursor) */
  nextRunAt?:
    | string
    | undefined;
  /** RFC3339, read-only */
  lastRunAt?:
    | string
    | undefined;
  /** RFC3339 */
  createdAt: string;
  /** RFC3339 */
  updatedAt: string;
  /** use embedding-based HDBSCAN clustering (#27) */
  clusteringEnabled: boolean;
}

export interface GetDigestSubscriptionRequest {
}

export interface UpsertDigestSubscriptionRequest {
  enabled: boolean;
  frequency: string;
  sendHour: number;
  byweekday?: number | undefined;
  timezone?: string | undefined;
  llmMinFeedback: number;
  sendOnEmpty: boolean;
  themePrompt?:
    | string
    | undefined;
  /** use embedding-based HDBSCAN clustering */
  clusteringEnabled: boolean;
}

export interface DeleteDigestSubscriptionRequest {
}

export interface DeleteDigestSubscriptionResponse {
}

/**
 * DigestSubscriptionService manages a tenant's daily digest configuration (#27).
 * v1 is a per-tenant singleton resource: one subscription per tenant, so the
 * endpoints are get / upsert / delete with no id path param.
 */
export interface DigestSubscriptionService {
  /** GET /fb/v1/console/digest-subscription */
  GetDigestSubscription(request: GetDigestSubscriptionRequest): Promise<DigestSubscription>;
  /** PUT /fb/v1/console/digest-subscription (create or replace) */
  UpsertDigestSubscription(request: UpsertDigestSubscriptionRequest): Promise<DigestSubscription>;
  /** DELETE /fb/v1/console/digest-subscription (204) */
  DeleteDigestSubscription(request: DeleteDigestSubscriptionRequest): Promise<DeleteDigestSubscriptionResponse>;
}
