// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/enrichment_runtime.proto

/* eslint-disable */
import { type Duration } from "../../google/protobuf/duration";

export const protobufPackage = "attune.v1";

export enum RuntimeApplyStatus {
  RUNTIME_APPLY_STATUS_UNSPECIFIED = "RUNTIME_APPLY_STATUS_UNSPECIFIED",
  RUNTIME_APPLY_STATUS_PENDING = "RUNTIME_APPLY_STATUS_PENDING",
  RUNTIME_APPLY_STATUS_APPLYING = "RUNTIME_APPLY_STATUS_APPLYING",
  RUNTIME_APPLY_STATUS_APPLIED = "RUNTIME_APPLY_STATUS_APPLIED",
  RUNTIME_APPLY_STATUS_FAILED = "RUNTIME_APPLY_STATUS_FAILED",
  RUNTIME_APPLY_STATUS_STALE = "RUNTIME_APPLY_STATUS_STALE",
  RUNTIME_APPLY_STATUS_DEGRADED = "RUNTIME_APPLY_STATUS_DEGRADED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface EnrichmentRuntimeSpec {
  queueLen: number;
  workers: number;
  batchSize: number;
  batchWindow?: Duration | undefined;
  sweepInterval?: Duration | undefined;
  llmRateLimitEnabled: boolean;
  llmMaxQps: number;
  llmBurst: number;
}

export interface EnrichmentRuntimeRevision {
  version: string;
  updatedAt?: Date | undefined;
  updatedBy: string;
  updateReason: string;
  bootstrapSnapshotVersion: string;
  specVersion: number;
  lastKnownGoodVersion: string;
}

export interface EnrichmentRuntimeHistoryEntry {
  revision?: EnrichmentRuntimeRevision | undefined;
  operationType: string;
  riskLevel: string;
  sourceVersion: string;
  targetVersion: string;
  rollbackLineage: string;
}

export interface EnrichmentRuntimeInstanceStatus {
  instanceId: string;
  bootId: string;
  desiredVersion: string;
  observedDesiredVersion: string;
  runnerEffectiveVersion: string;
  limiterEffectiveVersion: string;
  attemptedRunnerVersion: string;
  attemptedLimiterVersion: string;
  runnerApplyStatus: RuntimeApplyStatus;
  limiterApplyStatus: RuntimeApplyStatus;
  runnerLastApplyError: string;
  limiterLastApplyError: string;
  queueDepth: number;
  queueCapacityTarget: number;
  queueCapacityEffective: number;
  queueResizePending: boolean;
  inFlight: number;
  degradedReason: string;
  lastAppliedAt?: Date | undefined;
  lastReconciledAt?: Date | undefined;
  lastSeenAt?: Date | undefined;
  appliedSpec?: EnrichmentRuntimeSpec | undefined;
}

export interface EnrichmentRuntimeSummary {
  desiredVersion: string;
  liveInstances: number;
  staleInstances: number;
  expiredInstances: number;
  degradedInstances: number;
  fullyAppliedInstances: number;
  fullyConverged: boolean;
}

export interface EnrichmentRuntimeReadModel {
  bootstrapDefault?: EnrichmentRuntimeSpec | undefined;
  desiredSpec?: EnrichmentRuntimeSpec | undefined;
  desiredRevision?: EnrichmentRuntimeRevision | undefined;
  summary?: EnrichmentRuntimeSummary | undefined;
  instances: EnrichmentRuntimeInstanceStatus[];
  history: EnrichmentRuntimeHistoryEntry[];
}

export interface GetEnrichmentRuntimeRequest {
}

export interface GetEnrichmentRuntimeResponse {
  runtime?: EnrichmentRuntimeReadModel | undefined;
}

export interface UpdateEnrichmentRuntimeRequest {
  expectedVersion: string;
  spec?: EnrichmentRuntimeSpec | undefined;
  updateReason: string;
}

export interface UpdateEnrichmentRuntimeResponse {
  runtime?: EnrichmentRuntimeReadModel | undefined;
}

export interface ResetEnrichmentRuntimeRequest {
  expectedVersion: string;
  fields: string[];
  resetAll: boolean;
  updateReason: string;
}

export interface ResetEnrichmentRuntimeResponse {
  runtime?: EnrichmentRuntimeReadModel | undefined;
}

export interface RollbackEnrichmentRuntimeRequest {
  expectedVersion: string;
  targetVersion: string;
  updateReason: string;
}

export interface RollbackEnrichmentRuntimeResponse {
  runtime?: EnrichmentRuntimeReadModel | undefined;
}

export interface EnrichmentRuntimeService {
  GetEnrichmentRuntime(request: GetEnrichmentRuntimeRequest): Promise<GetEnrichmentRuntimeResponse>;
  UpdateEnrichmentRuntime(request: UpdateEnrichmentRuntimeRequest): Promise<UpdateEnrichmentRuntimeResponse>;
  ResetEnrichmentRuntime(request: ResetEnrichmentRuntimeRequest): Promise<ResetEnrichmentRuntimeResponse>;
  RollbackEnrichmentRuntime(request: RollbackEnrichmentRuntimeRequest): Promise<RollbackEnrichmentRuntimeResponse>;
}
