// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/ingest.proto

/* eslint-disable */
import { type Tag } from "./tag";
import { type WorkflowState } from "./workflow";

export const protobufPackage = "attune.v1";

/**
 * IngestRequest is the JSON body of POST /v1/feedback/ingest.
 *
 * JSON field names follow the protoJSON default (lowerCamelCase), which exactly
 * reproduces today's wire: content / source / sourceUser / sourceMeta / pageUrl.
 */
export interface IngestRequest {
  /** The feedback text. Required; the handler caps it at 5000 chars. */
  content: string;
  /**
   * Inbound channel/source identity ("api", "web", …). Channel-agnostic and
   * validated against the handler allow-list; defaults to "api" when empty.
   */
  source: string;
  /** Opaque end-user identifier from the originating system (optional). */
  sourceUser: string;
  /** Arbitrary source-specific metadata (optional). */
  sourceMeta?:
    | { [key: string]: any }
    | undefined;
  /** Originating page URL, for the in-app web widget (optional). */
  pageUrl: string;
}

/** IngestResponse is returned on 200. */
export interface IngestResponse {
  /**
   * The stored feedback row id.
   *
   * NOTE: per the protoJSON spec, int64 serializes as a JSON *string*
   * ({"id":"123"}). Deliberate — JavaScript cannot safely parse 64-bit integers.
   */
  id: string;
  /** Enrichment lifecycle state at ingest time (always "pending" here). */
  enrichmentStatus: string;
}

/**
 * Feedback is a console feedback list row. Post-E3 (metadata-driven
 * Dimensions): the per-row classification lives in `enriched_attrs`, a
 * map<dim.name, value> where value is a JSON string (single-kind dim)
 * or a JSON string array (multi-kind dim). `is_urgent` is a derived
 * boolean persisted at write time.
 */
export interface Feedback {
  /** → JSON string */
  id: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  pageUrl: string;
  enrichedTitle?:
    | string
    | undefined;
  /** map<dim.name, string | repeated string> — the LLM-emitted values. */
  enrichedAttrs?: { [key: string]: any } | undefined;
  isUrgent: boolean;
  /** pending | enriching | done | failed */
  enrichmentStatus: string;
  /** RFC3339 */
  createdAt: string;
  /** ISO 639-1-ish detected source language */
  language?:
    | string
    | undefined;
  /** tenant-locale console title */
  enrichedDisplayTitle?:
    | string
    | undefined;
  /** tenant locale used for display */
  enrichedDisplayLocale?:
    | string
    | undefined;
  /** model self-rated review signal [0,1] */
  classificationConfidence?: number | undefined;
  tags: Tag[];
  workflowState?: WorkflowState | undefined;
  allowedNextStates: WorkflowState[];
  /** Number of enrichment attempts made (0 = never attempted, max 5) */
  enrichmentAttempts?:
    | number
    | undefined;
  /** RFC3339 timestamp of next scheduled retry; absent if terminal or not failed */
  enrichmentNextRetryAt?: string | undefined;
  enrichmentFailureReasonClass?: string | undefined;
  enrichmentFailureModel?: string | undefined;
  enrichmentFailureChannelId?: string | undefined;
  enrichmentFailureChannelName?: string | undefined;
  enrichmentFailureConfigFingerprint?: string | undefined;
  enrichmentFailurePromptVersion?: string | undefined;
}

/** FeedbackDetail is the single-row view: the list fields plus extras (flat). */
export interface FeedbackDetail {
  id: string;
  content: string;
  source: string;
  type: string;
  userId: string;
  pageUrl: string;
  enrichedTitle?: string | undefined;
  enrichedAttrs?: { [key: string]: any } | undefined;
  isUrgent: boolean;
  enrichmentStatus: string;
  createdAt: string;
  sourceMeta?: { [key: string]: any } | undefined;
  attachments: Attachment[];
  enrichmentError?:
    | string
    | undefined;
  /** RFC3339 */
  enrichedAt?:
    | string
    | undefined;
  /**
   * LLM's short "why these values" justification. Already delivered
   * via the outbox envelope; persisted to user_feedback.enriched_rationale
   * by migration 013.
   */
  enrichedRationale?:
    | string
    | undefined;
  /** ISO 639-1-ish detected source language */
  language?:
    | string
    | undefined;
  /** tenant-locale console title */
  enrichedDisplayTitle?:
    | string
    | undefined;
  /** tenant-locale "why these values" */
  enrichedDisplayRationale?:
    | string
    | undefined;
  /** tenant locale used for display */
  enrichedDisplayLocale?:
    | string
    | undefined;
  /** model self-rated review signal [0,1] */
  classificationConfidence?:
    | number
    | undefined;
  /** operator-facing LLM draft (#26); never auto-sent */
  replyDraft?:
    | string
    | undefined;
  /** RFC3339; when the draft was last generated */
  replyDraftGeneratedAt?:
    | string
    | undefined;
  /** tenant opt-in; lets the UI tell off / on-but-empty / has-draft apart */
  replyDraftEnabled: boolean;
  tags: Tag[];
  workflowState?: WorkflowState | undefined;
  allowedNextStates: WorkflowState[];
  /** Number of enrichment attempts made (0 = never attempted, max 5) */
  enrichmentAttempts?:
    | number
    | undefined;
  /** RFC3339 timestamp of next scheduled retry; absent if terminal or not failed */
  enrichmentNextRetryAt?: string | undefined;
  enrichmentFailureReasonClass?: string | undefined;
  enrichmentFailureModel?: string | undefined;
  enrichmentFailureChannelId?: string | undefined;
  enrichmentFailureChannelName?: string | undefined;
  enrichmentFailureConfigFingerprint?: string | undefined;
  enrichmentFailurePromptVersion?: string | undefined;
}

export interface Attachment {
  url: string;
  mime?: string | undefined;
  size?: string | undefined;
}

/**
 * AttrFilter is one per-dim filter in a console list query. The
 * `dim` is a Dimension.Name; `value` is a stable Taxonomy.Value;
 * `multi` says whether the dim is multi-kind (needed because the
 * SQL containment shape differs).
 */
export interface AttrFilter {
  dim: string;
  value: string;
  multi: boolean;
}

export interface ListFeedbackRequest {
  /** last row id; opaque to the client */
  cursor?: string | undefined;
  limit?:
    | number
    | undefined;
  /** Per-dim filters, AND-composed via JSONB containment. */
  attrs: AttrFilter[];
  /** nil = no filter; true = only urgent; false = only non-urgent. */
  urgent?:
    | boolean
    | undefined;
  /** full-text query */
  q?: string | undefined;
  tagId?: string | undefined;
  workflowStateId?: string | undefined;
  workflowCategory?:
    | string
    | undefined;
  /** Filter by enrichment status: "pending" | "enriching" | "done" | "failed" */
  enrichmentStatus?:
    | string
    | undefined;
  /**
   * If true, only return rows where enrichment_status='failed' AND
   * enrichment_attempts >= maxEnrichmentAttempts AND enrichment_next_retry_at IS NULL.
   */
  terminalFailedOnly?: boolean | undefined;
}

export interface ListFeedbackResponse {
  items: Feedback[];
  /** absent when no more pages */
  nextCursor?: string | undefined;
}

export interface GetFeedbackRequest {
  /** path param */
  id: string;
}

/** RegenerateReplyDraftRequest re-runs reply-draft generation for one row (#26). */
export interface RegenerateReplyDraftRequest {
  /** path param */
  id: string;
}

export interface RegenerateReplyDraftResponse {
  replyDraft: string;
  /** RFC3339 */
  replyDraftGeneratedAt: string;
}

/** RetryEnrichmentRequest resets a terminal-failed row for re-enrichment (#81). */
export interface RetryEnrichmentRequest {
  /** path param */
  id: string;
}

export interface RetryEnrichmentResponse {
  id: string;
  /** will be "failed" (sweeper picks it up) */
  enrichmentStatus: string;
  /** will be 0 */
  enrichmentAttempts: number;
  /** RFC3339; will be ~NOW */
  enrichmentNextRetryAt: string;
}

export interface GetFeedbackStatsRequest {
}

export interface GetTerminalFailureWorkbenchRequest {
}

/** ValueCount is one bucket of a per-dim distribution. */
export interface ValueCount {
  value: string;
  count: string;
}

/** DimStats is the per-dim top-values distribution for the stats view. */
export interface DimStats {
  dim: string;
  top: ValueCount[];
}

export interface GetFeedbackStatsResponse {
  periodStart: string;
  periodEnd: string;
  total: string;
  /** One per-dim distribution for every dim the tenant has configured. */
  dims: DimStats[];
  /** Count of is_urgent = true rows within the window. */
  urgentCount: string;
}

export interface TerminalFailureCluster {
  key: string;
  label: string;
  count: string;
  oldestCreatedAt: string;
  newestCreatedAt: string;
  sampleFeedbackIds: string[];
  remediationHint?: string | undefined;
}

export interface GetTerminalFailureWorkbenchResponse {
  periodStart: string;
  periodEnd: string;
  totalTerminalFailures: string;
  oldestCreatedAt?: string | undefined;
  reasonClassClusters: TerminalFailureCluster[];
  modelChannelClusters: TerminalFailureCluster[];
  configFingerprintClusters: TerminalFailureCluster[];
  ageBucketClusters: TerminalFailureCluster[];
}

/**
 * FeedbackService is attune's feedback API. Today it exposes Ingest
 * (POST /v1/feedback/ingest, public, API-key auth); the console feedback reads
 * (list / stats / detail) join it as the migration proceeds.
 *
 * We do NOT generate server stubs — chi routing stays. The google.api.http
 * annotation exists only so protoc-gen-openapi emits the REST path + operation
 * into the OpenAPI document. (ts-proto with onlyTypes ignores this service.)
 */
export interface FeedbackService {
  /**
   * Ingest stores one feedback item and queues it for enrichment.
   *
   * Idempotency: send an `Idempotency-Key` header to make retries safe — a
   * replay with the same key + body returns the original id; the same key with
   * a different body fails 409. Errors use the shared ErrorResponse envelope
   * (`code` from the ErrorCode enum).
   */
  Ingest(request: IngestRequest): Promise<IngestResponse>;
  /** GET /fb/v1/console/feedback (console; session auth) */
  ListFeedback(request: ListFeedbackRequest): Promise<ListFeedbackResponse>;
  /** GET /fb/v1/console/feedback/{id} */
  GetFeedback(request: GetFeedbackRequest): Promise<FeedbackDetail>;
  /** GET /fb/v1/console/feedback/stats */
  GetFeedbackStats(request: GetFeedbackStatsRequest): Promise<GetFeedbackStatsResponse>;
  /** GET /fb/v1/console/feedback/terminal-failures */
  GetTerminalFailureWorkbench(
    request: GetTerminalFailureWorkbenchRequest,
  ): Promise<GetTerminalFailureWorkbenchResponse>;
  /** POST /fb/v1/console/feedback/{id}/reply-draft/regenerate (console; session auth) */
  RegenerateReplyDraft(request: RegenerateReplyDraftRequest): Promise<RegenerateReplyDraftResponse>;
  /**
   * POST /fb/v1/console/feedback/{id}/retry-enrichment (console; session auth)
   * Resets a terminal-failed row so it can be re-enriched.
   */
  RetryEnrichment(request: RetryEnrichmentRequest): Promise<RetryEnrichmentResponse>;
}
