// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/job.proto

/* eslint-disable */
import { type BatchFeedbackResponse } from "./batch";

export const protobufPackage = "attune.v1";

/** JobStatus represents the lifecycle state of an async job. */
export enum JobStatus {
  JOB_STATUS_UNSPECIFIED = "JOB_STATUS_UNSPECIFIED",
  JOB_STATUS_QUEUED = "JOB_STATUS_QUEUED",
  JOB_STATUS_RUNNING = "JOB_STATUS_RUNNING",
  JOB_STATUS_COMPLETED = "JOB_STATUS_COMPLETED",
  JOB_STATUS_FAILED = "JOB_STATUS_FAILED",
  JOB_STATUS_CANCELLED = "JOB_STATUS_CANCELLED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** GetJobStatusRequest fetches the current status of a job. */
export interface GetJobStatusRequest {
  jobId: string;
}

/** JobStatusResponse is the full job status with progress and result. */
export interface JobStatusResponse {
  /** Unique job identifier. */
  jobId: string;
  /** Current job status. */
  status: JobStatus;
  /** Total items to process. */
  total: number;
  /** Items processed so far. */
  progress: number;
  /** Final result (populated when status = COMPLETED). */
  result?:
    | BatchFeedbackResponse
    | undefined;
  /** Error message (populated when status = FAILED). */
  error?:
    | string
    | undefined;
  /** When the job was created (RFC3339). */
  createdAt: string;
  /** When processing started (RFC3339, absent if still queued). */
  startedAt?:
    | string
    | undefined;
  /** When the job finished (RFC3339, absent if still running). */
  completedAt?:
    | string
    | undefined;
  /** When the job status was last updated (RFC3339). */
  updatedAt?:
    | string
    | undefined;
  /** Suggested poll interval in seconds (for long-running jobs). */
  retryAfterSeconds: number;
}

/** ListJobsRequest lists jobs with optional filtering. */
export interface ListJobsRequest {
  /** Filter by status (optional). Values: queued, running, completed, failed, cancelled. */
  status?:
    | string
    | undefined;
  /** Maximum jobs to return (default: 20, max: 100). */
  limit?:
    | number
    | undefined;
  /** Pagination cursor from previous response (job ID). */
  cursor?: string | undefined;
}

/** ListJobsResponse contains the list of jobs. */
export interface ListJobsResponse {
  jobs: JobStatusResponse[];
  /** Cursor for the next page; absent when no more pages. */
  nextCursor?: string | undefined;
}

/** CancelJobRequest cancels a running or queued job. */
export interface CancelJobRequest {
  jobId: string;
}

/** CancelJobResponse confirms cancellation. */
export interface CancelJobResponse {
  /** The status after cancellation attempt. */
  status: JobStatus;
  /** Human-readable result message. */
  message: string;
}

/** JobService provides status tracking for async batch operations (#30). */
export interface JobService {
  GetJobStatus(request: GetJobStatusRequest): Promise<JobStatusResponse>;
  ListJobs(request: ListJobsRequest): Promise<ListJobsResponse>;
  CancelJob(request: CancelJobRequest): Promise<CancelJobResponse>;
}
