// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/mcp_client.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface MCPClient {
  id: string;
  name: string;
  redirectUris: string[];
  scopes: string[];
  toolPolicyMode: string;
  rateLimitRpm?: number | undefined;
  rateLimitBurst?:
    | number
    | undefined;
  /** RFC3339 */
  createdAt: string;
  createdBy: string;
  /** RFC3339 */
  revokedAt?: string | undefined;
}

export interface MCPSession {
  id: string;
  scopes: string[];
  lastToolName: string;
  lastDecision: string;
  lastIp: string;
  lastUserAgent: string;
  /** RFC3339 */
  lastActiveAt: string;
  /** RFC3339 */
  createdAt: string;
  closedReason: string;
  closedBy: string;
  /** RFC3339 */
  closedAt?: string | undefined;
}

export interface MCPRefreshGrant {
  id: string;
  sessionId: string;
  scopes: string[];
  /** RFC3339 */
  expiresAt: string;
  /** RFC3339 */
  createdAt: string;
}

export interface MCPClientToolPolicy {
  name: string;
  requiredScope: string;
  risk: string;
  dataClass: string;
  readOnlyHint: boolean;
  destructiveHint: boolean;
  openWorldHint: boolean;
  defaultRpm: number;
  defaultBurst: number;
  scopeGranted: boolean;
  effectiveAllowed: boolean;
  effect: string;
  rateLimitRpm?: number | undefined;
  rateLimitBurst?: number | undefined;
}

export interface MCPConnectionProfile {
  serverUrl: string;
  resourceUrl: string;
  oauthIssuer: string;
  authorizationEndpoint: string;
  tokenEndpoint: string;
  protectedResourceMetadataUrl: string;
  authorizationServerMetadataUrl: string;
  openidConfigurationUrl: string;
  legacyProtectedResourceMetadataUrl: string;
  legacyAuthorizationServerMetadataUrl: string;
  legacyOpenidConfigurationUrl: string;
}

export interface MCPToolPolicyInput {
  toolName: string;
  effect: string;
  rateLimitRpm?: number | undefined;
  rateLimitBurst?: number | undefined;
}

export interface ListMCPClientsRequest {
}

export interface ListMCPClientsResponse {
  clients: MCPClient[];
}

export interface CreateMCPClientRequest {
  name: string;
  redirectUris: string[];
  scopes: string[];
}

export interface CreateMCPClientResponse {
  client?: MCPClient | undefined;
}

export interface GetMCPClientRequest {
  /** path param (UUID) */
  id: string;
}

export interface GetMCPClientResponse {
  client?: MCPClient | undefined;
  sessions: MCPSession[];
  refreshGrants: MCPRefreshGrant[];
  tools: MCPClientToolPolicy[];
  connection?: MCPConnectionProfile | undefined;
}

export interface RevokeMCPClientRequest {
  /** path param (UUID) */
  id: string;
}

export interface RevokeMCPClientResponse {
}

export interface UpdateMCPClientRequest {
  /** path param (UUID) */
  id: string;
  toolPolicyMode?: string | undefined;
  rateLimitRpm?: number | undefined;
  rateLimitBurst?: number | undefined;
}

export interface UpdateMCPClientResponse {
  client?: MCPClient | undefined;
}

export interface ReplaceMCPClientToolPoliciesRequest {
  /** path param (UUID) */
  id: string;
  policies: MCPToolPolicyInput[];
}

export interface ReplaceMCPClientToolPoliciesResponse {
  tools: MCPClientToolPolicy[];
}

export interface RevokeMCPSessionRequest {
  /** path param (UUID) */
  id: string;
  /** path param (UUID) */
  sessionId: string;
}

export interface RevokeMCPSessionResponse {
}

export interface RevokeMCPRefreshGrantRequest {
  /** path param (UUID) */
  id: string;
  /** path param (UUID) */
  grantId: string;
}

export interface RevokeMCPRefreshGrantResponse {
}

/** MCPClientService manages MCP OAuth clients and their governance surface. */
export interface MCPClientService {
  /** GET /fb/v1/console/mcp/clients */
  ListMCPClients(request: ListMCPClientsRequest): Promise<ListMCPClientsResponse>;
  /** POST /fb/v1/console/mcp/clients */
  CreateMCPClient(request: CreateMCPClientRequest): Promise<CreateMCPClientResponse>;
  /** GET /fb/v1/console/mcp/clients/{id} */
  GetMCPClient(request: GetMCPClientRequest): Promise<GetMCPClientResponse>;
  /** DELETE /fb/v1/console/mcp/clients/{id} */
  RevokeMCPClient(request: RevokeMCPClientRequest): Promise<RevokeMCPClientResponse>;
  /** PATCH /fb/v1/console/mcp/clients/{id} */
  UpdateMCPClient(request: UpdateMCPClientRequest): Promise<UpdateMCPClientResponse>;
  /** PUT /fb/v1/console/mcp/clients/{id}/tool-policies */
  ReplaceMCPClientToolPolicies(
    request: ReplaceMCPClientToolPoliciesRequest,
  ): Promise<ReplaceMCPClientToolPoliciesResponse>;
  /** DELETE /fb/v1/console/mcp/clients/{id}/sessions/{session_id} */
  RevokeMCPSession(request: RevokeMCPSessionRequest): Promise<RevokeMCPSessionResponse>;
  /** DELETE /fb/v1/console/mcp/clients/{id}/grants/{grant_id} */
  RevokeMCPRefreshGrant(request: RevokeMCPRefreshGrantRequest): Promise<RevokeMCPRefreshGrantResponse>;
}
