// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/member.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/** Member represents a user's membership in a tenant. */
export interface Member {
  id: string;
  /** "admin" | "oidc_user" | "tenant_user" | "invite" */
  memberType: string;
  userId: string;
  /** display email (from user record or invite) */
  email: string;
  /** "admin" | "member" | "viewer" */
  role: string;
  /** "idp" | "manual" | "bootstrap" */
  roleSource: string;
  /** unix seconds */
  invitedAt: string;
  /** unix seconds, 0 if pending */
  acceptedAt: string;
}

export interface ListMembersRequest {
}

export interface ListMembersResponse {
  members: Member[];
}

export interface InviteMemberRequest {
  email: string;
  /** "admin" | "member" | "viewer" */
  role: string;
}

export interface InviteMemberResponse {
  member?: Member | undefined;
}

export interface UpdateMemberRoleRequest {
  id: string;
  /** "admin" | "member" | "viewer" */
  role: string;
}

export interface UpdateMemberRoleResponse {
}

export interface RemoveMemberRequest {
  /** path param (UUID) */
  id: string;
}

export interface RemoveMemberResponse {
}

/** MemberService manages tenant membership for RBAC (#38). */
export interface MemberService {
  /** GET /fb/v1/console/members — list all tenant members. */
  ListMembers(request: ListMembersRequest): Promise<ListMembersResponse>;
  /** POST /fb/v1/console/members — invite a new member. */
  InviteMember(request: InviteMemberRequest): Promise<InviteMemberResponse>;
  /** PATCH /fb/v1/console/members/{id} — change role. */
  UpdateMemberRole(request: UpdateMemberRoleRequest): Promise<UpdateMemberRoleResponse>;
  /** DELETE /fb/v1/console/members/{id} — remove from tenant. */
  RemoveMember(request: RemoveMemberRequest): Promise<RemoveMemberResponse>;
}
