// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/outbox.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * OutboxFailureKind is the structured failure classification. Mirrors
 * notify.FailureKind and the notify_outbox.failure_kind CHECK constraint.
 */
export enum OutboxFailureKind {
  OUTBOX_FAILURE_KIND_UNSPECIFIED = "OUTBOX_FAILURE_KIND_UNSPECIFIED",
  OUTBOX_FAILURE_KIND_HTTP_4XX = "OUTBOX_FAILURE_KIND_HTTP_4XX",
  OUTBOX_FAILURE_KIND_HTTP_5XX = "OUTBOX_FAILURE_KIND_HTTP_5XX",
  OUTBOX_FAILURE_KIND_TIMEOUT = "OUTBOX_FAILURE_KIND_TIMEOUT",
  OUTBOX_FAILURE_KIND_DNS = "OUTBOX_FAILURE_KIND_DNS",
  OUTBOX_FAILURE_KIND_CONNECTION = "OUTBOX_FAILURE_KIND_CONNECTION",
  OUTBOX_FAILURE_KIND_TLS = "OUTBOX_FAILURE_KIND_TLS",
  OUTBOX_FAILURE_KIND_TERMINAL = "OUTBOX_FAILURE_KIND_TERMINAL",
  OUTBOX_FAILURE_KIND_OTHER = "OUTBOX_FAILURE_KIND_OTHER",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/**
 * OutboxDelivery is one queued (feedback × destination) delivery row. Timestamps
 * are RFC3339 strings ("" when unset), matching the rest of the console
 * contract.
 */
export interface OutboxDelivery {
  id: string;
  feedbackId: string;
  destinationType: string;
  destinationTarget: string;
  audience: string;
  /** pending | delivered | failed | dead */
  status: string;
  attempts: number;
  failureKind: OutboxFailureKind;
  /** 0 = no response */
  httpStatus: number;
  lastError: string;
  deadReason: string;
  traceId: string;
  nextRetryAt: string;
  createdAt: string;
  deliveredAt: string;
  lastManualRetryAt: string;
  retriedBy: string;
  manualRetryCount: number;
  /** a worker currently holds the row (claimed_at set) */
  inFlight: boolean;
}

export interface ListDeliveriesRequest {
  /** empty → ["dead"] */
  status: string[];
  /** clamped server-side to [1,200] */
  limit: number;
  /** keyset cursor; 0 = first page */
  beforeId: string;
}

export interface ListDeliveriesResponse {
  deliveries: OutboxDelivery[];
  /** 0 when there are no more pages */
  nextBeforeId: string;
}

export interface RetryDeliveryRequest {
  id: string;
}

export interface RetryDeliveryResponse {
  delivery?: OutboxDelivery | undefined;
}

/**
 * NotifyOutboxService is the operator surface over the notify_outbox delivery
 * queue (#33): list dead / in-flight-failed deliveries and manually retry one
 * in place. The retry/backoff/dead engine itself lives in the worker; this
 * contract only exposes visibility + manual re-arm.
 */
export interface NotifyOutboxService {
  /**
   * List deliveries for the caller's tenant, filtered by status (defaults to
   * dead when none given), newest first, keyset-paginated on id.
   */
  ListDeliveries(request: ListDeliveriesRequest): Promise<ListDeliveriesResponse>;
  /**
   * Manually re-arm one dead/failed delivery (retry-in-place). Asynchronous:
   * the worker redelivers on its next poll, so a successful call is 202.
   */
  RetryDelivery(request: RetryDeliveryRequest): Promise<RetryDeliveryResponse>;
}
