// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/public_visibility.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum PublicSurface {
  PUBLIC_SURFACE_UNSPECIFIED = "PUBLIC_SURFACE_UNSPECIFIED",
  PUBLIC_SURFACE_REQUEST = "PUBLIC_SURFACE_REQUEST",
  PUBLIC_SURFACE_REQUEST_COMMENT = "PUBLIC_SURFACE_REQUEST_COMMENT",
  PUBLIC_SURFACE_ROADMAP_ITEM = "PUBLIC_SURFACE_ROADMAP_ITEM",
  PUBLIC_SURFACE_CHANGELOG_POST = "PUBLIC_SURFACE_CHANGELOG_POST",
  PUBLIC_SURFACE_PORTAL_SUBMISSION = "PUBLIC_SURFACE_PORTAL_SUBMISSION",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ModerationState {
  MODERATION_STATE_UNSPECIFIED = "MODERATION_STATE_UNSPECIFIED",
  MODERATION_STATE_PENDING = "MODERATION_STATE_PENDING",
  MODERATION_STATE_APPROVED = "MODERATION_STATE_APPROVED",
  MODERATION_STATE_REJECTED = "MODERATION_STATE_REJECTED",
  MODERATION_STATE_HIDDEN = "MODERATION_STATE_HIDDEN",
  MODERATION_STATE_SPAM = "MODERATION_STATE_SPAM",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum PublicIdentityMode {
  PUBLIC_IDENTITY_MODE_UNSPECIFIED = "PUBLIC_IDENTITY_MODE_UNSPECIFIED",
  PUBLIC_IDENTITY_MODE_ANONYMOUS = "PUBLIC_IDENTITY_MODE_ANONYMOUS",
  PUBLIC_IDENTITY_MODE_DISPLAY_NAME = "PUBLIC_IDENTITY_MODE_DISPLAY_NAME",
  PUBLIC_IDENTITY_MODE_ORGANIZATION = "PUBLIC_IDENTITY_MODE_ORGANIZATION",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum PublicAccessMode {
  PUBLIC_ACCESS_MODE_UNSPECIFIED = "PUBLIC_ACCESS_MODE_UNSPECIFIED",
  PUBLIC_ACCESS_MODE_DISABLED = "PUBLIC_ACCESS_MODE_DISABLED",
  PUBLIC_ACCESS_MODE_PUBLIC = "PUBLIC_ACCESS_MODE_PUBLIC",
  PUBLIC_ACCESS_MODE_AUTHENTICATED = "PUBLIC_ACCESS_MODE_AUTHENTICATED",
  PUBLIC_ACCESS_MODE_INVITE_ONLY = "PUBLIC_ACCESS_MODE_INVITE_ONLY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum PublicWriteMode {
  PUBLIC_WRITE_MODE_UNSPECIFIED = "PUBLIC_WRITE_MODE_UNSPECIFIED",
  PUBLIC_WRITE_MODE_DISABLED = "PUBLIC_WRITE_MODE_DISABLED",
  PUBLIC_WRITE_MODE_ANONYMOUS = "PUBLIC_WRITE_MODE_ANONYMOUS",
  PUBLIC_WRITE_MODE_IDENTIFIED = "PUBLIC_WRITE_MODE_IDENTIFIED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface PublicVisibilityPolicy {
  tenantId: string;
  portalAccessMode: PublicAccessMode;
  searchIndexingEnabled: boolean;
  requestsEnabled: boolean;
  commentsEnabled: boolean;
  roadmapEnabled: boolean;
  changelogEnabled: boolean;
  submissionWriteMode: PublicWriteMode;
  commentWriteMode: PublicWriteMode;
  voteWriteMode: PublicWriteMode;
  defaultRequestState: ModerationState;
  defaultCommentState: ModerationState;
  submitterIdentityMode: PublicIdentityMode;
  showVoteCount: boolean;
  showCommentCount: boolean;
  showSubmitterDisplay: boolean;
  hidePublicTimestamps: boolean;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetPublicVisibilityPolicyRequest {
}

export interface UpdatePublicVisibilityPolicyRequest {
  portalAccessMode: PublicAccessMode;
  searchIndexingEnabled: boolean;
  requestsEnabled: boolean;
  commentsEnabled: boolean;
  roadmapEnabled: boolean;
  changelogEnabled: boolean;
  submissionWriteMode: PublicWriteMode;
  commentWriteMode: PublicWriteMode;
  voteWriteMode: PublicWriteMode;
  defaultRequestState: ModerationState;
  defaultCommentState: ModerationState;
  submitterIdentityMode: PublicIdentityMode;
  showVoteCount: boolean;
  showCommentCount: boolean;
  showSubmitterDisplay: boolean;
  hidePublicTimestamps: boolean;
}

export interface ListModerationSubjectsRequest {
  surface: PublicSurface[];
  state: ModerationState[];
  limit: number;
  cursor: string;
}

export interface ListModerationSubjectsResponse {
  subjects: ModerationSubject[];
  nextCursor?: string | undefined;
}

export interface ModerationSubject {
  id: string;
  tenantId: string;
  surface: PublicSurface;
  subjectId: string;
  state: ModerationState;
  reasonCode: string;
  reasonNote: string;
  submittedByDisplay: string;
  reviewedBy: string;
  reviewedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface ApproveModerationSubjectRequest {
  id: string;
  reasonCode: string;
  reasonNote: string;
}

export interface RejectModerationSubjectRequest {
  id: string;
  reasonCode: string;
  reasonNote: string;
}

export interface HideModerationSubjectRequest {
  id: string;
  reasonCode: string;
  reasonNote: string;
}

export interface MarkModerationSubjectSpamRequest {
  id: string;
  reasonCode: string;
  reasonNote: string;
}

export interface RestoreModerationSubjectRequest {
  id: string;
  reasonCode: string;
  reasonNote: string;
}

export interface PublicRequestProfile {
  id: string;
  tenantId: string;
  requestId: string;
  publicSlug: string;
  publicTitle: string;
  publicSummary: string;
  publicState: string;
  roadmapColumn: string;
  includedInPortal: boolean;
  includedInRoadmap: boolean;
  publishedAt?: string | undefined;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface PublicRequestPublication {
  profile?: PublicRequestProfile | undefined;
  moderation?: ModerationSubject | undefined;
}

export interface GetPublicRequestProfileRequest {
  requestId: string;
}

export interface UpsertPublicRequestProfileRequest {
  requestId: string;
  publicSlug: string;
  publicTitle: string;
  publicSummary: string;
  publicState: string;
  roadmapColumn: string;
  includedInPortal: boolean;
  includedInRoadmap: boolean;
  submittedByDisplay: string;
}

export interface GetPublicCustomerRequestRequest {
  tenantSlug: string;
  publicSlug: string;
}

export interface ListPublicCustomerRequestsRequest {
  tenantSlug: string;
  limit: number;
  cursor: string;
}

export interface ListPublicCustomerRequestsResponse {
  requests: PublicCustomerRequestSummary[];
  nextCursor?: string | undefined;
}

export interface ListPublicRoadmapRequest {
  tenantSlug: string;
  limit: number;
  cursor: string;
}

export interface PublicRoadmapColumn {
  name: string;
  requests: PublicCustomerRequestSummary[];
}

export interface ListPublicRoadmapResponse {
  columns: PublicRoadmapColumn[];
  nextCursor?: string | undefined;
}

export interface PublicCustomerRequestSummary {
  id: string;
  slug: string;
  title: string;
  summary: string;
  state: string;
  roadmapColumn: string;
  voteCount?: number | undefined;
  commentCount?: number | undefined;
  submittedByDisplay?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

export interface PublicCustomerRequestDetail {
  request?: PublicCustomerRequestSummary | undefined;
  links: string[];
}

export interface PublicVisibilityService {
  GetPublicVisibilityPolicy(request: GetPublicVisibilityPolicyRequest): Promise<PublicVisibilityPolicy>;
  UpdatePublicVisibilityPolicy(request: UpdatePublicVisibilityPolicyRequest): Promise<PublicVisibilityPolicy>;
  ListModerationSubjects(request: ListModerationSubjectsRequest): Promise<ListModerationSubjectsResponse>;
  GetPublicRequestProfile(request: GetPublicRequestProfileRequest): Promise<PublicRequestPublication>;
  UpsertPublicRequestProfile(request: UpsertPublicRequestProfileRequest): Promise<PublicRequestPublication>;
  ApproveModerationSubject(request: ApproveModerationSubjectRequest): Promise<ModerationSubject>;
  RejectModerationSubject(request: RejectModerationSubjectRequest): Promise<ModerationSubject>;
  HideModerationSubject(request: HideModerationSubjectRequest): Promise<ModerationSubject>;
  MarkModerationSubjectSpam(request: MarkModerationSubjectSpamRequest): Promise<ModerationSubject>;
  RestoreModerationSubject(request: RestoreModerationSubjectRequest): Promise<ModerationSubject>;
}

export interface PortalService {
  ListPublicCustomerRequests(request: ListPublicCustomerRequestsRequest): Promise<ListPublicCustomerRequestsResponse>;
  GetPublicCustomerRequest(request: GetPublicCustomerRequestRequest): Promise<PublicCustomerRequestDetail>;
  ListPublicRoadmap(request: ListPublicRoadmapRequest): Promise<ListPublicRoadmapResponse>;
}
