// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/quality_action.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export interface ListQualityActionsRequest {
  status: string;
  limit?: number | undefined;
}

export interface ListQualityActionsResponse {
  actions: QualityAction[];
}

export interface UpdateQualityActionRequest {
  actionKey: string;
  signal: string;
  status: string;
  severity: string;
  targetPath: string;
  metricLabel: string;
  metricValue: string;
  recommendationKey: string;
  evidenceJson: string;
}

export interface UpdateQualityActionResponse {
  action?: QualityAction | undefined;
}

export interface QualityAction {
  actionId: string;
  actionKey: string;
  signal: string;
  status: string;
  severity: string;
  targetPath: string;
  metricLabel: string;
  metricValue: string;
  recommendationKey: string;
  evidenceJson: string;
  createdAt: string;
  lastSeenAt: string;
  acknowledgedAt: string;
  resolvedAt: string;
  dismissedAt: string;
  updatedAt: string;
  updatedBy: string;
}

/**
 * QualityActionService stores the operator action ledger behind the control
 * tower. Signals still come from the dedicated quality APIs; this service keeps
 * the human workflow state for each recommended action.
 */
export interface QualityActionService {
  ListQualityActions(request: ListQualityActionsRequest): Promise<ListQualityActionsResponse>;
  UpdateQualityAction(request: UpdateQualityActionRequest): Promise<UpdateQualityActionResponse>;
}
