// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/request_notification.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

export enum RequestNotificationEventType {
  REQUEST_NOTIFICATION_EVENT_TYPE_UNSPECIFIED = "REQUEST_NOTIFICATION_EVENT_TYPE_UNSPECIFIED",
  REQUEST_NOTIFICATION_EVENT_TYPE_STATUS_CHANGED = "REQUEST_NOTIFICATION_EVENT_TYPE_STATUS_CHANGED",
  REQUEST_NOTIFICATION_EVENT_TYPE_SHIPPED = "REQUEST_NOTIFICATION_EVENT_TYPE_SHIPPED",
  REQUEST_NOTIFICATION_EVENT_TYPE_NEED_INFO_DIRECT = "REQUEST_NOTIFICATION_EVENT_TYPE_NEED_INFO_DIRECT",
  REQUEST_NOTIFICATION_EVENT_TYPE_MODERATOR_RESPONSE = "REQUEST_NOTIFICATION_EVENT_TYPE_MODERATOR_RESPONSE",
  REQUEST_NOTIFICATION_EVENT_TYPE_CHANGELOG_POST_PUBLISHED = "REQUEST_NOTIFICATION_EVENT_TYPE_CHANGELOG_POST_PUBLISHED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RequestNotificationChannel {
  REQUEST_NOTIFICATION_CHANNEL_UNSPECIFIED = "REQUEST_NOTIFICATION_CHANNEL_UNSPECIFIED",
  REQUEST_NOTIFICATION_CHANNEL_EMAIL = "REQUEST_NOTIFICATION_CHANNEL_EMAIL",
  REQUEST_NOTIFICATION_CHANNEL_WEBHOOK = "REQUEST_NOTIFICATION_CHANNEL_WEBHOOK",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface RequestNotificationSettings {
  tenantId: string;
  emailEnabled: boolean;
  webhookEnabled: boolean;
  enabledEventTypes?: { [key: string]: any } | undefined;
  statusPolicy?: { [key: string]: any } | undefined;
  defaultConsentMode: string;
  requirePublicUpdateForStatus: boolean;
  maxRecipientsWithoutConfirm: number;
  tenantHourlySendLimit: number;
  contactDailySendLimit: number;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetRequestNotificationSettingsRequest {
}

export interface UpdateRequestNotificationSettingsRequest {
  emailEnabled?: boolean | undefined;
  webhookEnabled?: boolean | undefined;
  enabledEventTypes?: { [key: string]: any } | undefined;
  statusPolicy?: { [key: string]: any } | undefined;
  defaultConsentMode?: string | undefined;
  requirePublicUpdateForStatus?: boolean | undefined;
  maxRecipientsWithoutConfirm?: number | undefined;
  tenantHourlySendLimit?: number | undefined;
  contactDailySendLimit?: number | undefined;
}

export interface RequestNotificationSender {
  id: string;
  fromName: string;
  fromEmailRedacted: string;
  replyToRedacted: string;
  domain: string;
  dkimStatus: string;
  spfStatus: string;
  dmarcStatus: string;
  provider: string;
  status: string;
  verifiedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface GetRequestNotificationSenderRequest {
}

export interface UpsertRequestNotificationSenderRequest {
  fromName: string;
  fromEmail: string;
  replyTo?: string | undefined;
  provider: string;
  providerUrl: string;
  providerSecret?: string | undefined;
}

export interface VerifyRequestNotificationSenderRequest {
  id: string;
}

export interface RequestNotificationWebhookTarget {
  id: string;
  name: string;
  url: string;
  urlHost: string;
  signatureVersion: string;
  eventMask?: { [key: string]: any } | undefined;
  includeRecipientIdentity: boolean;
  status: string;
  verifiedAt?: string | undefined;
  lastTestedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface ListRequestNotificationWebhookTargetsRequest {
}

export interface ListRequestNotificationWebhookTargetsResponse {
  targets: RequestNotificationWebhookTarget[];
}

export interface CreateRequestNotificationWebhookTargetRequest {
  name: string;
  url: string;
  secret?: string | undefined;
  eventMask?: { [key: string]: any } | undefined;
  includeRecipientIdentity: boolean;
}

export interface UpdateRequestNotificationWebhookTargetRequest {
  id: string;
  name?: string | undefined;
  url?: string | undefined;
  secret?: string | undefined;
  eventMask?: { [key: string]: any } | undefined;
  includeRecipientIdentity?: boolean | undefined;
  status?: string | undefined;
}

export interface DeleteRequestNotificationWebhookTargetRequest {
  id: string;
}

export interface DeleteRequestNotificationWebhookTargetResponse {
}

export interface TestRequestNotificationWebhookTargetRequest {
  id: string;
}

export interface RequestNotificationWebhookTestResult {
  ok: boolean;
  statusCode?: number | undefined;
  latencyMs?: string | undefined;
  message: string;
}

export interface RequestNotificationUpdateDraft {
  requestId: string;
  title: string;
  body: string;
  kind: string;
  notifySubscribers: boolean;
}

export interface PreviewRequestNotificationRequest {
  update?: RequestNotificationUpdateDraft | undefined;
  channels: RequestNotificationChannel[];
}

export interface PreviewRequestNotificationResponse {
  eligibleRecipients: number;
  excludedRecipients: number;
  excludedByReason?: { [key: string]: any } | undefined;
  emailPayload?: { [key: string]: any } | undefined;
  webhookPayload?: { [key: string]: any } | undefined;
}

export interface PublishRequestUpdateRequest {
  update?: RequestNotificationUpdateDraft | undefined;
  channels: RequestNotificationChannel[];
  confirmLargeAudience: boolean;
}

export interface RequestNotificationEvent {
  id: string;
  eventType: RequestNotificationEventType;
  status: string;
  requestId?: string | undefined;
  updateId?: string | undefined;
  directFollowupId?: string | undefined;
  dedupeKey: string;
  recipientSnapshot?: { [key: string]: any } | undefined;
  createdAt: string;
}

export interface RequestNotificationDelivery {
  id: string;
  eventId: string;
  channel: RequestNotificationChannel;
  status: string;
  attempts: number;
  failureKind: string;
  httpStatus?: number | undefined;
  lastError: string;
  deadReason: string;
  traceId: string;
  destinationHash: string;
  createdAt: string;
  deliveredAt?: string | undefined;
  nextRetryAt?: string | undefined;
  lastManualRetryAt?: string | undefined;
  retriedBy: string;
  manualRetryCount: number;
  payload?: { [key: string]: any } | undefined;
}

export interface ListRequestNotificationDeliveriesRequest {
  status: string[];
  limit: number;
  beforeId: string;
  requestId?: string | undefined;
  channel?: RequestNotificationChannel | undefined;
}

export interface ListRequestNotificationDeliveriesResponse {
  deliveries: RequestNotificationDelivery[];
  nextBeforeId: string;
}

export interface RetryRequestNotificationDeliveryRequest {
  id: string;
}

export interface ListRequestSubscribersRequest {
  requestId: string;
}

export interface ListRequestSubscribersResponse {
  subscribers: RequestSubscriber[];
}

export interface RequestSubscriber {
  contactId: string;
  displayName: string;
  organization: string;
  emailRedacted: string;
  consentState: string;
  subscriptionStatus: string;
  sources: string[];
  createdAt?: string | undefined;
  unsubscribedAt?: string | undefined;
}

export interface SuppressRequestSubscriberRequest {
  contactId: string;
  reason: string;
}

export interface RecordRequestNotificationProviderEventRequest {
  email: string;
  eventType: string;
  reason: string;
  provider: string;
  providerMessageId: string;
}

export interface SubscribePublicCustomerRequestRequest {
  tenantSlug: string;
  publicSlug: string;
  email: string;
  notifyMe: boolean;
  notificationConsentTextVersion: string;
  displayName: string;
  organization: string;
  locale: string;
  timezone: string;
}

export interface UnsubscribePublicCustomerRequestRequest {
  tenantSlug: string;
  token: string;
  scope: string;
}

export interface ConfirmPublicNotificationContactRequest {
  tenantSlug: string;
  token: string;
}

export interface PublicRequestSubscription {
  id: string;
  requestId: string;
  status: string;
  scope: string;
  emailRedacted: string;
}

export interface PublicNotificationContact {
  id: string;
  emailRedacted: string;
  consentState: string;
  verified: boolean;
}

export interface RequestNotificationService {
  GetRequestNotificationSettings(request: GetRequestNotificationSettingsRequest): Promise<RequestNotificationSettings>;
  UpdateRequestNotificationSettings(
    request: UpdateRequestNotificationSettingsRequest,
  ): Promise<RequestNotificationSettings>;
  GetRequestNotificationSender(request: GetRequestNotificationSenderRequest): Promise<RequestNotificationSender>;
  UpsertRequestNotificationSender(request: UpsertRequestNotificationSenderRequest): Promise<RequestNotificationSender>;
  VerifyRequestNotificationSender(request: VerifyRequestNotificationSenderRequest): Promise<RequestNotificationSender>;
  ListRequestNotificationWebhookTargets(
    request: ListRequestNotificationWebhookTargetsRequest,
  ): Promise<ListRequestNotificationWebhookTargetsResponse>;
  CreateRequestNotificationWebhookTarget(
    request: CreateRequestNotificationWebhookTargetRequest,
  ): Promise<RequestNotificationWebhookTarget>;
  UpdateRequestNotificationWebhookTarget(
    request: UpdateRequestNotificationWebhookTargetRequest,
  ): Promise<RequestNotificationWebhookTarget>;
  DeleteRequestNotificationWebhookTarget(
    request: DeleteRequestNotificationWebhookTargetRequest,
  ): Promise<DeleteRequestNotificationWebhookTargetResponse>;
  TestRequestNotificationWebhookTarget(
    request: TestRequestNotificationWebhookTargetRequest,
  ): Promise<RequestNotificationWebhookTestResult>;
  PreviewRequestNotification(request: PreviewRequestNotificationRequest): Promise<PreviewRequestNotificationResponse>;
  PublishRequestUpdate(request: PublishRequestUpdateRequest): Promise<RequestNotificationEvent>;
  ListRequestNotificationDeliveries(
    request: ListRequestNotificationDeliveriesRequest,
  ): Promise<ListRequestNotificationDeliveriesResponse>;
  RetryRequestNotificationDelivery(
    request: RetryRequestNotificationDeliveryRequest,
  ): Promise<RequestNotificationDelivery>;
  ListRequestSubscribers(request: ListRequestSubscribersRequest): Promise<ListRequestSubscribersResponse>;
  SuppressRequestSubscriber(request: SuppressRequestSubscriberRequest): Promise<RequestSubscriber>;
  RecordRequestNotificationProviderEvent(
    request: RecordRequestNotificationProviderEventRequest,
  ): Promise<RequestSubscriber>;
}

export interface PublicRequestNotificationService {
  SubscribePublicCustomerRequest(request: SubscribePublicCustomerRequestRequest): Promise<PublicRequestSubscription>;
  UnsubscribePublicCustomerRequest(
    request: UnsubscribePublicCustomerRequestRequest,
  ): Promise<PublicRequestSubscription>;
  ConfirmPublicNotificationContact(
    request: ConfirmPublicNotificationContactRequest,
  ): Promise<PublicNotificationContact>;
}
