// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: attune/v1/webhook_subscription.proto

/* eslint-disable */

export const protobufPackage = "attune.v1";

/**
 * WebhookSubscription never carries the secret — it is write-only once
 * stored (same rule as NotifyTarget).
 */
export interface WebhookSubscription {
  id: string;
  targetUrl: string;
  /** append-only vocabulary */
  eventTypes: string[];
  /** active | disabled */
  status: string;
  /** e.g. "gone" (consumer answered HTTP 410) */
  disabledReason: string;
  /** zapier | generic */
  consumer: string;
  /** RFC3339 */
  createdAt: string;
}

export interface CreateWebhookSubscriptionRequest {
  /** HTTPS (loopback exemption per config) */
  targetUrl: string;
  eventTypes: string[];
  /** >= 16 chars when provided; server generates when empty */
  secret: string;
  /** default "generic" */
  consumer: string;
}

export interface ListWebhookSubscriptionsRequest {
}

export interface ListWebhookSubscriptionsResponse {
  subscriptions: WebhookSubscription[];
}

export interface DeleteWebhookSubscriptionRequest {
  id: string;
}

export interface DeleteWebhookSubscriptionResponse {
}

export interface ListWebhookSamplesRequest {
  eventType: string;
}

/**
 * Samples are envelope objects returned as raw JSON structs so the envelope
 * (built by the delivery pipeline) stays the single source of truth.
 */
export interface ListWebhookSamplesResponse {
  samples: { [key: string]: any }[];
}

/**
 * WebhookSubscriptionService manages automation webhook subscriptions
 * (e.g. Zapier REST hooks) over API-key auth, scope hooks:manage.
 * One subscription per consumer hook; event_types filters the append-only
 * automation event vocabulary (feedback.created, feedback.urgent,
 * request.created, request.status_changed).
 */
export interface WebhookSubscriptionService {
  /** POST /v1/hooks (201) */
  CreateWebhookSubscription(request: CreateWebhookSubscriptionRequest): Promise<WebhookSubscription>;
  /** GET /v1/hooks */
  ListWebhookSubscriptions(request: ListWebhookSubscriptionsRequest): Promise<ListWebhookSubscriptionsResponse>;
  /** DELETE /v1/hooks/{id} (204) */
  DeleteWebhookSubscription(request: DeleteWebhookSubscriptionRequest): Promise<DeleteWebhookSubscriptionResponse>;
  /**
   * GET /v1/hooks/samples/{event_type} — recent real events (or a canned
   * static sample when the tenant has none), reverse-chronological, each
   * item schema-identical to the live webhook payload. Serves as the
   * Zapier performList endpoint.
   */
  ListWebhookSamples(request: ListWebhookSamplesRequest): Promise<ListWebhookSamplesResponse>;
}
