{{- if and .Values.workload.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "attune.fullname" . }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "attune.appSelectorLabels" . | nindent 6 }}
{{- end }}
