{{- if and .Values.postgres.embedded.enabled (not .Values.postgres.embedded.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attune.postgresSecretName" . }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  {{ .Values.postgres.embedded.auth.secretKeys.username }}: {{ .Values.postgres.embedded.auth.username | quote }}
  {{ .Values.postgres.embedded.auth.secretKeys.password }}: {{ default "" .Values.postgres.embedded.auth.password | quote }}
  {{ .Values.postgres.embedded.auth.secretKeys.database }}: {{ .Values.postgres.embedded.auth.database | quote }}
{{- end }}
