// Code generated by go run ./internal/tools/observabilitydash. Do not edit by hand.

export type ReliabilityScope = 'tenant' | 'global' | 'destination_type'
export type ReliabilityBurnKind = 'error' | 'success'

export interface ReliabilityCatalogEntry {
  key: string
  alertName: string
  title: string
  owner: string
  escalation: string
  scope: ReliabilityScope
  alertLabel: string
  objective: number
  burnKind: ReliabilityBurnKind
  recordedRatioBase: string
  overviewDescription: string
  budgetExceptionPolicy: string
  budgetExceptionNote: string
  policySummary: string
  policyNote: string
  trendLegendBase: string
  tenantRankLegendBase?: string
  includeInTenantRank: boolean
}

export const reliabilityCatalog = [
  {
    key: 'ingest_service',
    alertName: 'AttuneIngestServiceFastBurn',
    title: 'Ingest burn x',
    owner: 'Ingest',
    escalation: 'Ingest on-call',
    scope: 'tenant',
    alertLabel: 'ingest_service',
    objective: 0.999,
    burnKind: 'error',
    recordedRatioBase: 'attune:ingest_service_failure_ratio',
    overviewDescription:
      'Fast burn multiplier for ingest internal errors and rate-limit pressure. 1x means the budget is being consumed at the planned rate; 14.4x is the classic 30d fast-burn page threshold.',
    budgetExceptionPolicy: 'Maintenance windows only',
    budgetExceptionNote:
      'Use only for approved deploy or maintenance windows; validation failures and rate-limit pressure stay in burn.',
    policySummary:
      'Start at 99.9% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Keep validation failures diagnostic and fold rate-limit pressure into the service-owned failure ratio.',
    trendLegendBase: 'ingest',
    tenantRankLegendBase: 'ingest',
    includeInTenantRank: true,
  },
  {
    key: 'enrichment_latency',
    alertName: 'AttuneEnrichmentFastBurn',
    title: 'Enrich burn x',
    owner: 'AI Pipeline',
    escalation: 'AI Pipeline on-call',
    scope: 'tenant',
    alertLabel: 'enrichment_latency',
    objective: 0.95,
    burnKind: 'success',
    recordedRatioBase: 'attune:enrich_success_under_5s',
    overviewDescription:
      'Fast burn multiplier for enrichment attempts that miss the 5s success target. This is the main user-facing latency SLO.',
    budgetExceptionPolicy: 'No standing exclusions',
    budgetExceptionNote:
      'Transient provider slowness stays in burn; use a time-boxed exception only for planned model or provider migrations.',
    policySummary:
      'Start at 95.0% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Measure end-to-end completion within 5s so the SLI matches the user-visible latency experience.',
    trendLegendBase: 'enrich',
    tenantRankLegendBase: 'enrich',
    includeInTenantRank: true,
  },
  {
    key: 'outbox_delivery',
    alertName: 'AttuneOutboxDeliveryFastBurn',
    title: 'Outbox burn x',
    owner: 'Delivery',
    escalation: 'Delivery on-call',
    scope: 'destination_type',
    alertLabel: 'outbox_delivery',
    objective: 0.999,
    burnKind: 'error',
    recordedRatioBase: 'attune:outbox_delivery_failure_ratio',
    overviewDescription:
      'Fast burn multiplier for terminal delivery failures. Pair this with outbox lag to tell destination rejection from worker pressure.',
    budgetExceptionPolicy: 'Destination-maintenance only',
    budgetExceptionNote:
      'Only exclude destination-side maintenance with owner approval; worker lag and dead rows stay in burn.',
    policySummary:
      'Start at 99.9% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Pair the failure ratio with lag and dead rows to distinguish destination rejection from worker pressure.',
    trendLegendBase: 'outbox',
    includeInTenantRank: false,
  },
  {
    key: 'oidc_login',
    alertName: 'AttuneOIDCLoginFastBurn',
    title: 'OIDC burn x',
    owner: 'Auth',
    escalation: 'Auth on-call',
    scope: 'global',
    alertLabel: 'oidc_login',
    objective: 0.999,
    burnKind: 'error',
    recordedRatioBase: 'attune:oidc_login_failure_ratio',
    overviewDescription:
      'Fast burn multiplier for failed sign-in attempts. This is a service-owned authentication reliability signal.',
    budgetExceptionPolicy: 'IdP-maintenance only',
    budgetExceptionNote:
      'Controlled IdP changes may be excluded when they are approved and time-boxed; implementation regressions remain in burn.',
    policySummary:
      'Start at 99.9% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Treat failed sign-ins as a service-owned reliability signal while keeping IdP outages visible.',
    trendLegendBase: 'oidc',
    includeInTenantRank: false,
  },
  {
    key: 'apikey_access',
    alertName: 'AttuneAPIKeyAccessFastBurn',
    title: 'API key burn x',
    owner: 'Security',
    escalation: 'Security on-call',
    scope: 'global',
    alertLabel: 'apikey_access',
    objective: 0.95,
    burnKind: 'error',
    recordedRatioBase: 'attune:apikey_access_denial_ratio',
    overviewDescription:
      'Fast burn multiplier for access denials on active API keys. Keep this separate from authz denials so policy-driven rejections stay explainable.',
    budgetExceptionPolicy: 'No standing exclusions',
    budgetExceptionNote:
      'Policy-driven denials are diagnostic signals, not error-budget events, so do not file budget exceptions for them.',
    policySummary:
      'Start at 95.0% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Keep API-key access denials separate from role-based authorization denials so governance changes stay explainable.',
    trendLegendBase: 'apikey',
    includeInTenantRank: false,
  },
  {
    key: 'mcp_tool',
    alertName: 'AttuneMCPToolFastBurn',
    title: 'MCP burn x',
    owner: 'MCP',
    escalation: 'MCP on-call',
    scope: 'tenant',
    alertLabel: 'mcp_tool',
    objective: 0.999,
    burnKind: 'error',
    recordedRatioBase: 'attune:mcp_tool_error_ratio',
    overviewDescription:
      'Fast burn multiplier for MCP tool-call failures. Use this with tool mix and latency to separate tool regressions from policy pressure.',
    budgetExceptionPolicy: 'Tool-migration only',
    budgetExceptionNote:
      'Use a time-boxed exclusion only when a tool or adapter is being intentionally rotated; policy denials remain in burn.',
    policySummary:
      'Start at 99.9% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Use tool mix and latency alongside burn rate to tell policy pressure from tool regressions.',
    trendLegendBase: 'mcp',
    tenantRankLegendBase: 'mcp',
    includeInTenantRank: true,
  },
  {
    key: 'gdpr_job',
    alertName: 'AttuneGDPRJobFastBurn',
    title: 'GDPR burn x',
    owner: 'Compliance',
    escalation: 'Compliance on-call',
    scope: 'tenant',
    alertLabel: 'gdpr_job',
    objective: 0.999,
    burnKind: 'success',
    recordedRatioBase: 'attune:gdpr_job_completion_ratio',
    overviewDescription:
      'Fast burn multiplier for GDPR jobs that miss completion. Cancelled and revoked jobs are excluded from the denominator so the lens stays operational.',
    budgetExceptionPolicy: 'Denominator already excludes cancellations',
    budgetExceptionNote:
      'Cancelled and revoked jobs are already excluded from the burn denominator; file a budget exception only if the legal workflow changes.',
    policySummary:
      'Start at 99.9% objective; page at 14.4x on 5m and 1h; warn at 6x on 30m and 6h; keep traffic floor > 0.01.',
    policyNote:
      'Keep cancelled and revoked jobs out of the completion denominator so the burn reflects active requests.',
    trendLegendBase: 'gdpr',
    tenantRankLegendBase: 'gdpr',
    includeInTenantRank: true,
  },
] as const satisfies readonly ReliabilityCatalogEntry[]

export type ReliabilityCatalogEntryValue = (typeof reliabilityCatalog)[number]
