-- Migration 001: listen 独立 RDS 完整 init schema.
--
-- Wave 1.2 起 listen 跑在自己的独立 PG database 上（阿里云 RDS
-- listen），不再寄生主项目 schema。这里建出 listen 需要的全部三张
-- 基础表：tenants / user_feedback / external_api_keys.
--
-- Schema 决策（与主项目同名表的差异）：
--
-- 1. tenants：删 `_platform_` sentinel——listen 是纯多租户 SaaS,
--    没有"全局 admin"概念。每条 feedback 都属于一个真实租户。
-- 2. tenants.id 用 TEXT(uuid)——保持与现有 listen 代码 string 处理
--    一致；UUID 算法生成但字符串存储。
-- 3. tenants 新加 `lark_tenant_key TEXT UNIQUE`——Wave 2 OAuth 接入
--    时填充飞书 tenant_key. 让外部 ID 与内部 PK 解耦（反模式：让
--    PK 依赖外部系统的命名）。
-- 4. user_feedback.tenant_id 改为 NOT NULL + FK——独立 RDS 没有
--    legacy null 行；任何写入必须先 ResolveSlug 到 tenant_id.
-- 5. enrichment_claimed_at / lark_*_claimed_at 等列直接在 CREATE
--    TABLE 里包含——migration 002/003 在新 RDS 上是 idempotent
--    no-op，但保留以便向后兼容（如果有人重新 init 老 RDS）。
--
-- 律 5 稳定性：002-005 全部 IF (NOT) EXISTS，新 RDS 上跑过 001 后
-- 它们都是 no-op；老共享 RDS 仍可独立演进。

BEGIN;

-- ─── 1. tenants ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tenants (
    -- UUID generated by PG; stored as TEXT to keep one type across
    -- application code that's already string-typed.
    id              TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::text,
    -- Business-readable handle. Used by config (lark_default_tenant_slug,
    -- custom_webhooks[].tenant_slug) and CLI (listen keys issue --tenant).
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL DEFAULT '',
    -- External identity mappings (Wave 2+ OAuth flows fill these).
    -- NULL until customer connects via the corresponding integration.
    lark_tenant_key TEXT        UNIQUE,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenants_active
  ON tenants (slug) WHERE is_active = TRUE;

-- ─── 2. user_feedback ─────────────────────────────────────────
-- Merged schema (legacy main-backend migrations 062 + 160 + 161):
-- base columns + enrichment fields + tenant_id (now NOT NULL + FK).
CREATE TABLE IF NOT EXISTS user_feedback (
    id          BIGSERIAL    PRIMARY KEY,
    -- NOT NULL on the standalone RDS: listen owns ingest path 100%.
    -- ON DELETE RESTRICT so deleting a tenant first requires archiving
    -- their feedback (compliance + audit trail).
    tenant_id   TEXT         NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    user_id     TEXT         NOT NULL,
    -- Source channel marker so future non-app sources (lark group,
    -- email, web SDK) land in the same table. Validated in code.
    source      TEXT         NOT NULL DEFAULT 'api',
    source_meta JSONB        NOT NULL DEFAULT '{}'::jsonb,
    type        TEXT         NOT NULL DEFAULT 'other',
    content     TEXT         NOT NULL,
    page_url    TEXT         NOT NULL DEFAULT '',
    attachments JSONB        NOT NULL DEFAULT '[]'::jsonb,
    -- AI enrichment outputs (from main backend's migration 160).
    enriched_title    TEXT,
    enriched_kind     TEXT,
    enriched_modules  JSONB,
    enriched_severity TEXT,
    enriched_priority NUMERIC(5, 2),
    enrichment_status TEXT NOT NULL DEFAULT 'pending',
    enrichment_error  TEXT,
    enriched_at       TIMESTAMPTZ,
    -- Worker claim (formerly migration 002). Stale claim ≥ 5min is
    -- re-eligible — see service/enricher.go tryClaim semantics.
    enrichment_claimed_at TIMESTAMPTZ,
    -- Historical mirror columns (formerly migration 003). The mirror
    -- collaborator was abandoned in Wave 1.1; columns retained so an
    -- ops mistake reverting code doesn't crash on missing columns.
    lark_mirror_claimed_at TIMESTAMPTZ,
    lark_base_record_id    TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_feedback_created
  ON user_feedback (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_feedback_user
  ON user_feedback (user_id);
CREATE INDEX IF NOT EXISTS idx_user_feedback_tenant_created
  ON user_feedback (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_feedback_enrichment_status
  ON user_feedback (enrichment_status, created_at)
  WHERE enrichment_status IN ('pending', 'failed');
CREATE INDEX IF NOT EXISTS idx_user_feedback_enrichment_claim
  ON user_feedback (enrichment_status, enrichment_claimed_at)
  WHERE enrichment_status IN ('pending', 'failed', 'enriching');

-- ─── 3. external_api_keys ────────────────────────────────────
-- Per-tenant API key for the public ingest surface. Raw key shape:
-- "fbk_live_" + 32 hex chars; stored as sha256(raw) in key_hash.
CREATE TABLE IF NOT EXISTS external_api_keys (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     TEXT         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key_hash      BYTEA        NOT NULL,
    key_prefix    VARCHAR(20)  NOT NULL,
    label         VARCHAR(200) NOT NULL DEFAULT '',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_used_at  TIMESTAMPTZ,
    revoked_at    TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_api_keys_hash
  ON external_api_keys (key_hash);
CREATE INDEX IF NOT EXISTS idx_external_api_keys_tenant
  ON external_api_keys (tenant_id) WHERE is_active = TRUE;

COMMIT;
