-- Enrichment runtime control plane: desired policy, immutable history, and
-- per-instance applied status.

CREATE TABLE IF NOT EXISTS enrichment_runtime_policy (
    policy_key                 TEXT PRIMARY KEY,
    queue_len                  INTEGER NOT NULL,
    workers                    INTEGER NOT NULL,
    batch_size                 INTEGER NOT NULL,
    batch_window_ms            BIGINT NOT NULL,
    sweep_interval_ms          BIGINT NOT NULL,
    llm_rate_limit_enabled     BOOLEAN NOT NULL,
    llm_max_qps                DOUBLE PRECISION NOT NULL,
    llm_burst                  INTEGER NOT NULL,
    bootstrap_snapshot_version TEXT NOT NULL,
    spec_version               INTEGER NOT NULL,
    last_known_good_version    BIGINT NOT NULL DEFAULT 0,
    version                    BIGINT NOT NULL,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by                 TEXT NOT NULL,
    update_reason              TEXT NOT NULL DEFAULT '',
    CHECK (policy_key = 'default'),
    CHECK (queue_len > 0),
    CHECK (workers > 0),
    CHECK (batch_size > 0),
    CHECK (batch_window_ms > 0),
    CHECK (sweep_interval_ms > 0),
    CHECK (llm_max_qps >= 0),
    CHECK (llm_burst >= 0),
    CHECK (spec_version > 0),
    CHECK (version >= 0),
    CHECK (last_known_good_version >= 0)
);

CREATE TABLE IF NOT EXISTS enrichment_runtime_policy_history (
    id                         BIGSERIAL PRIMARY KEY,
    policy_key                 TEXT NOT NULL,
    version                    BIGINT NOT NULL,
    operation_type             TEXT NOT NULL,
    queue_len                  INTEGER NOT NULL,
    workers                    INTEGER NOT NULL,
    batch_size                 INTEGER NOT NULL,
    batch_window_ms            BIGINT NOT NULL,
    sweep_interval_ms          BIGINT NOT NULL,
    llm_rate_limit_enabled     BOOLEAN NOT NULL,
    llm_max_qps                DOUBLE PRECISION NOT NULL,
    llm_burst                  INTEGER NOT NULL,
    bootstrap_snapshot_version TEXT NOT NULL,
    spec_version               INTEGER NOT NULL,
    last_known_good_version    BIGINT NOT NULL DEFAULT 0,
    changed_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changed_by                 TEXT NOT NULL,
    change_reason              TEXT NOT NULL DEFAULT '',
    actor_type                 TEXT NOT NULL DEFAULT '',
    actor_id                   TEXT NOT NULL DEFAULT '',
    actor_ip                   TEXT NOT NULL DEFAULT '',
    actor_user_agent           TEXT NOT NULL DEFAULT '',
    session_id                 TEXT NOT NULL DEFAULT '',
    risk_level                 TEXT NOT NULL DEFAULT '',
    source_version             BIGINT NOT NULL DEFAULT 0,
    target_version             BIGINT NOT NULL DEFAULT 0,
    rollback_lineage           TEXT NOT NULL DEFAULT '',
    CHECK (policy_key = 'default'),
    CHECK (version > 0),
    CHECK (queue_len > 0),
    CHECK (workers > 0),
    CHECK (batch_size > 0),
    CHECK (batch_window_ms > 0),
    CHECK (sweep_interval_ms > 0),
    CHECK (llm_max_qps >= 0),
    CHECK (llm_burst >= 0),
    CHECK (spec_version > 0),
    CHECK (last_known_good_version >= 0),
    CHECK (operation_type IN ('update', 'reset', 'rollback')),
    CHECK (risk_level IN ('', 'normal', 'high'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_enrichment_runtime_policy_history_version
    ON enrichment_runtime_policy_history(policy_key, version);

CREATE INDEX IF NOT EXISTS idx_enrichment_runtime_policy_history_changed_at
    ON enrichment_runtime_policy_history(policy_key, changed_at DESC);

CREATE TABLE IF NOT EXISTS enrichment_runtime_instance_status (
    instance_id                TEXT PRIMARY KEY,
    boot_id                    TEXT NOT NULL,
    desired_version            BIGINT NOT NULL,
    observed_desired_version   BIGINT NOT NULL,
    runner_effective_version   BIGINT NOT NULL,
    limiter_effective_version  BIGINT NOT NULL,
    attempted_runner_version   BIGINT NOT NULL DEFAULT 0,
    attempted_limiter_version  BIGINT NOT NULL DEFAULT 0,
    runner_apply_status        TEXT NOT NULL,
    limiter_apply_status       TEXT NOT NULL,
    runner_last_apply_error    TEXT NOT NULL DEFAULT '',
    limiter_last_apply_error   TEXT NOT NULL DEFAULT '',
    queue_depth                INTEGER NOT NULL DEFAULT 0,
    queue_capacity_target      INTEGER NOT NULL DEFAULT 0,
    queue_capacity_effective   INTEGER NOT NULL DEFAULT 0,
    queue_resize_pending       BOOLEAN NOT NULL DEFAULT FALSE,
    in_flight                  INTEGER NOT NULL DEFAULT 0,
    degraded_reason            TEXT NOT NULL DEFAULT '',
    applied_spec_json          JSONB NOT NULL,
    heartbeat_interval_ms      BIGINT NOT NULL,
    stale_after_ms             BIGINT NOT NULL,
    expire_after_ms            BIGINT NOT NULL,
    last_applied_at            TIMESTAMPTZ,
    last_reconciled_at         TIMESTAMPTZ NOT NULL,
    last_seen_at               TIMESTAMPTZ NOT NULL,
    CHECK (desired_version >= 0),
    CHECK (observed_desired_version >= 0),
    CHECK (runner_effective_version >= 0),
    CHECK (limiter_effective_version >= 0),
    CHECK (attempted_runner_version >= 0),
    CHECK (attempted_limiter_version >= 0),
    CHECK (queue_depth >= 0),
    CHECK (queue_capacity_target >= 0),
    CHECK (queue_capacity_effective >= 0),
    CHECK (in_flight >= 0),
    CHECK (heartbeat_interval_ms > 0),
    CHECK (stale_after_ms > 0),
    CHECK (expire_after_ms > stale_after_ms),
    CHECK (runner_apply_status IN ('pending', 'applying', 'applied', 'failed', 'stale', 'degraded')),
    CHECK (limiter_apply_status IN ('pending', 'applying', 'applied', 'failed', 'stale', 'degraded'))
);

CREATE INDEX IF NOT EXISTS idx_enrichment_runtime_instance_status_last_seen
    ON enrichment_runtime_instance_status(last_seen_at DESC);
