-- SPDX-License-Identifier: Apache-2.0
--
-- Tenant-scoped Customer Request scoring settings.

CREATE TABLE IF NOT EXISTS customer_request_scoring_settings (
    tenant_id                 TEXT        PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    priority_none_weight      INT         NOT NULL DEFAULT 0,
    priority_low_weight       INT         NOT NULL DEFAULT 20,
    priority_medium_weight    INT         NOT NULL DEFAULT 40,
    priority_high_weight      INT         NOT NULL DEFAULT 60,
    priority_urgent_weight    INT         NOT NULL DEFAULT 80,
    feedback_weight           INT         NOT NULL DEFAULT 2,
    feedback_cap              INT         NOT NULL DEFAULT 80,
    customer_weight           INT         NOT NULL DEFAULT 5,
    customer_cap              INT         NOT NULL DEFAULT 100,
    account_weight            INT         NOT NULL DEFAULT 8,
    account_cap               INT         NOT NULL DEFAULT 120,
    vote_weight               INT         NOT NULL DEFAULT 4,
    vote_cap                  INT         NOT NULL DEFAULT 80,
    revenue_cents_per_point   BIGINT      NOT NULL DEFAULT 100000,
    revenue_cap               INT         NOT NULL DEFAULT 100,
    updated_by                TEXT        NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_customer_request_scoring_priority_none_weight CHECK (priority_none_weight BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_priority_low_weight CHECK (priority_low_weight BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_priority_medium_weight CHECK (priority_medium_weight BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_priority_high_weight CHECK (priority_high_weight BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_priority_urgent_weight CHECK (priority_urgent_weight BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_feedback_weight CHECK (feedback_weight BETWEEN 0 AND 1000),
    CONSTRAINT chk_customer_request_scoring_feedback_cap CHECK (feedback_cap BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_customer_weight CHECK (customer_weight BETWEEN 0 AND 1000),
    CONSTRAINT chk_customer_request_scoring_customer_cap CHECK (customer_cap BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_account_weight CHECK (account_weight BETWEEN 0 AND 1000),
    CONSTRAINT chk_customer_request_scoring_account_cap CHECK (account_cap BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_vote_weight CHECK (vote_weight BETWEEN 0 AND 1000),
    CONSTRAINT chk_customer_request_scoring_vote_cap CHECK (vote_cap BETWEEN 0 AND 10000),
    CONSTRAINT chk_customer_request_scoring_revenue_cents_per_point CHECK (revenue_cents_per_point BETWEEN 1 AND 100000000000),
    CONSTRAINT chk_customer_request_scoring_revenue_cap CHECK (revenue_cap BETWEEN 0 AND 10000)
);

CREATE OR REPLACE FUNCTION update_customer_request_scoring_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_customer_request_scoring_settings_updated_at ON customer_request_scoring_settings;
CREATE TRIGGER trg_customer_request_scoring_settings_updated_at
    BEFORE UPDATE ON customer_request_scoring_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_customer_request_scoring_settings_updated_at();

ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS chk_audit_action_value;
ALTER TABLE audit_log ADD CONSTRAINT chk_audit_action_value
    CHECK (action IN (
        'api_key.create',
        'api_key.revoke',
        'api_key.rotate',
        'audit_evidence.create',
        'audit_evidence.download',
        'audit_evidence.expire',
        'auth.mode_change',
        'breakglass.issue',
        'breakglass.use',
        'breakglass.revoke',
        'breakglass.expire',
        'breakglass.unlock_ip',
        'breakglass.approve',
        'breakglass.recovery_codes.generate',
        'breakglass.recovery_codes.use',
        'breakglass.recovery_codes.revoke',
        'service_account.create',
        'service_account.delete',
        'service_account.update',
        'customer_request.create',
        'customer_request.update',
        'customer_request.promote_feedback',
        'customer_request.link_feedback',
        'customer_request.unlink_feedback',
        'customer_request.link_customer',
        'customer_request.unlink_customer',
        'customer_request.add_vote',
        'customer_request.remove_vote',
        'customer_request.add_note',
        'customer_request.delete_note',
        'customer_request.merge',
        'customer_request.link_issue',
        'customer_request.unlink_issue',
        'customer_request.record_issue_sync',
        'customer_request.update_scoring_settings',
        'digest_subscription.delete',
        'digest_subscription.upsert',
        'enrich_config.activate_version',
        'enrich_config.promote_suggested',
        'enrich_config.update',
        'enrichment_runtime.reset',
        'enrichment_runtime.rollback',
        'enrichment_runtime.update',
        'feedback.batch_delete',
        'feedback_job.cancel',
        'gdpr.delete',
        'gdpr.delete.cancelled',
        'gdpr.delete.requested',
        'gdpr.export',
        'gdpr.export.revoked',
        'guard_policy.create',
        'guard_policy.delete',
        'guard_policy.update',
        'inbound_source.create',
        'inbound_source.delete',
        'inbound_source.pause',
        'inbound_source.resume',
        'inbound_source.rotate_secret',
        'inbound_source.test_connection',
        'llm_ability.delete',
        'llm_ability.upsert',
        'llm_channel.create',
        'llm_channel.delete',
        'llm_channel.test',
        'llm_channel.update',
        'llm_route.delete',
        'llm_route.upsert',
        'member.invite',
        'member.remove',
        'member.update_role',
        'notify_target.create',
        'notify_target.delete',
        'notify_target.test',
        'notify_target.update',
        'outbox.retry',
        'reply_draft.approve',
        'reply_draft.edit',
        'reply_draft.generate',
        'reply_draft.generate_blocked',
        'reply_draft.reject',
        'reply_draft.send.failure',
        'reply_draft.send.request',
        'reply_draft.send.success',
        'reply_draft.stale',
        'reply_send_hook.disable',
        'reply_send_hook.redeliver',
        'reply_send_hook.test',
        'reply_send_hook.upsert',
        'retry_enrichment',
        'tag.archive',
        'tag.create',
        'tag.update',
        'workflow_seed_defaults.run',
        'workflow_state.archive',
        'workflow_state.create',
        'workflow_state.update',
        'workflow_transition.replace',
        'mcp.list_feedback',
        'mcp.get_feedback',
        'mcp.list_workflow_states',
        'mcp.get_workflow_state',
        'mcp.list_tags',
        'mcp.update_workflow_state',
        'mcp.add_tag',
        'mcp.remove_tag',
        'mcp.set_urgent',
        'mcp.submit_feedback',
        'mcp.archive_tag',
        'mcp.batch_update_status',
        'mcp.batch_update_tags',
        'mcp.create_tag',
        'mcp.get_cluster',
        'mcp.get_digest',
        'mcp.get_enrichment_status',
        'mcp.get_usage_stats',
        'mcp.link_issue',
        'mcp.list_clusters',
        'mcp.list_dimensions',
        'mcp.mark_duplicate',
        'mcp.record_signal',
        'mcp.reclassify',
        'mcp.retry_enrichment',
        'mcp.search_feedback',
        'mcp.trigger_digest',
        'mcp.update_status',
        'mcp.update_tags',
        'mcp_client.create',
        'mcp_client.revoke',
        'mcp_client.update',
        'mcp_client.tool_policy_update',
        'mcp_refresh_grant.revoke',
        'mcp_session.revoke',
        'mcp_tool.authorize_denied',
        'mcp_tool.rate_limited'
    ));
