-- SPDX-License-Identifier: Apache-2.0
--
-- Anomaly & spike detection (#237): daily feedback-volume rollup buckets,
-- anomaly event records, per-tenant detection config, custom slice
-- definitions, and per-day detection run claims.

CREATE TABLE IF NOT EXISTS feedback_volume_buckets (
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    bucket_date     DATE NOT NULL,
    slice_type      TEXT NOT NULL,
    slice_key       TEXT NOT NULL,
    slice_display   TEXT NOT NULL DEFAULT '',
    config_version  INT  NOT NULL DEFAULT 1,
    feedback_count  BIGINT NOT NULL DEFAULT 0
        CONSTRAINT chk_volume_buckets_count_nonnegative CHECK (feedback_count >= 0),
    sample_feedback_ids BIGINT[] NOT NULL DEFAULT '{}',
    computed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, bucket_date, slice_type, slice_key),
    CONSTRAINT chk_volume_buckets_slice_type CHECK (
        slice_type IN ('total','source','dimension','cluster','cohort','custom')),
    CONSTRAINT chk_volume_buckets_slice_key_len CHECK (length(slice_key) BETWEEN 1 AND 120)
);

CREATE INDEX IF NOT EXISTS idx_volume_buckets_series
    ON feedback_volume_buckets (tenant_id, slice_type, slice_key, bucket_date DESC);
CREATE INDEX IF NOT EXISTS idx_volume_buckets_retention
    ON feedback_volume_buckets (bucket_date);

CREATE TABLE IF NOT EXISTS anomaly_events (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    slice_type        TEXT NOT NULL,
    slice_key         TEXT NOT NULL,
    slice_display     TEXT NOT NULL DEFAULT '',
    direction         TEXT NOT NULL
        CONSTRAINT chk_anomaly_events_direction CHECK (direction IN ('spike','drop')),
    first_bucket_date DATE NOT NULL,
    last_bucket_date  DATE NOT NULL,
    observed          BIGINT NOT NULL,
    expected_med      DOUBLE PRECISION NOT NULL,
    expected_low      DOUBLE PRECISION NOT NULL,
    expected_high     DOUBLE PRECISION NOT NULL,
    z_score           DOUBLE PRECISION NOT NULL,
    status            TEXT NOT NULL DEFAULT 'open'
        CONSTRAINT chk_anomaly_events_status CHECK (status IN ('open','resolved','retracted')),
    quality_action_id UUID REFERENCES feedback_quality_actions(id) ON DELETE SET NULL,
    evidence          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at       TIMESTAMPTZ,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_anomaly_events_open
    ON anomaly_events (tenant_id, slice_type, slice_key, direction)
    WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_anomaly_events_tenant_status
    ON anomaly_events (tenant_id, status, last_bucket_date DESC);

CREATE TABLE IF NOT EXISTS tenant_anomaly_configs (
    tenant_id           TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    sensitivity         TEXT NOT NULL DEFAULT 'medium'
        CONSTRAINT chk_anomaly_configs_sensitivity CHECK (sensitivity IN ('high','medium','low')),
    min_count           INT  NOT NULL DEFAULT 10
        CONSTRAINT chk_anomaly_configs_min_count CHECK (min_count BETWEEN 0 AND 10000),
    settle_delay_hours  INT  NOT NULL DEFAULT 3
        CONSTRAINT chk_anomaly_configs_settle_delay CHECK (settle_delay_hours BETWEEN 0 AND 48),
    enabled_slice_types TEXT[] NOT NULL
        DEFAULT '{total,source,dimension,cluster,cohort,custom}',
    drop_enabled_slice_types TEXT[] NOT NULL
        DEFAULT '{total,source,dimension,cohort,custom}',
    notify_mode         TEXT NOT NULL DEFAULT 'immediate'
        CONSTRAINT chk_anomaly_configs_notify_mode CHECK (notify_mode IN ('immediate','digest','off')),
    detection_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
    config_version      INT NOT NULL DEFAULT 1,
    backfill_version    INT NOT NULL DEFAULT 0,
    backfilled_at       TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS tenant_anomaly_custom_slices (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name        TEXT NOT NULL
        CONSTRAINT chk_anomaly_custom_slices_name CHECK (length(name) BETWEEN 1 AND 80),
    definition  JSONB NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    last_error  TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_anomaly_custom_slices_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS anomaly_detection_runs (
    tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    bucket_date  DATE NOT NULL,
    status       TEXT NOT NULL DEFAULT 'pending'
        CONSTRAINT chk_anomaly_runs_status CHECK (status IN ('pending','running','done','failed')),
    claimed_by   TEXT NOT NULL DEFAULT '',
    claimed_at   TIMESTAMPTZ,
    finished_at  TIMESTAMPTZ,
    error        TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (tenant_id, bucket_date)
);

-- Register anomaly detection audit actions in the append-only audit log.
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS chk_audit_action_value;
ALTER TABLE audit_log ADD CONSTRAINT chk_audit_action_value
    CHECK (action IN (
        'anomaly_config.update',
        'anomaly_custom_slice.create',
        'anomaly_custom_slice.delete',
        'api_key.create',
        'api_key.revoke',
        'api_key.rotate',
        'audit_evidence.create',
        'audit_evidence.download',
        'audit_evidence.expire',
        'auth.mode_change',
        'breakglass.approve',
        'breakglass.expire',
        'breakglass.issue',
        'breakglass.recovery_codes.generate',
        'breakglass.recovery_codes.revoke',
        'breakglass.recovery_codes.use',
        'breakglass.revoke',
        'breakglass.unlock_ip',
        'breakglass.use',
        'classification_review.record',
        'cohort.sync',
        'cohort.update',
        'cohort_source.create',
        'cohort_source.delete',
        'cohort_source.update',
        'customer_request.add_comment',
        'customer_request.add_note',
        'customer_request.add_vote',
        'customer_request.create',
        'customer_request.create_github_issue',
        'customer_request.delete_note',
        'customer_request.link_customer',
        'customer_request.link_feedback',
        'customer_request.link_issue',
        'customer_request.merge',
        'customer_request.promote_feedback',
        'customer_request.record_issue_sync',
        'customer_request.remove_vote',
        'customer_request.unlink_customer',
        'customer_request.unlink_feedback',
        'customer_request.unlink_issue',
        'customer_request.update',
        'customer_request.update_scoring_settings',
        'digest_subscription.delete',
        'digest_subscription.upsert',
        'enrich_config.activate_version',
        'enrich_config.promote_suggested',
        'enrich_config.update',
        'enrichment_runtime.reset',
        'enrichment_runtime.rollback',
        'enrichment_runtime.update',
        'external_connection.create',
        'external_connection.delete',
        'external_connection.qualify',
        'external_connection.resume',
        'external_connection.test',
        'external_connection.update',
        'external_provider_installation.create',
        'external_provider_installation.delete',
        'external_provider_installation.qualify',
        'external_provider_installation.resources_select',
        'external_sync_conflict.resolve',
        'external_sync_cursor.reset',
        'external_sync_event.replay',
        'external_sync_failure.retry',
        'external_sync_mapping.update',
        'external_sync_run.backfill',
        'external_sync_run.request',
        'external_sync_run.retry',
        'feedback.batch_delete',
        'feedback_assignment.policy_restore',
        'feedback_assignment.policy_update',
        'feedback_job.cancel',
        'gdpr.delete',
        'gdpr.delete.cancelled',
        'gdpr.delete.requested',
        'gdpr.export',
        'gdpr.export.revoked',
        'guard_policy.create',
        'guard_policy.delete',
        'guard_policy.update',
        'inbound_source.create',
        'inbound_source.delete',
        'inbound_source.pause',
        'inbound_source.resume',
        'inbound_source.rotate_secret',
        'inbound_source.sync_now',
        'inbound_source.test_connection',
        'inbound_source.update',
        'llm_ability.delete',
        'llm_ability.upsert',
        'llm_channel.create',
        'llm_channel.delete',
        'llm_channel.test',
        'llm_channel.update',
        'llm_route.delete',
        'llm_route.upsert',
        'mcp.add_tag',
        'mcp.archive_tag',
        'mcp.batch_update_status',
        'mcp.batch_update_tags',
        'mcp.create_tag',
        'mcp.get_cluster',
        'mcp.get_digest',
        'mcp.get_enrichment_status',
        'mcp.get_feedback',
        'mcp.get_usage_stats',
        'mcp.get_workflow_state',
        'mcp.link_issue',
        'mcp.list_clusters',
        'mcp.list_dimensions',
        'mcp.list_feedback',
        'mcp.list_tags',
        'mcp.list_workflow_states',
        'mcp.mark_duplicate',
        'mcp.reclassify',
        'mcp.record_signal',
        'mcp.remove_tag',
        'mcp.retry_enrichment',
        'mcp.search_feedback',
        'mcp.set_urgent',
        'mcp.submit_feedback',
        'mcp.trigger_digest',
        'mcp.update_status',
        'mcp.update_tags',
        'mcp.update_workflow_state',
        'mcp_client.create',
        'mcp_client.revoke',
        'mcp_client.tool_policy_update',
        'mcp_client.update',
        'mcp_refresh_grant.revoke',
        'mcp_session.revoke',
        'mcp_tool.authorize_denied',
        'mcp_tool.rate_limited',
        'member.invite',
        'member.remove',
        'member.update_role',
        'moderation.approve',
        'moderation.hide',
        'moderation.mark_spam',
        'moderation.reject',
        'moderation.restore',
        'notify_target.create',
        'notify_target.delete',
        'notify_target.test',
        'notify_target.update',
        'outbox.retry',
        'portal_submission.create',
        'public_policy.update',
        'public_request_profile.upsert',
        'reply_draft.approve',
        'reply_draft.edit',
        'reply_draft.generate',
        'reply_draft.generate_blocked',
        'reply_draft.reject',
        'reply_draft.send.failure',
        'reply_draft.send.request',
        'reply_draft.send.success',
        'reply_draft.stale',
        'reply_send_hook.disable',
        'reply_send_hook.redeliver',
        'reply_send_hook.test',
        'reply_send_hook.upsert',
        'request_notification.bounce',
        'request_notification.complaint',
        'request_notification.delivery_dead',
        'request_notification.delivery_retry',
        'request_notification.event_create',
        'request_notification.public_update_publish',
        'request_notification.sender_verify',
        'request_notification.settings_update',
        'request_notification.subscribe',
        'request_notification.suppress_contact',
        'request_notification.unsubscribe',
        'request_notification.webhook_target_create',
        'request_notification.webhook_target_delete',
        'request_notification.webhook_target_test',
        'request_notification.webhook_target_update',
        'retry_enrichment',
        'service_account.create',
        'service_account.delete',
        'service_account.update',
        'signal_subject.merge',
        'signal_subject.split',
        'survey.campaign_archive',
        'survey.campaign_create',
        'survey.campaign_update',
        'survey.hosted_link_create',
        'survey.invitation_delivery_retry',
        'survey.low_score_review_assign',
        'survey.low_score_review_batch_update',
        'survey.low_score_review_escalate',
        'survey.low_score_review_update',
        'survey.nps_run_cancel',
        'survey.nps_run_evidence_export',
        'survey.nps_run_schedule',
        'survey.provider_event_record',
        'survey.test_email_send',
        'tag.archive',
        'tag.create',
        'tag.update',
        'workflow_seed_defaults.run',
        'workflow_state.archive',
        'workflow_state.create',
        'workflow_state.update',
        'workflow_transition.replace'
    ));
